### ISSUE TITLE
Found a typo in RU locale

### ISSUE THREAD

**Issue by HaskuldrKrionskij** [rust-lang/www.rust-lang.org#1006]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/ru/learn/get-started

## What needs to be fixed?
увидтиле
https://github.com/rust-lang/www.rust-lang.org/blob/10570dff6d797a6ae188fecce30882ff336179fa/locales/ru/learn.ftl#L93

## Suggested Improvement
увидите

**Comment by Manishearth** [comment]
cc @funkill

**Comment by funkill** [comment]
Fixed on Pontoon. Also fixed some other typos.
