### ISSUE TITLE
Code with "error" does in fact compile

### ISSUE THREAD

**Issue by harry-zuzan** [rust-lang/www.rust-lang.org#1016]
# Content Bug Report

## Page(s) Affected
Please list the page or pages this bug is present on. Please file one issue
for each bug you find. Only file an issue for a multi-page bug if the bug is
indeed the *same* bug, across the pages.
https://doc.rust-lang.org/1.8.0/book/references-and-borrowing.html

## What needs to be fixed?
Tell us what content is causing the issue and *how* it is causing the issue.
For example, "The code sample was confusing because it used advanced Rust features",
or "The call to action on the community page was vague".
The code snippet on this page near the bottom
let y: &i32;
let x = 5;
y = &x;
println!("{}", y);
is not supposed to run because the reference y is declared before x.   But it does run on your site and if I compile it myself I get no error and the correct result.  That is 5.
## Suggested Improvement
(optional) Do you have a suggestion for how to fix the problem? Include your ideas
here.
A good Rust programmer (which I am not) needs to check the text, the code and the compiler error message which does not appear.

**Comment by XAMPPRocky** [comment]
@harry-zuzan Thank you for your issue! This is the repository for the website, not the Rust book, and that is an old version of the book. Rust has improved to the point where that is no longer a issue. I recommend reading the latest version of the book instead.

https://doc.rust-lang.org/book/
