### ISSUE TITLE
Add list of teams on /governance/teams/

### ISSUE THREAD

**Issue by jyn514** [rust-lang/www.rust-lang.org#1021]
# Content Feature Request
## Summary
https://www.rust-lang.org/governance/teams/ gives a 404, even though it has subpages at e.g. https://www.rust-lang.org/governance/teams/core. It would be nice for that to show a list of all the teams instead. Since the teams are already shown at https://www.rust-lang.org/governance#teams, https://www.rust-lang.org/governance/teams could just redirect there.

## Motivation
Why are we doing this? What use cases does it support? What is the expected
outcome?

I would like to be able to go from https://www.rust-lang.org/governance/teams/core to https://www.rust-lang.org/governance/teams/ to see the list of existing teams. Right now I have to look in the top bar, click governance, and then scroll down to 'Teams'.

## Drawbacks
Why should we _not_ do this?

No drawbacks that I am aware of.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?
- What other designs have been considered and what is the rationale for not
  choosing them?
- What is the impact of not doing this?

Redirecting to part of another page is slightly inelegant, I'm open to suggestions on that bit. Alternatively we could duplicate the entire contents of the 'Teams' subheader at /governance/teams or replace that subheader with a link.

## Maintenance
How will this content be maintained? Who will do it?

This will not need maintenance.

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?

N/A

**Comment by camelid** [comment]
I was thinking of doing this too!

@rustbot claim

**Comment by camelid** [comment]
@XAMPPRocky How do you redirect in Rocket? I tried this in `src/main.rs`, but I keep getting a 404:

```rust
#[get("/governance/<section>", rank = 1)]
fn teams(section: String) -> Option<Redirect> {
    if section == "teams" {
        Some(Redirect::to("/governance#teams"))
    } else if section == "wgs" {
        Some(Redirect::to("/governance#working-groups"))
    } else {
        None
    }
}
```

Here's some of the console output:

```
GET /governance/teams text/html:
    => Matched: GET /<category>/<subject> [4] (subject)
    => Error: Template 'governance/teams' does not exist.
```

**Comment by XAMPPRocky** [comment]
@camelid Well I believe that's correct as that page doesn't exist, right? The issue is about creating a `governance/teams` page.

**Comment by jyn514** [comment]
@XAMPPRocky right, @camelid just tried to add it, notice the `section == "teams"`.

You have `get("/governance/<section>")`, but the error says `<category>/<subject>`. Maybe the wrong pattern matched?

**Comment by Manishearth** [comment]
No, this won't work because it will override the `governance/<team>` one. You'll need to hardcode `governance/teams` and `governance/wgs`

**Comment by camelid** [comment]
Hmm, I tried a bunch of different ranks and none of them worked. I also tried hardcoding just now, but that didn't work either – I got the same error.

## Code

```rust
#[get("/governance/teams")]
fn teams() -> Redirect {
    Redirect::to("/governance#teams")
}

#[get("/governance/wgs")]
fn wgs() -> Redirect {
    Redirect::to("/governance#working-groups")
}
```

## Console

```
GET /governance/teams text/html:
    => Matched: GET /<category>/<subject> [4] (subject)
    => Error: Template 'governance/teams' does not exist.
```

What should I do?
```

**Comment by Manishearth** [comment]
You may need to tweak the priorities

**Comment by camelid** [comment]
You mean increase the rank of `/<category>/<subject>`?

**Comment by camelid** [comment]
I increased the rank (aka, decreased priority) of `/<category>/<subject>` from 4 to 8, and it still doesn't work :(

**Comment by Manishearth** [comment]
I don't know then.

You could just edit the governance handler to do this special case
