### ISSUE TITLE
Link to community Discord

### ISSUE THREAD

**Issue by wwkeyboard** [rust-lang/www.rust-lang.org#1028]
### Summary
Add a link to the community discord.

### Motivation
When I see references to the "community Discord" I head to the community page of the website and click on the discord button. This does not lead to the Discord that is colloquially known as the community Discord. Instead it leads to the internals Discord.

### Drawbacks
There is history between the two services, the community one does not appear to be official so linking to it from the main website may require other organization changes first.

### Rationale and alternatives
The current state is confusing. An alternative may be to better designate that the link on this page is to the Discord about the development OF Rust instead of development WITH Rust.

### Maintenance
The premalink to the community Discord will need to be created. Any new text will need to be translated into all supported languages.

This is a proposal of what it could look like:

![dualdiscorddesigndrawing](https://user-images.githubusercontent.com/105435/76108297-ebe03680-5f9f-11ea-9f13-c073c97a504c.png)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! We don't want link to community resources as there are multiple community discords. Picking one could be favouritism and it could be confused as part of the org when that is not the case.
