### ISSUE TITLE
provide link to forge.rust-lang.org on a page

### ISSUE THREAD

**Issue by mobop** [rust-lang/www.rust-lang.org#1075]
i need to use search engine to find it.

**Comment by mobop** [comment]
https://github.com/rust-lang/rust-forge/issues/337#issuecomment-615955502

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I would accept a PR that adds a link to forge in the footer. While I'm sure there is a more prominent place we could put it. Putting it in the footer seems like the easiest step we can take for now.

**Comment by mobop** [comment]
i am not asking to put it in the footer. 
you should discuss with others on this topic.

**Comment by XAMPPRocky** [comment]
I know, but putting it in the footer makes it available on every page, and its not like we can't have linked in multiple places. Having it in the footer is a good start.

**Comment by mobop** [comment]
so, please do it.

**Comment by mobop** [comment]
but what will you call it?
> Rust Forge

**Comment by XAMPPRocky** [comment]
> ok, then do it.

This is a volunteer project, I don't have time to add this right this moment. If you'd like it done sooner you're more than welcome to make a PR.

**Comment by mobop** [comment]
i am out
