### ISSUE TITLE
Very little mistake in Chapter 2 (guessing game) code

### ISSUE THREAD

**Issue by n-gram-hub** [rust-lang/www.rust-lang.org#1082]
### What needs to be fixed?
The secret number should be generated inside the loop, while from the example the user infers it is above the loop.
```

/ --snip--

    println!("The secret number is: {}", secret_number);

    loop {
        println!("Please input your guess.");

        // --snip--

        match guess.cmp(&secret_number) {
            Ordering::Less => println!("Too small!"),
            Ordering::Greater => println!("Too big!"),
            Ordering::Equal => println!("You win!"),
        }
    }
}
```

### Page(s) Affected
https://doc.rust-lang.org/1.31.0/book/ch02-00-guessing-game-tutorial.html

### Suggested Improvement
Put the code inside the loop or it will always generate the same number

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However this repository is for the rust website, where as that content is from the rust book. I would recommend filing an issue on [rust-lang/book](https://github.com/rust-lang/book) instead.

**Comment by n-gram-hub** [comment]
> Thank you for your issue! However this repository is for the rust website, where as that content is from the rust book. I would recommend filing an issue on [rust-lang/book](https://github.com/rust-lang/book) instead.

Sorry!   :-)
