### ISSUE TITLE
a complicated journey to find "how to install minimal profile"

### ISSUE THREAD

**Issue by LucianoBestia** [rust-lang/www.rust-lang.org#1095]
I wanted to install rust with the minimal profile on my web server. 
It looks easy, but the documentation is difficult to find and it is on many different places.
First I tried the obvious:
<https://www.rust-lang.org/tools/install>. 
I have a Win10 workstation, but my server is linux. So I click "other installation options". 
<https://forge.rust-lang.org/infra/other-installation-methods.html>
A lot of info, but not what I need.
I found on google there is a dedicated rustup web site:
<https://rustup.rs/>
It is different from rust-lang.org, but not enough informative. Here also we have "other installation options", but it does not lead to the same page. It goes to github:
<https://github.com/rust-lang/rustup#other-installation-methods>
And here finally I found instructions how to install the minimal profile.
All this websites and pages look very fragmented. I miss one place where all this info converges.

**Comment by XAMPPRocky** [comment]
Thank you for your feedback! The install page is one thing I definitely want to redesign to consolidate and improve the installation experience.

**Comment by Manishearth** [comment]
Yeah, that's a pretty hard-to-discover step. I'm wary of overcomplicating the install page itself and making it intimidating, but we should definitely have this information consolidated somewhere in a discoverable fashion.
