### ISSUE TITLE
Overlapping content at the bottom of the start page

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/www.rust-lang.org#1111]
### Page(s) Affected

https://www.rust-lang.org/

### What needs to be fixed?

Al the way at the bottom, things look like this:
![Screenshot_2020-05-14 Rust Programming Language](https://user-images.githubusercontent.com/330628/81958165-dd507400-960d-11ea-85e1-0bb6ebc4ee00.png)

That is probably not intended. :)
Other pages (e.g. https://www.rust-lang.org/production) look fine.

This is with Firefox 77.0b5 on Linux.

**Comment by XAMPPRocky** [comment]
Using Firefox 76 on macOS and I can't replicate this bug, so I'm assuming this is a bug in Firefox itself rather than with the website.

**Comment by RalfJung** [comment]
Okay, I will report this as a webcompat issue as well and see what they say.

**Comment by RalfJung** [comment]
Oh what the... now when I look again the problem is gone??

**Comment by RalfJung** [comment]
I'm not sure if this is maybe a race condition in the website or the browser, but I cannot reproduce this any more. I'm happy I made a screenshot, that proves at least I was not hallucinating...

**Comment by Mark-Simulacrum** [comment]
I think I've seen this sort of thing in Firefox before on random sites and indeed a refresh usually makes it go away. No idea what's up with it -- but probably not our bug?
