### ISSUE TITLE
Prevent "fi" legature in "efficient"

### ISSUE THREAD

**Issue by bill-myers** [rust-lang/www.rust-lang.org#1120]
### Page(s) Affected
Homepage

### What needs to be fixed?
The word "efficient" is rendered, at least on my Firefox instance, using a "fi" ligature rather than "f" and "i" glyphs, which is pretty weird since it results in the two "f" letters looking different.

### Suggested Improvement
Prevent the usage of that ligature by inserting the zero-width joiner "\&zwnj;", i.e. rewriting "efficient" to "eff\&zwnj;icent"

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yes it shouldn't have been "fi", I've now replaced it with the correct ligature.

**Comment by Manishearth** [comment]
We shouldn't be using the unicode ligatures at all (there are pretty rare use cases for using those), and in this case it makes it strictly worse

![image](https://user-images.githubusercontent.com/1617736/83056950-183da900-a00b-11ea-850a-b2d4834aaff4.png)


It seems like Fira sans has a ligature for `fi` but not `ffi`. I don't see a pressing need to diverge from the font.

**Comment by Manishearth** [comment]
I reverted it. The ZWJ approach seems okay (we might actually want a ZWNJ?), but i'm not convinced we should be diverging from the font. @bill-myers can you post a screenshot of what you see?

Here's what I get:

![image](https://user-images.githubusercontent.com/1617736/83057326-a154e000-a00b-11ea-9d19-278cfb8cb42d.png)

this kind of thing is pretty standard with `fi`-ligatures, often an `ffi` will have a slightly different second `f`

**Comment by XAMPPRocky** [comment]
That must be a Firefox issue as on safari the ligature renders as I would expect.
<img width="675" alt="Screenshot 2020-05-27 at 20 22 51" src="https://user-images.githubusercontent.com/4464295/83057937-e56dd200-a057-11ea-9a1e-1e3337dc2835.png">

**Comment by bill-myers** [comment]
This is on Firefox on Ubuntu, normal DPI, no zoom/scaling.

![rust](https://user-images.githubusercontent.com/4647491/83060512-de48c300-a05b-11ea-876b-b1129bd4a789.png)

**Comment by bill-myers** [comment]
BTW, "font-variant-ligatures: none" in CSS may be a better fix than adding the zero-width character.

**Comment by bill-myers** [comment]
Also, changing "font-size: 36px" to "font-size: 37px" makes it look fine on my machine.

**Comment by XAMPPRocky** [comment]
@Manishearth What version is your browser? I can't replicate that screenshot. Both Firefox and chrome render correctly.

## Safari
<img width="675" alt="Screenshot 2020-05-27 at 20 22 51" src="https://user-images.githubusercontent.com/4464295/83062725-61b7e380-a05f-11ea-9763-54e676fdf78e.png">
## Firefox
<img width="696" alt="Screenshot 2020-05-27 at 21 13 53" src="https://user-images.githubusercontent.com/4464295/83062647-42b95180-a05f-11ea-8bfd-ec9d0aaf7b7a.png">

## Chrome
<img width="690" alt="Screenshot 2020-05-27 at 21 12 44" src="https://user-images.githubusercontent.com/4464295/83062668-4d73e680-a05f-11ea-8287-eeaa1005e44e.png">

**Comment by bill-myers** [comment]
I think it depends on the OS, and in particular Linux seems to be the problem (I assume you tested OSX or Windows since you include Safari)

**Comment by Manishearth** [comment]
@XAMPPRocky this is not a browser issue, this is a font issue

but in general the unicode ligature characters should not be used. If a font has a ligature, it will automatically apply it where it deems fit, we shouldn't be messing with the stylistic choices made by fonts

**Comment by Manishearth** [comment]
Yes, we can apply font-variant-ligatures. Only on the English version though

**Comment by XAMPPRocky** [comment]
Okay, sounds good to me. I’m going to close this as wontfix.
