### ISSUE TITLE
ch10-01-syntax.html#generic-data-types self vs &self

### ISSUE THREAD

**Issue by jehugaleahsa** [rust-lang/www.rust-lang.org#1121]
### What needs to be fixed?
I was reading the section on generic data types and I noticed in the `mixup` function, `self` is being passed taking ownership rather than borrowing. Sorry, I'm new to Rust so I am not sure how to phrase that. Should it be `&self` instead of `self`?

### Page(s) Affected
https://doc.rust-lang.org/stable/book/ch10-01-syntax.html Listing 10-11: A method that uses different generic types from its struct’s definition

### Suggested Improvement
I am new, so what's there might be totally correct, but it seems like borrowing would make more sense. On the chapter that introduces `impl` and method syntax it made it sounds like passing `self` is for very special use cases. My understanding is `p1` in that example would be unusable after calling `mixup`.

**Comment by Manishearth** [comment]
This should be filed on github.com/rust-lang/book/
