### ISSUE TITLE
Getting started page says "Is rustup up to date?" not "Is Rust up to date?"

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1137]
### What needs to be fixed?

The getting started page has a header that says "Is rustup up to date?" where I would expect it to say "Is Rust up to date?".

I'm not sure if this is intentional, but I figured I should point it out because it seemed confusing to me.

### Page(s) Affected

[Getting started](https://www.rust-lang.org/learn/get-started)

### Suggested Improvement

Replace the header "Is rustup up to date?" with "Is Rust up to date?".

**Comment by ayushmishra2005** [comment]
@camelid It is `rustup` . It is a tool, which is managed by Rust.

**Comment by Manishearth** [comment]
Well, yes, but it's really "the rust managed by rustup" that's outdated. I see a case for either, though it makes slightly more sense for it to say "is rust out of date" imo

**Comment by Fasani** [comment]
@XAMPPRocky this can be closed :-)
