### ISSUE TITLE
language code for chinese needs updates

### ISSUE THREAD

**Issue by aohan237** [rust-lang/www.rust-lang.org#1139]
zh-CN represents  "Simplified Chinese" and zh-TW represents "Traditional Chinese"

so language code should changed into 

LANGUAGES = (
    ('zh-hans', _('Simplified Chinese')),
    ('zh-hant', _('Traditional Chinese'))
)
like code in other programming language

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I’m afraid I’m out of my depth on Chinese locales to feel comfortable making any kind of change. Cc @crlf0710

**Comment by crlf0710** [comment]
@XAMPPRocky It seems there're two different issues going on here.
1. In the Pontoon locale list it would improve a little to change `zh-CN` to `zh-Hans-CN` and `zh-TW` to `zh-Hant-TW` to recognize the script difference between Hans and Hant. (should it be reported upstream?)
2. We have a small inconsistency here when we supply `en-US` with the description `English` and supply `zh-Hans-CN` with the description `简体中文`(Simplified Chinese, which corresponds to zh-Hans prefix).

I'm not sure if it's worth the churn though.

**Comment by Manishearth** [comment]
So firstly, zh-CN _is_ zh-Hans-CN, much like how en-US is en-Latn-US.

It's _technically_ correct that zh-Hans is the way to represent "simplified chinese", however using zh-CN vs zh-TW is far more common and is what users are mostly used to (google does this!). I believe when making these changes I had started out with zh-Hans and zh-Hant and was asked to change them.
