### ISSUE TITLE
remove unnecessary white spaces and empty lines before deploying

### ISSUE THREAD

**Issue by edcded** [rust-lang/www.rust-lang.org#1153]
many people have to pay for every byte they receive.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However our responses are already encoded with gzip so removing extra whitespace will not really save us any bytes over the wire in practice. There are much more meaningful improvements (such as providing cache headers) that we could make to reduce our footprint.

**Comment by edcded** [comment]
rust is by Mozilla and their website is this. what the hell is wrong?
