### ISSUE TITLE
Вычисления с большими числами

### ISSUE THREAD

**Issue by Vladimir66R** [rust-lang/www.rust-lang.org#1158]
Прошу прощения, может плохо искал, но есть маленькая проблема, так расчет числа 2_f64.powf(64.0)-1.0 дает неправильный ответ (=18446744073709552000). Подскажите пожалуйста с чем это может быть связано и как обходить подобные проблемы.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However this is a repository for the rust website not for help with the programming language, I would recommend asking on the Rust discord or Zulip instead.

- [Zulip](https://rust-lang.zulipchat.com)
- [Discord](https://discord.gg/rust-lang)
