### ISSUE TITLE
Cargo builds the deepspeech library twice?

### ISSUE THREAD

**Issue by bhamilton2591** [rust-lang/www.rust-lang.org#1163]
I first ran this problem by the people responsible for deepspeech-rs.  After review, I was told this appeared to be a cargo problem and to open an issue here.

~/deepspeech-rs $ cargo run --verbose --release --example client /home/pi/Downloads/ /home/pi/Downloads/audio/2830-3980-0043.wav
       Fresh hound v3.4.0
       Fresh alac v0.3.3
       Fresh sample v0.9.1
       Fresh claxon v0.4.2
       Fresh byteorder v1.3.4
       Fresh libc v0.2.71
       Fresh deepspeech-sys v0.7.0
       Fresh deepspeech-sys v0.7.0 (/home/pi/deepspeech-rs/sys)
       Fresh deepspeech v0.7.0
       Fresh ogg v0.5.1
       Fresh caf v0.1.0
       Fresh lewton v0.7.0
       Fresh audrey v0.2.0
   Compiling deepspeech v0.7.0 (/home/pi/deepspeech-rs)
     Running `rustc --crate-name client examples/client.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=45c9c7b6f4f5974a -C extra-filename=-45c9c7b6f4f5974a --out-dir /home/pi/deepspeech-rs/target/release/examples -L dependency=/home/pi/deepspeech-rs/target/release/deps --extern audrey=/home/pi/deepspeech-rs/target/release/deps/libaudrey-04d87e6302404fc9.rlib --extern deepspeech=/home/pi/deepspeech-rs/target/release/deps/libdeepspeech-8c31f94611999af5.rlib --extern deepspeech=/home/pi/deepspeech-rs/target/release/deps/libdeepspeech-f5785e43f263827b.rlib --extern deepspeech_sys=/home/pi/deepspeech-rs/target/release/deps/libdeepspeech_sys-175b4a4ae9f8bf87.rlib --extern libc=/home/pi/deepspeech-rs/target/release/deps/liblibc-660d6d0feecc043c.rlib`
error[E0465]: multiple rlib candidates for `deepspeech` found
 --> examples/client.rs:1:1
  |
1 | extern crate deepspeech;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1: /home/pi/deepspeech-rs/target/release/deps/libdeepspeech-8c31f94611999af5.rlib
 --> examples/client.rs:1:1
  |
1 | extern crate deepspeech;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /home/pi/deepspeech-rs/target/release/deps/libdeepspeech-f5785e43f263827b.rlib
 --> examples/client.rs:1:1
  |
1 | extern crate deepspeech;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0463]: can't find crate for `deepspeech`
 --> examples/client.rs:1:1
  |
1 | extern crate deepspeech;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

**Comment by est31** [comment]
Btw cargo repo is over here: https://github.com/rust-lang/cargo/
