### ISSUE TITLE
Home page layout improvements

### ISSUE THREAD

**Issue by Fasani** [rust-lang/www.rust-lang.org#1172]
### Page(s) Affected
Home page

### What needs to be fixed?
I find the current alignments all a bit odd (See image)

### Suggested Improvement
I would propose the following improvements. Assuming the approach works across all the various language versions and ensuring responsive design still looks good and performs as expected.

1) Pull logo right
2) Pull menu left
3) Pull Rust and subheading left
4) Pull button right
5) Reduce space until the next section

<img width="1434" alt="Screenshot 2020-07-03 at 22 38 05" src="https://user-images.githubusercontent.com/448410/86496750-ff997f00-bd7e-11ea-8514-cebb8963f44f.png">

**Comment by Fasani** [comment]
It seems there was no objection to this change so I will go ahead with it.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Sorry I haven’t had time to write a response as I want to properly respond. In short I would approve a PR that implements 3 + 4, but I would want to discuss and think about the header and hero design more before changing them further.

**Comment by Fasani** [comment]
Ok I will do 3+4
