### ISSUE TITLE
Underline and spacing for headings look different on staging

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1173]
### Page(s) Affected
It looks like it's on any page with headings on www-staging.rust-lang.org

### What needs to be fixed?
The underline thickness and the margin below headings look different than the deployed site. I'm not sure if this is intentional, but I thought it might be a regression.

**Comment by camelid** [comment]
Here are some screenshots for comparison:

## Deployed

![image](https://user-images.githubusercontent.com/37223377/86519535-715de100-bdf0-11ea-8bc6-9b0a83e850b9.png)


## Staging

![image](https://user-images.githubusercontent.com/37223377/86519530-66a34c00-bdf0-11ea-867d-e8ab19671340.png)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! It is an intentional change, see #1165 for more context.
