### ISSUE TITLE
Website hasn't been deployed since May 21

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1174]
The [`deploy`](https://github.com/rust-lang/www.rust-lang.org/tree/deploy) branch hasn't been updated since May 21. I don't know if this is intentional or not, but I figured I should file an issue just in case.

Cc @XAMPPRocky

**Comment by XAMPPRocky** [comment]
I’ll fix that.

**Comment by camelid** [comment]
Looks like it's deployed!
