### ISSUE TITLE
Add link to r-l zulip

### ISSUE THREAD

**Issue by tinaun** [rust-lang/www.rust-lang.org#1183]
### Summary
The r-l zulip should be linked along with the discord in the community section of the website.

### Motivation
more and more development is moving to zulip, and the discord gets people asking questions which are then redirected to the zulip all the time.

### Drawbacks
we might get more drive by spam in the zulip.

**Comment by Fasani** [comment]
IMO, This task needs clarification.

My understanding is these requests are in relation to the compiler team specifically? I am not sure if flooding their zulip would be the correct approach from a link on the community page. I think if you want the chat button to be added it should be added here: https://www.rust-lang.org/governance/teams/compiler

This may not completely stop the need to redirect people from the discord. But as it looks like there are 11 teams (http://127.0.0.1:7878/governance) it would feel like adding an additional button to the general community page may not be the correct approach?

If the request is to add a button to the community page then I can also do it no problem, just wanted to share my thoughts/clarify this topic.

Also if someone takes this task you should probably wait for this branch to be merged first.
https://github.com/rust-lang/www.rust-lang.org/pull/1188

**Comment by Manishearth** [comment]
Different teams use different channels, the ones who use zulip should have that mentioned on their page.

I think it's fine to link both on the community page, the discord is not any more informal than the zulip, both are primarily venues for getting work done.

**Comment by XAMPPRocky** [comment]
Yeah, I think linking to zulip on governance pages is separate from discussed issue here which is just linking to the main zulip instance on community. I'll make a separate issue for the governance pages.

**Comment by camelid** [comment]
I think this can be closed:

![image](https://user-images.githubusercontent.com/37223377/98449931-eb7adb00-20ec-11eb-9261-ea140c92ef39.png)
