### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Aadit017** [rust-lang/www.rust-lang.org#1189]
please i need some type of guide for rust which teaches me evrything from scratch .... and also has some programming question in between because i really want to learn the language ........

**Comment by XAMPPRocky** [comment]
Thank you for your issue! however this is repository for the rust website, I would recommend going to https://www.rust-lang.org/learn where you will find plenty of resources to learn the language. If you have any questions feel free to head over to our Discord or Zulip and ask any questions you have there.
