### ISSUE TITLE
Broken link on "Code of conduct" page

### ISSUE THREAD

**Issue by jhernandis** [rust-lang/www.rust-lang.org#1212]
Hi, on the Code of conduct page (https://www.rust-lang.org/policies/code-of-conduct) the link to the "Citizen Code of Conduct" seems to be broken or that page are not working.

Thanks.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've also found a related issue on https://github.com/rust-lang/rust/issues/57402 I think we can replace the link with the GitHub version mentioned in it if anyone wants to make a small PR.

https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

**Comment by jhernandis** [comment]
Sorry, I didn't do a search before post the issue.

**Comment by XAMPPRocky** [comment]
@jhernandis It's no problem, I think this repository is a more appropriate place for this issue. Since the actual content is here.

**Comment by aa-deet-eeya** [comment]
Is this still available? 
I would like to work on this, should I go on to replace http://citizencodeofconduct.org/ with the [GitHub link](https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md)?

**Comment by pietroalbini** [comment]
The link has been changed, thanks @aa-deet-eeya!

Whether we want to inline the definition or not is tracked at https://github.com/rust-lang/core-team/issues/17.
