### ISSUE TITLE
Documentation pages are not displayed in Opera Mini

### ISSUE THREAD

**Issue by bodqhrohro** [rust-lang/www.rust-lang.org#1223]
### Page(s) Affected
For example, http://doc.rust-lang.org/std/vec/struct.Vec.html (lots of them actually, probably all).

### What needs to be fixed?
It's just a typical case when Opera Mini transcoders try to execute JS, but do it partially and thus break the page at all :/
![2020-08-12-152012_1366x768_scrot](https://user-images.githubusercontent.com/2134486/90014306-7e9fa280-dcaf-11ea-9614-ac1d97c52a2a.png)
![2020-08-12-152041_1366x768_scrot](https://user-images.githubusercontent.com/2134486/90014327-8c552800-dcaf-11ea-964e-df0ba5e30673.png)
It's not even a layout problem, as the page is empty in Mobile View too.

### Suggested Improvement
The documentation is almost plain HTML by its nature, unlike brand new web apps that need bleeding edge technologies, so I see no reasons to make it inaccessible in outdated browsers.

I see non-transpilled ES6 lambdas here that cause a syntax error, but that may be only a part of the problem.

As a last resort, if the root cause is hard to find, scripts may be disabled at all for Opera Mini by detecting the `window.operamini` object. That's an ugly quirk, but there already are IE detections in the code, so why not? :)

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However this a repository for the rust website which separate from the documentation. So I'm going to close this and I would recommend you open an issue on rust-lang/rust instead.
