### ISSUE TITLE
Add a note about installing gcc for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by navneethc** [rust-lang/www.rust-lang.org#1247]
### What needs to be fixed?

The section for Windows Subsystem for Linux includes just the part to install rustup. However, this will not be sufficient as will be evident when one tries to compile their program the first time. (Assuming they don't already have `gcc` installed.)

Example error:

```
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `fibonacci`.
```

### Page(s) Affected

When visiting the page from Windows:

- https://www.rust-lang.org/learn/get-started 
- https://www.rust-lang.org/tools/install

### Suggested Improvement

 Add an instruction to install gcc or build-essential.

**Comment by seritools** [comment]
This seems like a general linux thing, not related to WSL.

**Comment by navneethc** [comment]
It may well be, but when one's intention is to install Rust in WSL and they are automatically redirected to the Windows version of the page with specific instructions for WSL, they are unlikely to search for the page with instructions for Linux.

**Comment by navneethc** [comment]
My bad. This issue is already covered here: https://github.com/rust-lang/www.rust-lang.org/issues/1012.
