### ISSUE TITLE
Yelp isn't listed on the "production users" page

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1248]
### What needs to be fixed?
Yelp isn't listed on the "production users" (/production/users) page, even though it's featured on the "production" page (/production).

### Page(s) Affected
/production/users

**Comment by senekor** [comment]
I'm gonna close this, as it doesn't seem very important. (Please respond if you disagree.) Yelp simply isn't in the `src/data/users.yml` file.

I'm guessing if there is an effort at some point to redo the content of the website, this company list likely wouldn't make the cut anyway. Rust has achieved great adoption by now, an explicit list of users seems out of place.
