### ISSUE TITLE
Bold important part of security policy

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1251]
What do you think of **bolding** this part of the security policy to make absolutely sure that people see it?

Currently, it's like this:

![image](https://user-images.githubusercontent.com/37223377/91645682-ed913100-e9fb-11ea-9c52-369714d01004.png)

I propose something like this:

![image](https://user-images.githubusercontent.com/37223377/91645699-0a2d6900-e9fc-11ea-9c02-21caf318aac9.png)

**Comment by pietroalbini** [comment]
Hmm, I'm not sure it's necessary. The policy is not that long where bolding is important, and I would expect any security researcher not to skim it.
