### ISSUE TITLE
Use the disc list type instead of circle

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1252]
### Summary
Right now, unordered lists (`ul`s) have the `circle` list style:

![image](https://user-images.githubusercontent.com/37223377/91669269-76759e80-eac8-11ea-8ad3-f27faaf026da.png)

I propose changing this to the `disc` list style, which is in my experience more common:

![image](https://user-images.githubusercontent.com/37223377/91669282-90af7c80-eac8-11ea-8d93-3818a39eba22.png)

### Motivation
1. The circle list type looks a bit out-of-place on the Rust website since a lot of the Rust website has a "filled-in" design, e.g., buttons: 
![image](https://user-images.githubusercontent.com/37223377/91669544-87271400-eaca-11ea-9ae0-d1c2921b787a.png)
2. The circles are also so thin that they look pixelated
3. Discs would stand out more on the page so you can clearer see that it's a list
4. Other parts of Rust, e.g. mdBooks, use the `disc` list type:
![image](https://user-images.githubusercontent.com/37223377/91669372-58f50480-eac9-11ea-9533-9368215e8923.png)
5. In my experience, the `disc` list type is more common on websites than the `circle` list type, so it's a bit jarring for someone used to the other style

### Drawbacks
It might be bikeshedding :)

### Rationale and alternatives
- Why is this design the best in the space of possible designs?
- What other designs have been considered and what is the rationale for not
  choosing them?
- What is the impact of not doing this?

See the "Motivation" section

### Maintenance
N/A

### Unresolved Questions
N/A

---

@rustbot modify labels: A-design

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Changing the bullet style makes sense to me.
