### ISSUE TITLE
www-staging doesn't seem to be getting deployed

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1256]
E.g., the button fix I made 3 days ago (#1250) still hasn't shown up on https://www-staging.rust-lang.org:

![image](https://user-images.githubusercontent.com/37223377/91777647-494aee00-eba5-11ea-9011-2b6e701c46c5.png)

Note: I have tried force-refreshing (Shift-Command-R).

---

@rustbot modify labels: A-Infra C-Bug

**Comment by Manishearth** [comment]
Oh, i suspect someone needs to re-set-up deploy on Heroku cc @pietroalbini

**Comment by pietroalbini** [comment]
Configured automatic deploys again.

**Comment by camelid** [comment]
Hmm, it still hasn't updated. Does it need a push to master to deploy the latest version?

**Comment by Manishearth** [comment]
Yes
