### ISSUE TITLE
Wrong display for escaped characters in Zulip streams

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/www.rust-lang.org#1274]
### What needs to be fixed?
URL-escaped characters, e.g. `/`, are displayed as their escaped counterpart in Zulip stream names.

### Page(s) Affected
All `/governance` teams/WGs who have attached Zulip streams containing an escaped character. For example, see all WGs that are subteams of `T-compiler`.

### Suggested Improvement
The website should probably use the raw data from `rust-lang/team`. #1235 might be reworked to store both displayable strings and escaped strings to create the links.

**Comment by camelid** [comment]
Can you give an example of one of the WGs under the t-compiler stream? I checked pretty much all of the WGs on /governance and none of them are under the t-compiler stream.

**Comment by LeSeulArtichaut** [comment]
Here's an example:

![](https://user-images.githubusercontent.com/38361244/98582895-da37f700-22c3-11eb-8d7d-107ef55874ff.png)

Notice how the Zulip button reads `#t-compiler.2fwg-diagnostics` instead of `#t-compiler/wg-diagnostics`

**Comment by camelid** [comment]
This is actually much more involved than I thought at first :/

@rustbot release-assignment

**Comment by LeSeulArtichaut** [comment]
I guess this could be solved in `rust_team_data` by doing the URL conversion thing there, so that both the name and the escaped link are availible in `Team`.
