### ISSUE TITLE
cargo new section is explanation and not a step

### ISSUE THREAD

**Issue by ryanbrookepayne** [rust-lang/www.rust-lang.org#1285]
### Page(s) Affected

https://www.rust-lang.org/learn/get-started

### What needs to be fixed?

The following part confused me.

> cargo new generates a "Hello, world!" project for us! We can run this program by moving into the new directory that we made and running this in our terminal:

I had already run `cargo new hello-rust` but then I thought I had to run `cargo new` again. The above section is an explanation and not a step.

See https://stackoverflow.com/q/64121582/11809808 for context.

### Suggested Improvement

Make it more clear the that `cargo new` section is an explanation and not a step in the getting started process.

**Comment by ariasuni** [comment]
Maybe simply changing
> `cargo new` generate**s** a "Hello World!" project for us

to

> `cargo new` generate**d** a "Hello World!" project for us

to make it clear it is referring to the previous step.

**Comment by AliSajid** [comment]
Bumping this up for review/closure
