### ISSUE TITLE
Paragraph positioning looks weird in "Where to learn" section

### ISSUE THREAD

**Issue by camelid** [rust-lang/www.rust-lang.org#1286]
### Page(s) Affected
/community in the "Where to learn" section

### What needs to be fixed?
The paragraph positioning looks weird for the right column:

![image](https://user-images.githubusercontent.com/37223377/94630051-609afb00-0279-11eb-84bd-75d6ccc9a84d.png)

It seems to be vertically centered.

### Suggested Improvement

I think it would look better aligned to the same vertical position as the left column's topmost paragraph.

**Comment by dzhibas** [comment]
Fixed in this PR https://github.com/rust-lang/www.rust-lang.org/pull/1297

other fixes made in same PR:


-    Moving paragraph headers to translations
-    closing not-closed div
-    fixing typo in closing
-   aligning where to learn section

screenshots of new view is in PR comments

**Comment by dzhibas** [comment]
PR with fix merged, this should be fixed on prod with next build

**Comment by camelid** [comment]
Thanks for fixing this! This can be closed because the PR was merged.
