### ISSUE TITLE
Some HTML tags not rendered in Spanish /sponsors

### ISSUE THREAD

**Issue by Zheoni** [rust-lang/www.rust-lang.org#1292]
### Page(s) Affected

https://www.rust-lang.org/es/sponsors

### What needs to be fixed?

In the Spanish (es) website,  in the sponsors page, there are html tags not rendered in several paragraphs. These errors are not found in the English (en-US) website.
The problems are in the GitHub, Integer 32, and ARM paragraphs. \<em\> and \<code\> tags.

**Comment by dzhibas** [comment]
There is 2 solutions to this one, and for both i will open PR. please choose one and decline another

1. disable sponsors description template variable escaping
2. remove html tags from spanish sponsors translation file

**Comment by dzhibas** [comment]
PRs opened for both solutions. Pick one & close another one

https://github.com/rust-lang/www.rust-lang.org/pull/1295
https://github.com/rust-lang/www.rust-lang.org/pull/1294

**Comment by senekor** [comment]
The sponsors page now redirects to the website of the Rust foundation.
