### ISSUE TITLE
old Firefox logo on WASM page

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/www.rust-lang.org#1310]
### What needs to be fixed?
Firefox logo on [this page](https://www.rust-lang.org/what/wasm)

### Page(s) Affected
https://www.rust-lang.org/what/wasm

### Suggested Improvement
Use newer Firefox logo

**Comment by Sahil2004** [comment]
I have done it and sent the PR.

**Comment by Manishearth** [comment]
This is not the new Firefox logo, this is the Firefox _brand_ logo, but the Firefox browser still has (and intends to keep) the fox logo.

**Comment by Maxgy** [comment]
> This is not the new Firefox logo, this is the Firefox _brand_ logo, but the Firefox browser still has (and intends to keep) the fox logo.

Indeed you are correct the logo @Sahil2004 uploaded is the Firefox branding logo, but they also updated the fox logo, did they not?

**Comment by Manishearth** [comment]
I think we already have the updated logo on the site? It's been updated a few times.

**Comment by Maxgy** [comment]
New logo:
![image](https://user-images.githubusercontent.com/19353212/95628508-680d9180-0a3b-11eb-80bf-e40e19686840.png)


Logo on WASM page (and maybe other places):
![image](https://user-images.githubusercontent.com/19353212/95628400-3268a880-0a3b-11eb-97ac-6d2fc162130b.png)

**Comment by Manishearth** [comment]
Ah, okay, PRs making that fix welcome
