### ISSUE TITLE
Governance page still mentions 2019 roadmap

### ISSUE THREAD

**Issue by DevQps** [rust-lang/www.rust-lang.org#1328]
### What needs to be fixed?
Currently when browsing to https://www.rust-lang.org/governance it still shows the 2019 roadmap.
I think this should be fixed to show the 2020 roadmap? 

### Page(s) Affected
https://www.rust-lang.org/governance

### Suggested Improvement
Replace this with the 2020 Roadmap

**Comment by JohnTitor** [comment]
So, the 2021 roadmap (https://github.com/rust-lang/rfcs/pull/3037) has been merged and we should link to it now, I think.

@Mark-Simulacrum Any plans about a blog post? If not, we could link to the RFC PR directly.

**Comment by aidanhs** [comment]
At this point we should just link to the 2021 roadmap - we can always update it later if it makes sense.
