### ISSUE TITLE
More direct link to translated Rust books (french version in my case)

### ISSUE THREAD

**Issue by luidnel-maignan** [rust-lang/www.rust-lang.org#1365]
When navigating through the french version of the website, I'm currently redirected to the original version of the Rust book, so I originally thought there was no translation. But I finally discovered a completed translation of the book here: https://jimskapt.github.io/rust-book-fr/ that only need to be proofread for some chapters. I think that a more direct access to think version will help a lot to bring some attention to this version and the very little work needed to finish it and maintain it efficiently.

Is it possible to add a link to the french version of the book next to every link to the original book ?

(this issue is a follow up of https://github.com/rust-lang/book/issues/808#issuecomment-737245663)

**Comment by Manishearth** [comment]
We're careful to not link to these since they're official, but having a link next to it that says "unofficial translation in french" would be okay.

**Comment by luidnel-maignan** [comment]
It would be great! Thanks! Is there a way I can contribute? It seems to be a matter of adding a translation entry for the book link, and if this entry is provided, adding a line to the rust book button of the learn page for example.

**Comment by Manishearth** [comment]
I think you'd want to add an empty `translated-book` key, and when it's nonempty the handlebars template adds an extra link or button somewhere.

**Comment by luidnel-maignan** [comment]
I cloned the master branch, cargo build it, installed cargo-watch and launched cargo watch -x run, but obtained a panic because the content of ./locales/en-US/privacy.ftl did not parse. I'm on Win10, and also new to all of this. Should I open another issue or am I missing something ? Should I discuss this on Discord or Zulip or somewhere else to have more direct help ?

**Comment by luidnel-maignan** [comment]
Ok, after posting the previous message, I tried to convert the file from CRLF to LF and the panic disappeared. I still don't know what to do with this info though.

**Comment by luidnel-maignan** [comment]
Now that the pull request is accepted, I can come back here on two things:
1) what is the process the website in production to be updated to the master branch ?
2) what should I do about the CRLF vs LF problem in the file ./locales/en-US/privacy.ftl which actually cause a panic ?

**Comment by Manishearth** [comment]
> what is the process the website in production to be updated to the master branch ?

You basically need to open a PR updating the `deploy` branch to `master`. Feel free to do it yourself, otherwise I'll do it. I'll be waiting a few days to ensure that staging (https://www-staging.rust-lang.org/) isn't broken

> what should I do about the CRLF vs LF problem in the file ./locales/en-US/privacy.ftl which actually cause a panic ?

Is it causing a panic? You should make sure your git conversion settings are correct

**Comment by luidnel-maignan** [comment]
I consider the CRLF vs LF problem to be a separate issue so I close this one.
Thanks again for all.
