### ISSUE TITLE
rustup installer breaks a lot of stuff in ubuntu 20.04

### ISSUE THREAD

**Issue by DouglasWatts** [rust-lang/www.rust-lang.org#1423]
I noticed rust-lang website recommends using the curl command at the top of the page to install Rust after realizing that VSCode could not use the Rust language server or access rustup. So I uninstalled and purged rust* which I had installed from Ubuntu repositories and then installed Rust using the script acquired from the curl command recommended on your website. As soon as I logged out and back in, ALL of my custom settings, keyboard shortcuts were completely gone and gnome-shell-extensions turned off ...literally every single setting I have ever changed on my system and I have a very customized Ubuntu environment. I reset them all within about 30 minutes, not too big a deal but unusual and quite annoying. When I rebooted, same thing ...every time I rebooted all settings and everything I customize was gone and I use a lot of custom keyboard shortcuts because I switched to Ubuntu from a couple years of Arch Linux with i3 desktop and found it easier to change all the keyboard shortcuts to be like i3. Also, my custom mapping of caps-lock as ctrl and both shift keys together enable caps-lock was gone and I had to reset that. While resetting all of the settings a second time, which only took about 10 minutes since I remembered where everything was due to just having done so, I noticed that as I set keyboard shortcuts some would be removed immediately and others duplicated.

Luckily I just started using rsnapshot to keep backups on a separate drive and I keep a separate /home drive, so I restored /home/me from the snapshot that was just taken this morning before installing with rustup and thus far that seems to have resolved the issue though I only did this about 15 minutes ago. This has been a major inconvenience this morning when I have a ton of work to do ...I am in my last semester for Computer Science with math minor and we are using rust in my operating systems course. I had been learning rust for a while over semester break using the package from Ubuntu repository and have now reinstalled that. Rust is awesome by the way, I am working through "The Book" now!

**Comment by skade** [comment]
Hi @DouglasWatts. This issue should be reported tor rust-lang/rustup.

Can you identify files that are being overwritten?

**Comment by DouglasWatts** [comment]
No, I already restored from my snapshot. Sorry about that, I was about to try to track down any changes and realized I do not have time as I have a lot of school work so I just restored this mornings snapshot.

**Comment by DouglasWatts** [comment]
Thanks for your quick response : )

**Comment by DouglasWatts** [comment]
It was literally like having a fresh install of Ubuntu though.

**Comment by DouglasWatts** [comment]
Thanks for reporting it in the appropriate place, sorry about that. I reported it here because the website: https://www.rust-lang.org/ links issues here at the bottom of the page when your click "File an issue".

**Comment by DouglasWatts** [comment]
I posted the relevant parts of my initial report as a comment on your report at rust-lang/rustup, I also mentioned that their "File an issue" links here. Thanks, I see that my bug report should have been more concise and not included unneeded information. I was just trying to make sure I mentioned the entire situation. I will keep this in mind when filing bug reports in the future an appreciate being schooled on that : )

**Comment by DouglasWatts** [comment]
Should I close this report since it is moved to the appropriate place now and they have all info they need? I let them know I am willing to try reproducing the issue and provide them with what they need to assist, since it is very easy for me to restore with rsync in less than a minute.
