### ISSUE TITLE
Playground Timeout on rust-book example

### ISSUE THREAD

**Issue by shashanksingh28** [rust-lang/www.rust-lang.org#1435]
I was trying [this](https://github.com/rust-lang/book/blob/master/listings/ch16-fearless-concurrency/listing-16-02/src/main.rs) example listed on this [page](https://doc.rust-lang.org/book/ch16-02-message-passing.html) while reading the rust-book and was getting:

```Playground Communication: timeout```

I posted the curl command myself locally (and I do get the response), I think the rust-lang.org website perhaps has a timeout setting for calling examples that perhaps needs to be bumped a bit? Happy to put a PR in if I could get some guidance.

Here is my curl command timings locally for reference:
```bash
$time curl 'https://play.rust-lang.org/evaluate.json' ...
0.02s user 0.01s system 0% cpu 7.614 total
```

**Comment by Manishearth** [comment]
Hi, please file an issue on the rust-book repo, this is the repo for the main website
