### ISSUE TITLE
Add the rustwasm connection to the official website (https://github.com/rustwasm).

### ISSUE THREAD

**Issue by jiangzhuochi** [rust-lang/www.rust-lang.org#1449]
### What needs to be fixed?

Add the rustwasm connection to the official website (https://github.com/rustwasm/team).
### Page(s) Affected

https://www.rust-lang.org/governance/wgs/wasm

The yellow box on the right.

![46T0DJ_XSFFXOUSFZ9W7EFS](https://user-images.githubusercontent.com/50538375/108348121-55db0580-721c-11eb-9981-87d02d0500a4.png)

**Comment by Manishearth** [comment]
Currently the wasm working group isn't in a great state as a WG and we're figuring out broader governance questions around WGs; so I'm going to close this for now.
