### ISSUE TITLE
社区首页简体中文页面翻译错误

### ISSUE THREAD

**Issue by w5e** [rust-lang/www.rust-lang.org#1455]
### What needs to be fixed?

社区首页简体中文页面中出现繁体中文
### Page(s) Affected

https://www.rust-lang.org/zh-CN/community
### Suggested Improvement

翻译过程变成从英语到简体中文到繁体中文

**Comment by Manishearth** [comment]
那个文字是繁体的？对不起，我会说一点中文可是不够 .

cc @upsuper 

(for non-Chinese speakers: there's some traditional chinese on the simplified chinese page. We use fallbacks so this is likely just a matter of a missing key, but i'm not sure which one since I can't read _enough_ chinese)

**Comment by w5e** [comment]
覽，聯絡
应该改为
览，联络

**Comment by w5e** [comment]
> 那个文字是繁体的？对不起，我会说一点中文可是不够 .
> 
> cc @upsuper
> 
> (for non-Chinese speakers: there's some traditional chinese on the simplified chinese page. We use fallbacks so this is likely just a matter of a missing key, but i'm not sure which one since I can't read _enough_ chinese)

覽，聯絡
应该改为
览，联络

**Comment by Manishearth** [comment]
谢谢你！

**Comment by Manishearth** [comment]
https://github.com/rust-lang/www.rust-lang.org/commit/36cd66dd256c0b165400d76f6f6601c2d8e4362d

我做了 

在十分钟看 http://www-staging.rust-lang.org/zh-CN/community

**Comment by upsuper** [comment]
We should probably not do fallback I guess.

**Comment by Manishearth** [comment]
I mean, there will be fallback either way, just to English instead.
