### ISSUE TITLE
rustup cant update itself

### ISSUE THREAD

**Issue by Arian94** [rust-lang/www.rust-lang.org#1459]
entered this command:
``` rustup -V```
gave me this:
``` rustup 1.50```
for some reason, i had to downgrade to version 1.31. so ran this:
``` rustup install 1.31```
then re-entered ``` rustup -V``` but instead of showing me 1,31, showed this:
``` rustup 1.23.1 ```
Again ran  ``` rustup install 1.50 ``` command to go back to my current version
it says it has installed 1.50 but when I enter ``` rustup -V ``` it gives me this:
``` rustup 1.23.1 ```
did everything, nothing worked. so fuck it. what's wrong with it???????????????????????????

**Comment by Manishearth** [comment]
`rustup self update`

**Comment by Arian94** [comment]
> `rustup self update`

I told you i did everything and none had worked out, including your solution as well!!

**Comment by Manishearth** [comment]
You are conflating the `rustup` version with the version for your `rust` compiler. `rustup install` installs a particular rust toolchain, whereas `rustup` has its own version number that shows up in `rustup -V`


This is also not the repo for rustup issues, see https://github.com/rust-lang/rustup
