### ISSUE TITLE
Community | Expose localized communities

### ISSUE THREAD

**Issue by EstebanBorai** [rust-lang/www.rust-lang.org#1470]
### Summary

In the rust-lang.org website, on the Community section would be great
to have a listing of the different Rust communities around the world.

I think some index with search capabilities would be great to help people
find a community which is nearby.

### Motivation

As Rust becomes more popular and is adopted in different places, I've found
that localized communities emerge, some of these communities are:

- [rust-lang-ar](https://github.com/rust-lang-ar)
- [rust-lang-br](https://github.com/rust-lang-br)
- [rust-lang-cn](https://github.com/rust-lang-cn)
- [rust-lang-de](https://github.com/rust-lang-de)
- [rust-lang-hu](http://rust-lang.hu/)
- [rust-lang-iran](https://github.com/rust-lang-iran)
- [rust-lang-ja](https://github.com/rust-lang-ja)
- [rust-lang-ko](https://github.com/rust-lang-ko)
- [rust-lang-pl](https://github.com/rust-lang-pl)
- [rust-lang-ru](https://github.com/rust-lang-ru)
- [rust-lang-th](https://github.com/rust-lang-th) (Looks like this is new!)
- [rust-lang-wales](https://github.com/rust-lang-wales)

I'm sure theres going to be many more in the future. I believe this
communities help people run meetings, workshops share knowledge
and help reunite Rustaceans who live close to each other.

(If im missing some community, please comment it here and I will add it as well!)

### Drawbacks

I don't find a reason why not at the moment, but perhaps theres one!

### Rationale and alternatives

The impact of doing this would be helping people interested
on sharing knowledge about Rust and meet other interested in the same field
to find a community to share experiences and help each other in the learning
paths. They could attend events, run video call meetings, help each other via
pair programming sessions and other activities which apply to educational goals.

### Maintenance

I could help provide some design if the idea is accurate enough for the rest of the team and
I would love to implement the final design as well!

### Unresolved Questions

I think that an important factor to consider is how are these communities going to be feed?

Im thinking about something similar to https://www.rustaceans.org where a JSON
file is used to maintain certain fields about each entry and interested people creates a PR
to update such file.

Some fields that I consider relevant are:

- Website
- Comunication Channels: Discord, Gitter, Slack, Telegram
- GitHub Organization
- Contact (Email perhaps)

**Comment by Manishearth** [comment]
> I don't find a reason why not at the moment, but perhaps theres one!

We are _very very careful_ about linking to unofficial resources because we cannot moderate them or guarantee any quality level. We don't even link to unofficial communities _in English_.

So this might be doable, but is a larger shift than it seems at first.

cc @skade

**Comment by EstebanBorai** [comment]
@Manishearth makes sense to me!

I don't know whats better, if providing some code of conduct, and contact details to a moderator or leaving a disclaimer saying something like:

```
The following communities are unofficial Rust communities. The Rust Programming Language organization is not responsible for any activity performed on any of these organizations.

This site acts as an index for communities opened by anyone who wants to publish their localized Rust community.
```

Perhaps something like that works? To avoid any issues with the official community?

**Comment by Manishearth** [comment]
Even with a disclaimer it would be a pretty large policy shift to do this

**Comment by EstebanBorai** [comment]
@Manishearth understood! So perhaps its better to close this then?

**Comment by Manishearth** [comment]
I want to wait for @skade's opinion but yeah

**Comment by skade** [comment]
@EstebanBorai: @Manishearth  is right there, we made the deliberate decision to not do this on the new page. That decision has history: the old page used to have a subpage with meetups and communities, but it was extremely hard to keep it up to date and even at a mediocre level of quality. It also brings questions like which bar a community needs to jump to be listed.

This applies to a lot of sections on the page, for example we only link to documentation the Rust project itself maintains and provides.
