### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by pocketdr** [rust-lang/www.rust-lang.org#1476]
### What needs to be fixed?

Incorrect link in zh-CN main page with TRPL unofficial translate.
中文主页的上的非官方翻译文档的地址链接是正体中文版本，翻译辛辛苦苦的劳动不要无法被人看到啊！XD
### Page(s) Affected

https://www.rust-lang.org/zh-CN/learn
### Suggested Improvement

Change 
`<a class="button-additional" href="https://rust-lang.tw/book-tw/">阅读非官方翻译</a>`
to
`<a class="button-additional" href="https://kaisery.github.io/trpl-zh-cn/">阅读非官方翻译</a>`

**Comment by Manishearth** [comment]
Updated in https://github.com/rust-lang/www.rust-lang.org/commit/857004470715de9c139c0c52b3b5fe4b9413f9b8 , should show up on https://www-staging.rust-lang.org/ soon

**Comment by pocketdr** [comment]
thx
