### ISSUE TITLE
Lifetime syntax should show more examples 

### ISSUE THREAD

**Issue by Randall-Coding** [rust-lang/www.rust-lang.org#1489]
### Summary
I think there should be more examples of lifetime declarations on various objects.   More than just the typical &str example.

### Motivation
I spent a fair bit of time just trying to find out the correct syntax to specify a lifetime on an object containing a generic like Vec<T>.

I was starting to think maybe I am not even able to add lifetimes to anything but references, because those were the only examples I saw.  It was always `&'a`.  I did finally figure it out, but I never saw the exact example, I just kind of guessed around to find it.

### Drawbacks
No reason to not do this

### Maintenance
None, very simple request.

Thanks for all your hard work guys.

**Comment by Manishearth** [comment]
Which example? If you're talking about the book, please file an issue on github.com/rust-lang/book

**Comment by Randall-Coding** [comment]
Oh sorry, I thought this was the same place.  Thanks.

**Comment by Randall-Coding** [comment]
Yeah I guess it was the book https://doc.rust-lang.org/book/ch10-03-lifetime-syntax.html
