### ISSUE TITLE
Ferris' pronouns are outdated.

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/www.rust-lang.org#1505]
See here: https://twitter.com/thattrans_girl/status/1363682685542105091

Basically, rustacean.net was updated to say "My pronouns are any--she/he/they/it are all great!", so that means the text saying "We refer to Ferris with the pronouns “they,” “them,” etc., rather than with gendered pronouns." is incorrect.

I would submit a PR but the text is no longer in the repo, hence, an issue :) Thanks!

**Comment by theasin** [comment]
wow, this is dumb
