### ISSUE TITLE
Small typo in spanish version

### ISSUE THREAD

**Issue by fcoterroba** [rust-lang/www.rust-lang.org#1518]
### What needs to be fixed?
Is a small typo in the Spanish version. In the `h3` with id: **uses-that-require-explicit-approval**, the last `li` element, shows _"Los términos "RustCamp", "RustCon" o "RustConf" no pueden usarse **in** autorización explícita."_

### Page(s) Affected
https://www.rust-lang.org/es/policies/media-guide

### Suggested Improvement
That's "in" shoulds be "sin"

**Comment by JohnTitor** [comment]
We maintain the translations on Pontoon, could you correct it there (https://pontoon.rust-lang.org/es/rust-www/media-guide.ftl/?string=397)?

**Comment by fcoterroba** [comment]
Done!
