### ISSUE TITLE
Typo in Install Page.

### ISSUE THREAD

**Issue by Sammie156** [rust-lang/www.rust-lang.org#1520]
### What needs to be fixed?
The Windows Subsystem section of installing Rust has a typo. It is written, "If you're a Windows Subsystem for Linux", which is scary and not correct. 

### Page(s) Affected
Just the Install Page has this error..

### Suggested Improvement
I guess it will be, "If you're on a Windows Subsystem for Linux"... I know its not serious, but its still a typo..

**Comment by Sammie156** [comment]
This is my first time opening an issue in any repository, so.... if it seems useless, or not appropriate, sorry.

**Comment by U-C-S** [comment]
Seems nothing is wrong in the sentence that's currently in the website 

> If you’re a Windows Subsystem for Linux user run the following in your terminal, then follow the on-screen instructions to install Rust.

You have missed the word "user" at the end

> It is written,  "If you're a Windows Subsystem for Linux",

**Comment by Sammie156** [comment]
Ah Yes.. I haven't been on the website for a while, and I may have missed that word. Thank you very much. 😅
