### ISSUE TITLE
Privacy Policy link from Policies page

### ISSUE THREAD

**Issue by jerusdp** [rust-lang/www.rust-lang.org#1569]
### Page(s) Affected

Policies page

### What needs to be fixed?

Privacy policy link from the list of Rust Policies.
(points to https://www.rust-lang.org/policies which returns 404).

### Suggested Improvement

Replace link with: https://foundation.rust-lang.org/policies/privacy-policy/

**Comment by EstebanBorai** [comment]
Hi! I'm checking on the provided link (https://www.rust-lang.org/policies) and I can see the page load without 404.
Perhaps I'm missing something?

**Comment by jerusdp** [comment]
From the main page follow the "All Policies" link to the Policies page. 

The link to "Privacy Notice" is broken.

**Comment by EstebanBorai** [comment]
I can see now, fetched the repo and it's already fixed but for some reason is not yet deployed

**Comment by Manishearth** [comment]
https://www-staging.rust-lang.org/policies

**Comment by Manishearth** [comment]
I've opened a PR to deploy, will be deployed once that gets merged

**Comment by jerusdp** [comment]
> 
> 
> https://www-staging.rust-lang.org/policies

Looks good.
