### ISSUE TITLE
Don't use `curl ... | sh`

### ISSUE THREAD

**Issue by kotovalexarian** [rust-lang/www.rust-lang.org#1572]
The website [recommends](https://www.rust-lang.org/tools/install) to install RustUp with `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`. This is inappropriate way to run executables. Executable from any source must be verified with checksum or signature. The source of checksums and public keys must be resistant against malicious replacement, so they must be stored locally and updated with cryptographic validation.

I know that any method is vulnerable during the first use. I hope that RustUp is ONLY vulnerable during the first use, while future updates are verified cryptographically. However, even this first run can be more secure.

Now attacks only require to change the script at `sh.rustup.rs`. Why not verify the script with checksum that is received from different sources? For example, installation documentation on `rust-lang.org`. Yes, this creates difficulties when making new releases of RustUp, but security is more important. Also this method requires that no one has deploy access to both `rust-lang.org` and `sh.rustup.rs`.

**Comment by pietroalbini** [comment]
Rust's implementation of `curl | bash` avoids some of the common pitfalls of the approach, but of course relies on trust on first use. There are some issues preventing us from doing what you suggest:

* Pinning hashes would break CI systems installing Rustup as part of the build, as any new release would change the hashes. There isn't really a way to update the hash pinned in our users' CI systems. It would also break tutorials, books or other manuals referencing how to install Rust.
* Changing any file in `sh.rustup.rs` requires the highest level of access possible in Rust's infrastructure. If someone gains that level of access they might as well change anything else on any piece of Rust infrastructure. Only a few people have the access required to make changes there.

If you have any more security concerns I recommend you email security@rust-lang.org.

**Comment by kotovalexarian** [comment]
Not only this highest level of privilegies is required to change something in `sh.rustup.rs`. It may be just vulnerability in web server software or in cryptographic libraries.

Also I don't understand how my proposal breaks anything. I only suggest optional hash verification.
