### ISSUE TITLE
document the two-dots slice notation

### ISSUE THREAD

**Issue by beroal** [rust-lang/www.rust-lang.org#1589]
### Summary

By the two-dots slice notation, I mean, for example, `a[1 .. 3]` where `a` has type `[u8; 2]`. The behavior of this notation when `start` and `end` in `array[start .. end]` are out of the bounds of `array` is very important for program correctness. All official sources I could find are

- [“Primitive Type slice”](https://doc.rust-lang.org/std/primitive.slice.html) in the `std` crate documentation containing zero pertinent information
- and incomplete [“The Slice Type”](https://doc.rust-lang.org/book/ch04-03-slices.html) in *The Rust Programming Language* by Steve Klabnik and Carol Nichols.

### Motivation

It would be good to have a first hand documentation and not to glean it from anonymous tutorials on the web.

### P. S.

Sorry if I posted to the wrong bug tracker. I couldn't find contacts on [https://doc.rust-lang.org](https://doc.rust-lang.org).

**Comment by Manishearth** [comment]
That operator maps to the Index trait, which is documented. It could perhaps still be improved, but this is the wrong bug tracker, github.com/rust-lang/rust for stdlib documentation and github.com/rust-lang/book for the book
