### ISSUE TITLE
Discord logo is outdated

### ISSUE THREAD

**Issue by fredster33** [rust-lang/www.rust-lang.org#1592]
### What needs to be fixed?
The Discord logo at the bottom of the page is outdated. It should be replaced with the new logo.

### Page(s) Affected
It looks like all pages are affected, as the logo is in the footer.

### Suggested Improvement
I see that this can be fixed by updating the template, however, I wasn't sure how to. The code seems to reference a {fluent discord} template, but I'm not sure where this is stored.

**Comment by AliSajid** [comment]
This needs a review and merge!
