### ISSUE TITLE
Typo in the french version of the "Commencer" (Getting started) page

### ISSUE THREAD

**Issue by Hliceath** [rust-lang/www.rust-lang.org#1595]
### What needs to be fixed?
In the french version, within the paragraph "En savoir plus !" there is a typo within the following sentence: 

> Quand vous serez **prêt·e**, faites un saut sur notre page « Apprendre », où vous pourrez trouver beaucoup de livres qui vous aideront a continuer votre aventure en Rust.

### Page(s) Affected
The page affected is: [https://www.rust-lang.org/fr/learn/get-started](https://www.rust-lang.org/fr/learn/get-started)

### Suggested Improvement
It should be fixed into: 

> "Quand vous serez **prêt,** faites un saut sur notre page « Apprendre », où vous pourrez trouver beaucoup de livres qui vous aideront a continuer votre aventure en Rust."

**Comment by ldesgoui** [comment]
This is not a typo, this is inclusive writing ("écriture inclusive").

**Comment by Hliceath** [comment]
> 
> 
> This is not a typo, this is inclusive writing ("écriture inclusive").

I'm a frenchman and this is not what we learn at school. This is politics not an actual rule of grammar.
