### ISSUE TITLE
Rust for Windows recommends installing a tool (Visual Studio Build Tools) that needs a licence

### ISSUE THREAD

**Issue by jonathanpallant** [rust-lang/www.rust-lang.org#1597]
### What needs to be fixed?

On https://rust-lang.github.io/rustup/installation/windows.html it says

> When targeting the MSVC ABI, Rust additionally requires an installation of Visual Studio 2013 (or later) or the Visual C++ Build Tools 2019 so rustc can use its linker. For Visual Studio, make sure to check the "C++ tools" and "Windows 10 SDK" option. No additional software installation is necessary for basic use of the GNU build.

It appears that a Visual Studio (Community, Professional or Enterprise) licence is now required to use the Visual Studio Build Tools, and we should either advise people of the fact or recommend an alternative. See this text on https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2019

> These Build Tools allow you to build Visual Studio projects from a command-line interface. Supported projects include: ASP.NET, Azure, C++ desktop, ClickOnce, containers, .NET Core, .NET Desktop, Node.js, Office and SharePoint, Python, TypeScript, Unit Tests, UWP, WCF, and Xamarin. *Use of this tool requires a valid Visual Studio license.*

(my emphasis)

See this issue on VS Code where their C++ plugin was doing the same: https://github.com/microsoft/vscode/issues/95745

### Page(s) Affected

https://rust-lang.github.io/rustup/installation/windows.html and anywhere else it talks about the "Visual Studio Build Tools" or "Visual C++ Build Tools".

### Suggested Improvement

1. Tell people they need a Visual Studio licence to use the Visual Studio Build Tools, and/or
2. Suggest people install an alternative Microsoft Visual C++ compatible C++ compiler

**Comment by jonathanpallant** [comment]
Will do, but FYI it also applies to https://www.rust-lang.org/tools/install.

**Comment by Manishearth** [comment]
Ah, reopened for that bit
