### ISSUE TITLE
When is the website deployed?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/www.rust-lang.org#1610]
### What needs to be fixed?
The pages that reference the list of editors still say "Sublime Text 3".  However, #1580 was merged back in August which should have fixed those pages.  

From what I can see https://www-staging.rust-lang.org/ has the correct content. So I'm guessing a manual deployment is necessary?

### Page(s) Affected
https://www.rust-lang.org/tools
https://www.rust-lang.org/learn/get-started

### Suggested Improvement
I'm not familiar with the deployment process.

**Comment by Manishearth** [comment]
Someone has to make a PR from master to the deploy

I'm on my phone but happy to merge if someone else does it.

**Comment by Manishearth** [comment]
#1611

**Comment by ehuss** [comment]
Thanks @Manishearth!!
