### ISSUE TITLE
I hit a compile error with old Rust code

### ISSUE THREAD

**Issue by dave-32** [rust-lang/www.rust-lang.org#1614]
I circled back to a project after a few years.  Editions is 'saving me' from updating to the latest, when I compile to see where I'm at.  I intend to update to the latest edition, and fix any compatibility issues in my code to reflect the new design.  However, before I make the problem disappear, I thought I would put it here, in case it should get fixed.

I am compiling this on a Mac, running 11.6.1

It is failing to compile Regex v0.2.6.  The compilation attempt follows:

cargo build
   Compiling libc v0.2.29
   Compiling version_check v0.1.3
   Compiling num-traits v0.1.40
   Compiling rustc-serialize v0.3.24
   Compiling byteorder v1.1.0
   Compiling traitobject v0.1.0
   Compiling matches v0.1.6
   Compiling log v0.3.8
   Compiling siphasher v0.2.2
   Compiling unicode-normalization v0.1.5
   Compiling typeable v0.1.2
   Compiling httparse v1.2.3
   Compiling percent-encoding v1.0.0
   Compiling language-tags v0.2.2
   Compiling modifier v0.1.0
   Compiling dtoa v0.4.2
   Compiling lazy_static v0.2.8
   Compiling itoa v0.3.4
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling void v1.0.2
   Compiling gcc v0.3.54
   Compiling safemem v0.2.0
   Compiling serde v1.0.24
   Compiling lazy_static v1.0.0
   Compiling serde v0.8.23
   Compiling itoa v0.1.1
   Compiling dtoa v0.2.2
   Compiling utf8-ranges v1.0.0
   Compiling regex-syntax v0.4.2
   Compiling linked-hash-map v0.5.0
   Compiling safemem v0.1.1
   Compiling serde v0.9.15
   Compiling hex v0.2.0
   Compiling linked-hash-map v0.3.0
   Compiling semver-parser v0.7.0
   Compiling bitflags v1.0.1
   Compiling bufstream v0.1.3
   Compiling separator v0.3.1
   Compiling data-encoding v1.2.0
   Compiling rand v0.3.17
   Compiling time v0.1.38
   Compiling memchr v2.0.0
   Compiling num_cpus v1.6.2
   Compiling memchr v0.1.11
   Compiling hostname v0.1.3
   Compiling num-integer v0.1.35
   Compiling num-complex v0.1.40
   Compiling conduit-mime-types v0.7.3
   Compiling unicase v1.4.2
   Compiling unicode-bidi v0.3.4
   Compiling unsafe-any v0.4.2
   Compiling mime v0.2.6
   Compiling base64 v0.5.2
   Compiling error v0.1.9
   Compiling synom v0.11.3
   Compiling unreachable v1.0.0
   Compiling base64 v0.6.0
   Compiling rust-crypto v0.2.36
   Compiling serde_json v0.8.6
   Compiling semver v0.8.0
   Compiling serde_json v1.0.8
   Compiling serde_json v0.9.10
   Compiling tempdir v0.3.5
   Compiling aho-corasick v0.6.4
   Compiling twoway v0.1.4
   Compiling cookie v0.10.1
   Compiling buf_redux v0.6.1
   Compiling num-bigint v0.1.40
   Compiling num-iter v0.1.34
   Compiling typemap v0.3.3
   Compiling idna v0.1.4
   Compiling syn v0.11.11
   Compiling thread_local v0.3.5
   Compiling plugin v0.2.6
   Compiling num-rational v0.1.39
   Compiling url v1.5.1
   Compiling regex v0.2.6
error[E0713]: borrow may still be in use when destructor runs
   --> /Users/dave/.cargo/registry/src/github.com-1ecc6299db9ec823/url-1.5.1/src/form_urlencoded.rs:251:40
    |
249 | impl<'a> Target for ::UrlQuery<'a> {
    |      -- lifetime `'a` defined here
250 |     fn as_mut_string(&mut self) -> &mut String { &mut self.url.serialization }
251 |     fn finish(self) -> &'a mut ::Url { self.url }
    |                                        ^^^^^^^^ - here, drop of `self` needs exclusive access to `*self.url`, because the type `UrlQuery<'_>` implements the `Drop` trait
    |                                        |
    |                                        returning this value requires that `*self.url` is borrowed for `'a`

For more information about this error, try `rustc --explain E0713`.
error: could not compile `url` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by AliSajid** [comment]
Rust Team. This is a bug, apparently in the compiler/language itself. This should probably be moved to [rust-lang/rust](https://github.com/rust-lang/rust) if possible. Otherwise this can be closed.

**Comment by senekor** [comment]
This is in the wrong repo and doesn't include reproduction steps.
