### ISSUE TITLE
Incorrect Content in "Rust Programming Language" book

### ISSUE THREAD

**Issue by ERAGON007** [rust-lang/www.rust-lang.org#1616]
### What needs to be fixed?
Hi, so i'm a newbie to Rust language and i really love it.

I'm reading "The Rust Programming Language" book from [this link](https://doc.rust-lang.org/book/)

and the section `Listing 3-5` in this book i think is outdated or something like that.

**Content in book:**
![image](https://user-images.githubusercontent.com/68738639/145718621-3c83d7e3-0fe1-41d5-aaaa-43722429cd3d.png)

**Exactly that code in vscode using `rust-analyzer` extension:**
it literraly says that this code can't be compiled!
![image](https://user-images.githubusercontent.com/68738639/145718556-0509cff7-ee99-4f7f-8ba5-a05d55a6784c.png)

**Compiler error when trying to compile:**
![image](https://user-images.githubusercontent.com/68738639/145718678-2fdf3270-a849-4499-a2ba-1814200fd644.png)

Note that i fixed this issue by doing what compiler told me to do. btw the book wasn't the thing that compiler did.

My `rustc` version is `rustc 1.52.1 (9bc8c42bb 2021-05-09)`
`Edition` section in `Cargo.toml` is "2018" as the book mentions.

the book didn't mentioned where should we report these kind of issues so i decided to report here. sorry if i'm posting in wrong section.

### Page(s) Affected
https://doc.rust-lang.org/book/ch03-05-control-flow.html#looping-through-a-collection-with-for

### Suggested Improvement
Changing content from
```rust
fn main() {
  let a = [10, 20, 30, 40, 50];
  for element in a {
    println!("the value is: {}", element);
  }
}
```

to 

```rust
fn main() {
  let a = [10, 20, 30, 40, 50];
  for element in a.iter() {
    println!("the value is: {}", element);
  }
}
```

**Comment by ERAGON007** [comment]
Maybe this kinda content exists on another pages of book related to this topic too. that'll need to be checked by far i've read the book to this page

**Comment by Manishearth** [comment]
This is an issue with https://github.com/rust-lang/book , and the specific bug you're facing is that [there was a change in array iteration in Rust 2021](https://doc.rust-lang.org/edition-guide/rust-2021/IntoIterator-for-arrays.html). You should be able to make a PR to that repo to fix this.

(cc @carols10cents)

**Comment by ERAGON007** [comment]
Oh, thanks for mentioning
