### ISSUE TITLE
Turkish language typo a word

### ISSUE THREAD

**Issue by efpyc** [rust-lang/www.rust-lang.org#1636]
### What needs to be fixed?

![resim](https://user-images.githubusercontent.com/55599607/151181186-cb221b26-9f8f-4185-9e2a-ba469cecbe1e.png)

The word I marked in this paragraph was misspelled with a translator mistake.

### Page(s) Affected
https://www.rust-lang.org/tr/

### Suggested Improvement

This word must change from "daya" to "daha".

**Comment by AliSajid** [comment]
There's an active pull request. #1653 . Please merge and close.
