### ISSUE TITLE
"Check Website Status" leads to non-existent page

### ISSUE THREAD

**Issue by djavorszky** [rust-lang/www.rust-lang.org#1637]
On the front page, there's a link at the bottom: "Check Website Status", which leads to http://ping.rust-lang.org/.

This server doesn't seem to exist - Firefox says that it cant find the server. Seems like there's no DNS record for it.

Not sure if that site being unreachable is intended :) if so, I suppose the link should be removed from https://rust-lang.org.

**Comment by homeworkprod** [comment]
Discovered this as well.

According to [Down for Everyone or Just Me](https://downforeveryoneorjustme.com/ping.rust-lang.org?proto=http), it's not just us.

**Comment by AliSajid** [comment]
It seems the link has been removed from the website so this can also be closed
