### ISSUE TITLE
I have a question to this Compile Bug 

### ISSUE THREAD

**Issue by JoeCP17** [rust-lang/www.rust-lang.org#1648]
<img width="945" alt="스크린샷 2022-02-28 오전 2 27 33" src="https://user-images.githubusercontent.com/76832303/155892829-f3b64b91-e9c3-4849-b04e-8b8f2577f53a.png">

Is this the intended bug?

When I printed it, I confirmed that the results came out properly as follows.

**Comment by Manishearth** [comment]
(This is not the place to ask for language help)
