### ISSUE TITLE
println!() The last line works without a semicolon.

### ISSUE THREAD

**Issue by barabobBOB** [rust-lang/www.rust-lang.org#1649]
### Page(s) Affected

<img width="1512" alt="스크린샷 2022-02-28 오전 2 30 54" src="https://user-images.githubusercontent.com/83595905/155892938-81c49a3b-9c71-4fb6-934f-dbb587c4bcf1.png">

### What needs to be fixed?
 println!() The last line works without a semicolon. In addition, errors occur when writing codes.
<img width="1512" alt="스크린샷 2022-02-28 오전 2 32 36" src="https://user-images.githubusercontent.com/83595905/155893015-10f9cfea-e0c2-423d-ae6c-12f119036b77.png">

Did you intend to do this? I'm a beginner developer.

**Comment by Manishearth** [comment]
(This is not the place to ask for language help)
