### ISSUE TITLE
Documentation: isize/usize MIN/MAX/BITS misinformation

### ISSUE THREAD

**Issue by Phosra** [rust-lang/www.rust-lang.org#1650]
Pages <https://doc.rust-lang.org/std/primitive.isize.html> and <https://doc.rust-lang.org/std/primitive.usize.html> write the minimum and maximum values, along with the number of bits, in terms of a 64-bit target.

Ideally, these values can be rewritten (especially the textual explanations/non-code sections) to reflect that the values are fixed based on the platform being compiled to.

Furthermore, APIs such as to/from be/le/ne bytes show a constant 8 bytes, whereas an signature such as `pub const fn to_ne_bytes(self) -> [u8; mem::size_of<usize>()]`, may better reveal the actual API.

**Comment by remlse** [comment]
The standard library source code is in a [different repository](https://github.com/rust-lang/rust).
