### ISSUE TITLE
Can we have "Copy to Clipboard" button on the install page?

### ISSUE THREAD

**Issue by okuramasafumi** [rust-lang/www.rust-lang.org#1659]
### Summary

On https://www.rust-lang.org/tools/install I'd like to have "Copy to Clipboard" button on the install code.

### Motivation

While copy and paste is still possible without the button, I think putting "Copy to Clipboard" button makes it even easier to prevent mistakes.

### Drawbacks

We need some amount of JavaScript.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

### Maintenance

Only a few lines of JavaScript should not be hard to maintain, but some browsers might not support it yet.

**Comment by haasal** [comment]
I think it would be a nice and simple addition. I will try to implement it.

**Comment by AliSajid** [comment]
PR #1695 closes this issue.
