### ISSUE TITLE
Add average completion time for each chapter in the book

### ISSUE THREAD

**Issue by asarkar** [rust-lang/www.rust-lang.org#1668]
### Summary
Add average completion time for each chapter in the book.

### Motivation
This will help the reader to pace themselves accordingly. Currently, when I'm starting a chapter, I don't know whether it'll take me 10 minutes or 2 hours to complete. This is a common practice, and used by Medium, for example.

### Drawbacks
Each person learns at their own pace.

### Rationale and alternatives
Already discussed.

### Maintenance
Depends on how it's implemented.

### Unresolved Questions
N/A.

**Comment by Manishearth** [comment]
This should be filed on https://github.com/rust-lang/book

**Comment by asarkar** [comment]
Filed https://github.com/rust-lang/book/issues/3167
