### ISSUE TITLE
Missing information at "Adding dependencies" in "learn/get-started" page

### ISSUE THREAD

**Issue by tritriper** [rust-lang/www.rust-lang.org#1671]
### What needs to be fixed?
Making the tutorial of get-started page, I had a error at build after add of dependencies "ferris-says" (https://www.rust-lang.org/learn/get-started#:~:text=rust%60%0AHello%2C%20world!-,Adding%20dependencies,-Let%E2%80%99s%20add%20a)
I found on the exemple of the doc of the crate (https://docs.rs/crate/ferris-says/0.2.1) it is needed to write this at begin of the code "extern crate ferris_says;" to resolve error.

### Page(s) Affected
https://www.rust-lang.org/learn/get-started

### Suggested Improvement
Add the instruction about the line "extern crate ferris_says;" or/and give the link/reference to the doc page of the crate (that already have a exemple)

Thank you for everything created in rust environnement, Like so much good documentation you have !

**Comment by Manishearth** [comment]
`extern crate ferris_says` is no longer necessary since the Rust 2018/2021 edition, which is defaulted with `cargo new`.
