### ISSUE TITLE
Page title says "Rust Programming Language" but it should say "The Rust Programming Language"

### ISSUE THREAD

**Issue by Bqleine** [rust-lang/www.rust-lang.org#1682]
### What needs to be fixed?
The page title is incorrect

### Page(s) Affected
All pages

### Suggested Improvement
The title should say "The Rust Programming Language" instead

**Comment by senekor** [comment]
I am afflicted by the wide spread disease of "having too many tabs open." Their titles all starting with "The" would only increase suffering :wink:

**Comment by Bqleine** [comment]
Understandable
