### ISSUE TITLE
i686 rustc immediately kernel panics w/ "rustc --version" on x86_64 host w/ 32-bit OS

### ISSUE THREAD

**Issue by dbodden-pesa** [rust-lang/www.rust-lang.org#1684]
I've been attempting to do builds against an older glibc used by Centos 7.

Running the 32-bit variant of CentOS 7, I download the Rust 1.61 offline installer, install.

Run rustc --version, I get a kernel panic. dmesg output attached along with the installer log and uname/etc/issue information.

I found this behavior started in 1.51, although even with 1.50 I can run rustc --version but not compile my code.

I tried running on a few different VM combinations including KVM and VirtualBox, but also loaded Centos7 to a physical system and saw similar behavior

(cpuinfo, cat /etc/centos-release, uname -a)
model name	: AMD EPYC-Rome Processor
model name	: AMD EPYC-Rome Processor
CentOS Linux release 7.9.2009 (AltArch)
Linux localhost.localdomain 3.10.0-1160.2.2.el7.centos.plus.i686 #1 SMP Mon Oct 26 11:56:29 UTC 2020 i686 i686 i386 GNU/Linux

(install.sh, 1.61)
install: uninstalling component 'rustc'
install: uninstalling component 'rust-std-i686-unknown-linux-gnu'
install: uninstalling component 'rust-docs'
install: uninstalling component 'cargo'
install: uninstalling component 'rustfmt-preview'
install: uninstalling component 'rls-preview'
install: uninstalling component 'llvm-tools-preview'
install: uninstalling component 'clippy-preview'
install: uninstalling component 'rust-analysis-i686-unknown-linux-gnu'
install: creating uninstall script at /usr/local/lib/rustlib/uninstall.sh
install: installing component 'rustc'
install: installing component 'rust-std-i686-unknown-linux-gnu'
install: installing component 'rust-docs'
install: backing up existing file at /usr/local/share/doc/rust/html
install: installing component 'rust-demangler-preview'
install: installing component 'cargo'
install: installing component 'rustfmt-preview'
install: installing component 'rls-preview'
install: installing component 'llvm-tools-preview'
install: installing component 'clippy-preview'
install: installing component 'rust-analysis-i686-unknown-linux-gnu'

    rust installed.
(file `which rustc)
/usr/local/bin/rustc: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, not stripped

(dmesg after the panic caused by "rustc --version")
[    0.769351] ACPI: PCI Interrupt Link [GSIF] enabled at IRQ 21
[    0.769402] ------------[ cut here ]------------
[    0.769406] WARNING: CPU: 0 PID: 254 at arch/x86/mm/pat.c:354 reserve_memtype+0x89/0x510
[    0.769407] reserve_memtype failed: [mem 0x00000000-0xffffffffffffffff], req write-combining
[    0.769416] Modules linked in: virtio_blk virtio_net net_failover failover qxl(+) virtio_console ahci libahci drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops libata crc32c_intel serio_raw ttm drm virtio_pci virtio_ring virtio drm_panel_orientation_quirks dm_mirror dm_region_hash dm_log dm_mod
[    0.769418] CPU: 0 PID: 254 Comm: systemd-udevd Tainted: G        W      ------------   3.10.0-1160.2.2.el7.centos.plus.i686 #1
[    0.769418] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[    0.769418] Call Trace:
[    0.769426]  [<c985398a>] dump_stack+0x16/0x18
[    0.769427]  [<c925d5ea>] __warn+0xea/0x110
[    0.769428]  [<c92558a9>] ? reserve_memtype+0x89/0x510
[    0.769429]  [<c925d656>] warn_slowpath_fmt+0x46/0x60
[    0.769430]  [<c92558a9>] reserve_memtype+0x89/0x510
[    0.769432]  [<c93acf86>] ? __kmalloc_track_caller+0x46/0x1e0
[    0.769433]  [<c9256187>] io_reserve_memtype+0x67/0x140
[    0.769439]  [<c925840b>] iomap_create_wc+0x2b/0x70
[    0.769443]  [<f80c9827>] qxl_device_init+0x467/0x8f0 [qxl]
[    0.769450]  [<c951baa2>] ? pci_read_config_word+0x42/0x50
[    0.769452]  [<c9522a94>] ? do_pci_enable_device+0xc4/0xf0
[    0.769455]  [<f80c928e>] qxl_pci_probe+0x6e/0xf0 [qxl]
[    0.769457]  [<c95eebd1>] ? __pm_runtime_resume+0x51/0x80
[    0.769459]  [<f80c9220>] ? qxl_pci_remove+0x50/0x50 [qxl]
[    0.769460]  [<c9526f4c>] pci_device_probe+0x7c/0xe0
[    0.769462]  [<c943a8c5>] ? sysfs_create_link+0x25/0x40
[    0.769464]  [<c95e4ed3>] driver_probe_device+0xb3/0x3d0
[    0.769465]  [<c95e5230>] ? __device_attach+0x40/0x40
[    0.769465]  [<c95e52a9>] __driver_attach+0x79/0x80
[    0.769466]  [<c95e5230>] ? __device_attach+0x40/0x40
[    0.769467]  [<c95e300a>] bus_for_each_dev+0x5a/0xa0
[    0.769468]  [<c95e490e>] driver_attach+0x1e/0x20
[    0.769469]  [<c95e5230>] ? __device_attach+0x40/0x40
[    0.769470]  [<c95e4457>] bus_add_driver+0x1d7/0x2b0
[    0.769471]  [<c95e5889>] driver_register+0x59/0xe0
[    0.769472]  [<c95268e4>] __pci_register_driver+0x84/0xa0
[    0.769473]  [<f80d8000>] ? 0xf80d7fff
[    0.769475]  [<f80d803c>] qxl_init+0x3c/0x1000 [qxl]
[    0.769479]  [<c920046d>] do_one_initcall+0xad/0x220
[    0.769480]  [<f80d8000>] ? 0xf80d7fff
[    0.769481]  [<c92d149e>] load_module+0x153e/0x1a70
[    0.769484]  [<c92d1b6d>] SyS_finit_module+0x8d/0xd0
[    0.769486]  [<c98636c8>] sysenter_do_call+0x1b/0x31
[    0.769487] ---[ end trace f68728a0d3053b54 ]---
[    0.769625] Unable to create surface_mapping
[    0.769625] qxl: probe of 0000:00:01.0 failed with error -12

**Comment by Manishearth** [comment]
This is not the issue tracker for the Rust compiler, try rust-lang/rust
