### ISSUE TITLE
Cannot expand any folders on source sidebar

### ISSUE THREAD

**Issue by mayorovp** [rust-lang/www.rust-lang.org#1690]
### Page(s) Affected

Any source text page
https://doc.rust-lang.org/src/std/sync/mutex.rs.html for example

### What needs to be fixed?

Folders on sidebar must be expandable on click

### Suggested Improvement

Docs generator is already fixed here: https://github.com/rust-lang/rust/commit/27dcebeb3e88b97420a6d8f9279102892e27c775#diff-3944de14e1cd5e2f0b1a4e83e7d87161e82a311b4b39496abba341e3c77bd374L34-R25, but the website uses old verison

**Comment by Manishearth** [comment]
The website will use newer docs on newer releases
