### ISSUE TITLE
can't run on loongnix 

### ISSUE THREAD

**Issue by iguoya** [rust-lang/www.rust-lang.org#1693]
navigator.platform: Linux loongarch64
navigator.appVersion: 5.0 (X11; Linux loongarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.141 Safari/537.36

○ → lscpu 
Architecture:        loongarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
CPU family:          Loongson-64bit
Model name:          Loongson-3A5000LL
BogoMIPS:            4600.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            256K
L3 cache:            16384K
NUMA node0 CPU(s):   0-3

**Comment by Manishearth** [comment]
This is the tracker for the website.
