### ISSUE TITLE
Add the "helix" editor to the tools page

### ISSUE THREAD

**Issue by usagi-flow** [rust-lang/www.rust-lang.org#1696]
### Summary

The Helix editor, which supports Rust among others, isn't mentioned on the [Tools](https://www.rust-lang.org/tools) page yet.

A link to the Helix website [https://helix-editor.com](https://helix-editor.com) with the text "Helix" should be added.

### Motivation

[Helix](https://helix-editor.com) is a modal text editor which is branded as a "post-modern text editor". It's somewhat newer, but already much better than other Editors in various areas. Here's why I believe it definitely deserves its place on the "Tools" page:

#### Batteries included
Helix supports Rust _out-of-the-box_, and that includes syntax highlighting, code completion (using LSP -> rust_analyzer), refactoring, debugging, and so on. There are *no plugins* required (in fact Helix has no plugin system yet, though that is being discussed), and no configuration.
In fact, there's many features it supports by default (where other Editors like Vim would require plugins).

All of the existing tools (on the "Tools" page) require at least a plugin.

#### Written in Rust
The editor is entirely written in Rust. This may or may not seem important, but you could indirectly consider Helix as a neat little showcase for a successful Rust application.

None of the existing tools (on the "Tools" page) are written in Rust.

#### Active development
This is hard to quantify of course, but I think most would agree that development is very active. New features get added frequently.
The repository is on GitHub: [helix-editor/helix](https://github.com/helix-editor/helix)
The GitHub insights show a nice overview of the high activity: [Pulse](https://github.com/helix-editor/helix/pulse)

#### Free and Open Source
Helix is licensed under the MPL. There are no commercial versions.

### Drawbacks

I can't see any drawbacks. The risk of Helix not being maintained anymore is virtually zero.

### Rationale and alternatives

_n.a._

### Maintenance

I can't imagine maintenance being required. The website domain [https://helix-editor.com](https://helix-editor.com) is highly unlikely to change. If something needs to be changed about it, I'll happily file a PR.

### Unresolved Questions

_n.a._

### Disclaimer
I started to use Helix some months ago (around May) and I've been using it on a daily basis since then. I've been using Neovim before.
I've also started developing additional features and contributing code for Helix.

**Comment by dzhibas** [comment]
I think Zed is yet another editor used by rust developers
