### ISSUE TITLE
The governance page still links to the 2021 roadmap

### ISSUE THREAD

**Issue by pygy** [rust-lang/www.rust-lang.org#1699]
### What needs to be fixed?

The roadmap link is stale. I'm not following the Rust dev process closely, and I couldn't find a 2022 roadmap in the RFC repo... I suppose [this](https://lang-team.rust-lang.org/roadmaps/roadmap-2024.html) is the new home for the roadmap.

### Page(s) Affected

https://www.rust-lang.org/governance

### Suggested Improvement

Since this is a recurring issue (#846 #1007 #1328), it may be worthwhile to bake an expiration date into the build script, after which the roadmap section is automatically removed from the site and a warning is issued.

**Comment by pygy** [comment]
The @Manishearth shouldn't the link to the past roadmap be removed altogether then ?

**Comment by Manishearth** [comment]
Unsure! Things from it are still being done.

**Comment by pygy** [comment]
Indeed... The problem, if there's one may lie in the "2021" part of the name then...

As it is, it looks like an oversight.

**Comment by Manishearth** [comment]
We coudl say latest, I'd rather not make changes to the RFC itself.

**Comment by Manishearth** [comment]
FWIW, currently we're just avoiding changes to the website out of caution, it's undermaintained and has taken up a lot of energy for little benefit, and the folks maintaining the website _do not want_ to be in charge of decisions like this anymore.

**Comment by pygy** [comment]
This is understandable. https://github.com/rust-lang/www.rust-lang.org/graphs/contributors tells the story, I should have looked first, I assumed that the Web site was actively maintained.

I can change the `en-US` and `fr` text to say "latest".

How do I proceed for the other translations? Is it ok to ping the folks who did them? If so, I could open a PR with my translations, and ask the translators to open PRs on my fork/branch with theirs, and I'll ping you once all of them are done.

**Comment by Manishearth** [comment]
The translations are typically done on Pontoon (pontoon.rust-lang.org), but I'm not sure how many of the translators are still active. Overall when we make changes to the English version we let the translators update things when they have time, we don't fix them all at once. I'd leave them be for now.

**Comment by pygy** [comment]
Ok, I'll send a PR later this evening for French and English, and I'll have a look at pontoon (not familiar with the platform).
