### ISSUE TITLE
Community page lists 2020 events

### ISSUE THREAD

**Issue by nuke-web3** [rust-lang/www.rust-lang.org#1720]
### What needs to be fixed?
Content on events and happenings in the community is quite stale :grimacing: 

### Page(s) Affected
https://www.rust-lang.org/community

### Suggested Improvement
- Have someone own that this page is updated regularly
- (less ideal) remove explicitly dated materials that are likely to become stale

**Comment by blyxyas** [comment]
We should change that link to [this list](https://foundation.rust-lang.org/events/), that is updated by the Foundation

**Comment by mariannegoldin** [comment]
@blyxyas @nuke-web3 Refreshing this thread :) We will make the suggestion to update the community pag.e 

In the meantime, please feel free to reference the TWIR Events list, which is meticulously compiled and includes events from the date of publication to 5 weeks out.

**Comment by Manishearth** [comment]
Yeah we should point this elsewhere

**Comment by senekor** [comment]
I can work on this. This Week in Rust seems like a great place to link to. I'm trying to link to the latest issue, but I'm not sure if that's possible? Something like `this-week-in-rust.org/blog/latest/#upcoming-events` would be great.

Alternatively... we could build that feature into our own templating, but that seems quite hacky.

**Comment by senekor** [comment]
Is the google form to "register your event" still active?
