### ISSUE TITLE
Add VIZIO to Production Users page

### ISSUE THREAD

**Issue by nathanweston-vizio** [rust-lang/www.rust-lang.org#1723]
### Summary
Recognize VIZIO as a company that uses Rust in production.

### Motivation
VIZIO uses Rust in their ad mediation layer to handle high-volume, low-latency ad requests and wants to be listed on the Production Users page.

### Drawbacks
No reason to not do this.

### Rationale and alternatives
N/A

### Maintenance
Potential future changes to the Vizio logo/landing page will be identified/submitted by the VIZIO team.

### Unresolved Questions
None

**Comment by Manishearth** [comment]
We're not really adding production users to the site at the moment
