### ISSUE TITLE
Passing ownership of `ferris-says` to rust-lang

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang/www.rust-lang.org#1735]
Hello! I'm the owner of [`ferris-says`](https://github.com/mgattozzi/ferris-says) which has been used on the main website for many years now as an introduction to Rust. This was originally a crate I had made for my RustConf talk back in like 2017 and was then added to the website as part of the redesign a few years back. Now, however, I no longer wish to maintain it, but it's still something that people open up issues for or PRs for new features every now and then. I'm opening up this issue to discuss passing the crate and maintenance to the org considering it's used still on the website and I don't want to just delete a repo and yank the code without any heads up for something that's kind of critical to branding and an introduction to the language. I think the code could use a lot of love and care as it's woefully out of date in terms of what is idiomatic and as an entry point to the language it's should be something that's a pristine example of what a Rust crate looks like and I do not have the time or energy to polish it up to snuff.

I would like to pass on ownership provided I still maintain the copyright and acknowledgement for having made it originally, but beyond that I'm fine with the code being changed to fit whatever need or changed however is needed under the terms of the license in the repo.

I didn't know what team owns this or who to talk to so I'm opening up the issue here in hopes it'll get a response.

**Comment by Manishearth** [comment]
There used to be plans for a team for the website but they kinda died. At this point the website is largely maintained by @pietroalbini and I as a matter of last resort, though it's kinda also in maintenance mode and we largely just accept bugfixes and changes to content made by the teams. We're hoping to fix that at some point but for now that's what we have :shrug:.

I'm happy to accept ownership: you can transfer the crate to me and I'll bounce it over into rust-lang (or you can transfer it into rust-lang directly if you have that ability, idk!), and also add me as a crate owner. I can take it from there and add more rust-lang people etc. Happy to have you still have access or remove your access, whatever you want to do with it. We can update the readme to mention you if that's not there already.

Thanks for all you've done, enjoy not having to think about this! :smile:

**Comment by pietroalbini** [comment]
@mgattozzi transfer the repository and the crate over to my account (Manish cannot transfer repositories to the `rust-lang` org), I'll take care of the rest.

**Comment by Manishearth** [comment]
Oh, huh, i could swear i kept that ability but maybe I'm wrong!

**Comment by mgattozzi** [comment]
I sent the request @pietroalbini. I've also added you and @Manishearth as owners of the ferris-says and fsays crate so you can publish new versions without needing me. Yeah just mention me in the readme and keep me as an author are my only two wishes, beyond maintaining the copyright as I stated. Beyond that feel free to add whatever you want or do whatever needs to be done for the code.

**Comment by pietroalbini** [comment]
> and keep me as an author

Whelp I acted on the notifications before checking your reply -- do you mean you'd still like to have publish perms on the crate on crates.io? Otherwise I was changing things to be the standard "rust-lang-owner + rust-lang/website" we use for Rust-controlled packages.

**Comment by pietroalbini** [comment]
Ooh or are you mentioning in `authors = []`?

**Comment by mgattozzi** [comment]
Yeah just `authors = [] ` !

**Comment by mgattozzi** [comment]
Looks like this was transferred over. Thanks so much @pietroalbini and @Manishearth!
