### ISSUE TITLE
Update `learn/get-started` article so it uses `ferris-says` version `0.3.1`

### ISSUE THREAD

**Issue by aleksanderkrauze** [rust-lang/www.rust-lang.org#1736]
### What needs to be fixed?
Introductory article uses an old version of dependency [ferris-says](https://crates.io/crates/ferris-says) with *very* big [unsoundness](https://github.com/mgattozzi/ferris-says/pull/21) bug. It should be updated to a new version where it is fixed, otherwise someone who is new to rust could look at the source code of this dependency and get very wrong ideas about `unsafe` and `&str`.

### Page(s) Affected
https://www.rust-lang.org/learn/get-started

### Suggested Improvement
Update this article so it uses new version of dependency and change sample code as API changed slightly. I am willing to provide a PR for that.

**Comment by dtolnay** [comment]
Fixed by https://github.com/rust-lang/www.rust-lang.org/pull/1848.
