### ISSUE TITLE
Not sure if this is a bug or a request: There is no downloads page for release artifacts like documentation

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/www.rust-lang.org#1741]
I can't find any page with Rust releases and downloads on the website. There is the GitHub releases page but there the only artifacts are the default one that GitHub makes by just bundling the entire repo.

Basically anything rustup has should be accessible on the website for download. I'm specifically looking for the stdlib documentation. I don't have rustup available on my system as my OS doesn't support rustup and rustup doesn't support my OS. But anyway it should be available for download.

**Comment by Manishearth** [comment]
In general non-rustup workflows are not documented, and downloading other artifacts like that works but isn't considered a supported workflow. Sorry.
