### ISSUE TITLE
Inconsistent handling of https://doc.rust-lang.org/std vs https://doc.rust-lang.org/std/

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/www.rust-lang.org#1747]
Hi. I'm writing Chromium extension for personal use. This extension should redirect https://doc.rust-lang.org/std (and similar) to https://doc.rust-lang.org/nightly/std . When writing this extension I noticed that doc.rust-lang.org threats /std and /std/ differently. This caused me pain, i. e. I had to write additional code in my extension to handle this. This makes me sad.

So, current situation is: `/std` gets redirected to `/stable/std/`. But `/std/` doesn't redirect to anywhere.

### Page(s) Affected
- https://doc.rust-lang.org/std
- https://doc.rust-lang.org/std/

### What needs to be fixed?
Two URLs above should redirect to same page, not to two different ones

**Comment by Manishearth** [comment]
This tracker only tracks issues around the main website. I'm not sure where the documentation deployment is handled
