### ISSUE TITLE
Confusing wording in the Rust tutorial regarding strings

### ISSUE THREAD

**Issue by nickdab** [rust-lang/www.rust-lang.org#1748]
### What needs to be fixed?
The text explaining the format! macro and how it affect strings in chapter 8, part two (I've bolded confusing/incorrect wording): "This code also sets s to tic-tac-toe. The format! macro works like println!, but instead of printing the output to the screen, it returns a String with the contents. The version of the code using format! is much easier to read**, and the code generated by the format! macro uses references so that this call doesn’t take ownership of any of its parameters.**"

![Screenshot 2022-12-05 at 11-47-33 Storing UTF-8 Encoded Text with Strings - The Rust Programming Language](https://user-images.githubusercontent.com/629361/205721235-8077ef09-f665-4f67-9efc-e56237c2424d.png)

As someone who is just getting used to references, this turned my understanding on its head for a little while. I think that we are missing the crucial information that the format! macro takes those references and copies of the values inside of them, returning a totally new string that lives in a completely different memory address. As the paragraph stands, without that information, and in the context of the information just shared about how Add works with strings, it starts to sound like references are copies of values. I stopped reading and spent the next 2 hours experimenting with vectors and strings to ensure I understood what a reference really was.

### Page(s) Affected
[https://doc.rust-lang.org/book/ch08-02-strings.html](https://doc.rust-lang.org/book/ch08-02-strings.html)

### Suggested Improvement

This code also sets s to tic-tac-toe. The format! macro works like println!, but instead of printing the output to the screen, it returns a String with the contents of the supplied string references, **copied and combined into a new String.** The version of the code using format! is much easier to read, and the code generated by the format! macro uses references so that this call doesn’t take ownership of any of its parameters."

**Comment by remlse** [comment]
The book is in another repository, you might want to open this issue [there](https://github.com/rust-lang/book).
