### ISSUE TITLE
Code using ferris_says dependency on get-started page does not build/run

### ISSUE THREAD

**Issue by littledip** [rust-lang/www.rust-lang.org#1750]
### What needs to be fixed?

Code using ferris_says dependency on https://www.rust-lang.org/learn/get-started does not build/run

### Page(s) Affected

https://www.rust-lang.org/learn/get-started

### Suggested Improvement

Replace asBytes() with asStr() and the code builds/runs

**Comment by ehuss** [comment]
To clarify, the code should work if the `Cargo.toml` has the instructed version 0.2 with `ferris-says = "0.2"`.  Only if you use the newer 0.3 version will it cause problems because the API changed.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/www.rust-lang.org/issues/1736
