### ISSUE TITLE
Mistake in text in "The Rust Programming Language"

### ISSUE THREAD

**Issue by puzzledsab** [rust-lang/www.rust-lang.org#1752]
### What needs to be fixed?
It says that the line
`println!("x = {x} and y + 2 = {}", y + 2);`
would print
`x = 5 and y = 12`
It should be
`x = 5 and y + 2 = 12`

### Page(s) Affected
https://doc.rust-lang.org/book/print.html

**Comment by Manishearth** [comment]
Please file this on https://github.com/rust-lang/book
