### ISSUE TITLE
Are we .. ? top level link

### ISSUE THREAD

**Issue by EvangelosKolimitras** [rust-lang/www.rust-lang.org#1753]
### Summary

It would be great to have a dropdown menu(or link to another page) something like
![image](https://user-images.githubusercontent.com/35934542/209848490-023cc380-e5af-4012-ac97-1f9ed7fc10e5.png)
so we could let a user navigate through the segments Rust could be used into.

### Motivation
Top level menus provide the ease to the user to finish faster his/her "user journey". Having a link with a dropdown listing all the available spaces or a totally seperate page would help users find out faster where the language could be used for.

### Drawbacks
One more link to the menu bar.

### Rationale and alternatives

- What is the impact of not doing this? It Keeps the "Are we ... yet" websites kinda hidden from users. 

### Maintenance
Curtainly I could maintain it. If offered.

**Comment by Manishearth** [comment]
In general we try not to link to unofficial content on the website

**Comment by EvangelosKolimitras** [comment]
Perhaps integrating it into the main website? I mean there is value into centralizing rust resources I guess.

**Comment by Manishearth** [comment]
We'd have to agree to maintain it, and that's a ton of work. Are we ... yet websites tend to be ephemeral as well.

In general the website is not accepting major content changes unless proposed by a team.

**Comment by EvangelosKolimitras** [comment]
Ok. I assume we drop the idea all together. Closing.
