### ISSUE TITLE
The CTAs in learning page are not inviting

### ISSUE THREAD

**Issue by anthonydheysum** [rust-lang/www.rust-lang.org#1754]
### Page(s) Affected

https://www.rust-lang.org/learn

### What needs to be fixed?

The CTAs(buttons) don't highlight as if they are call to actions, while hovering or scrolling the page it is easy to be missed. (I ended up with worse udemy courses :) 

### Suggested Improvement

The CTAs should be of warmer colors, or should popup while hovering or scrolling the page. All the CTAs (the buttons) should be of same color or size.

**Comment by Manishearth** [comment]
They do highlight on my browser, and always have. What's your setup? They also are all the same size.

As for color the color scheme was holistically designed and we typically don't take feedback for changing it.

(Closing as there is no applicable feedback, will reopen if we can figure out why they haven't been highlighting on your machine)
