### ISSUE TITLE
Rusqlite insert data issue

### ISSUE THREAD

**Issue by sakabda** [rust-lang/www.rust-lang.org#1764]
Hi Rust, I want to insert value in a case insensitive column by using rusqlite, but I can not able to do that, rusqlite not allow me to insert data in case insensitive filed, Please help with that. Thank you

**Comment by wezm** [comment]
I think this question would be best asked as a [discussion on the rusqlite repository](https://github.com/rusqlite/rusqlite/discussions). Be sure to include a complete code example and any errors you are encountering to maximise the chance someone can help.

**Comment by sakabda** [comment]
Thank you @wezm for your kind reply
