### ISSUE TITLE
Mark nightly features in the fuzzy search preview

### ISSUE THREAD

**Issue by zim0369** [rust-lang/www.rust-lang.org#1765]
![image](https://user-images.githubusercontent.com/85027668/217718031-0d1de123-db96-4718-b61b-ed2d5984719a.png)

### Summary
Above is an image of the search menu for the docs on this website. There is no indication if any of those features is nightly. The user has to go inside the docs to find out that the feature is nightly. It would be convenient if there was an indication in the fuzzy search menu on the left if the feature is nightly or to save space highlight nightly features in the list with a different color.

### Motivation
It helps saving the users time. If the user is only concerned with stable features then they might not even want to proceed with that feature. It is a nice idea to know that before having to go through the docs.

### Drawbacks
There doesn't seem to be any unless this makes the menu cluttered which I don't think it should. Or it could be hard to implement as I do not know anything about web development.

### Rationale and alternatives
There could be two ways to implement this:
1. Add a column with icons for the nightly feature
2. Highlight the nightly features with a different color which is visible to people with reduced ability to distinguish colors.
I'm not very sure about accessibility here.

### Maintenance
-

### Unresolved Questions
NA

**Comment by Manishearth** [comment]
Please file this on rust-lang/rust
