### ISSUE TITLE
sensitive information disclosure (aws keys leak)

### ISSUE THREAD

**Issue by RavitejaPegada** [rust-lang/www.rust-lang.org#1769]
- steps to reproduce :
- 
- Go to the github and visit the provided link 
- 
- https://github.com/rust-lang/rust/blob/master/.github/workflows/ci.yml
- 
- aws keys were leaking in the source code please check .
- 
- aws keys need to to be hidden ,keys are leaking !
![image](https://user-images.githubusercontent.com/107602866/219865619-1dafbd16-cede-4f09-bf62-51155facf87d.png)

**Comment by Manishearth** [comment]
That's not the secret part of the key
