### ISSUE TITLE
Add gnome-builder to the list of Rust "first-class editor support" tools

### ISSUE THREAD

**Issue by Unisa-Merni-392** [rust-lang/www.rust-lang.org#1772]

**Comment by senekor** [comment]
I think I'm going to close this as "not planned". Gnome Builder is not a general purpose editor and therefore not high up on the popularity list.

The goal shouldn't be to provide an _exhaustive_ list of editors with support, that would be impractical. Rust is a mature language at this point, it would be more surprising to see a serious code editor _without_ Rust support. Still, having a list with the most popular ones doesn't hurt.
