### ISSUE TITLE
Missing parenthesis

### ISSUE THREAD

**Issue by tidley** [rust-lang/www.rust-lang.org#1774]
### What needs to be fixed?
Getting Started guide has a code snippet with missing parenthesis after stdout in the `stdout.lock()`

### Page(s) Affected
https://www.rust-lang.org/learn/get-started

### Suggested Improvement
Replace:
`let mut writer = BufWriter::new(stdout.lock());`
With:
`let mut writer = BufWriter::new(stdout().lock());`

**Comment by Manishearth** [comment]
No, there's a `let stdout = stdout()` up above
