### ISSUE TITLE
get started page

### ISSUE THREAD

**Issue by danilobalarini** [rust-lang/www.rust-lang.org#1775]
### Page(s) Affected
https://www.rust-lang.org/pt-BR/learn/get-started

### What needs to be fixed?
Update ferris-says to 0.3.1

### Suggested Improvement
Cargo.toml
[dependencies]
ferris-says = "0.3.1"

src/main.rs
use ferris_says::say;
use std::io::{stdout, BufWriter};

fn main() {
    let stdout = stdout();
    let message = String::from("Hello fellow Rustaceans");
    let width = message.chars().count();

    let mut writer = BufWriter::new(stdout.lock());
    say(&message, width, &mut writer).unwrap();
}

**Comment by danilobalarini** [comment]
![get_started_rust_page](https://user-images.githubusercontent.com/128736/221733533-9c99e57f-7428-4283-b742-edbe59a574cc.png)

example

**Comment by Manishearth** [comment]
https://github.com/rust-lang/www.rust-lang.org/issues/1736
