### ISSUE TITLE
List support for Visual Studio 2022 on https://www.rust-lang.org/tools

### ISSUE THREAD

**Issue by parthopdas** [rust-lang/www.rust-lang.org#1781]
### Summary

List support for Visual Studio 2022 on https://www.rust-lang.org/tools

### Motivation

Supports the use case of windows developers on VS 2022.

### Drawbacks

n/a

### Rationale and alternatives

Rust has VS 2022 support now. Many users come to this site to download tools. The impact of not doing this is they may not know about the VS2022 support for rust.

### Maintenance

I'll raise the PR and maintain it.

**Comment by Hollow-Glitch** [comment]
What do you mean by "support"? Because I just tried debugging a simple rust program with VS2022 and not even breakpoint triggering works.
