### ISSUE TITLE
Replace rocket with stable and maintained web framework

### ISSUE THREAD

**Issue by senekor** [rust-lang/www.rust-lang.org#1783]
### What needs to be fixed?

The web server example should use a different framework. Rocket has been in a questionable maintenance status for years. Its latest stable release requires nightly. Newcomers may get a bad impression of the state of Rust's ecosystem, if the "officially" recommended web framework is poorly maintained and requires an unstable toolchain.

Judging from download numbers on crates.io and (subjectively perceived) "internet buzz", axum and actix-web are generally favored by the community these days. Both are stable and actively maintained.

### Page(s) Affected

https://www.rust-lang.org/what/networking

### Suggested Improvement

The code snippet using rocket should be replaced by one using axum or actix-web.

I will be happy to contribute this change if the maintainers agree with it.

**Comment by Manishearth** [comment]
I think help for _non-content_ changes is highly appreciated. This is a content change and I'd rather not have us do that just yet. I'll keep it in mind that you're interested in helping out here.


In general as the official website we have to be careful about picking examples. Annoyingly, the domain WG that was working on networking stuff is no longer active so we can't delegate this particular thing to them.

**Comment by remlse** [comment]
I understand completely. What can I help with? Should I go through the issues, pick non-content related ones and work on any of those?

**Comment by Manishearth** [comment]
I don't know if there's much to do right now. Feel free to go through the issues though.

**Comment by senekor** [comment]
Rocket now has a [stable release](https://rocket.rs/v0.5/news/2023-11-17-version-0.5/) which doesn't require nightly and [an organisation](https://rocket.rs/v0.5/news/2023-11-17-rwf2-prelaunch/) is being built to ensure reliable maintenance into the future. :partying_face:  

With these changes, I don't see any pressing reason to change the example anymore.
