### ISSUE TITLE
Extra space before period on code-of-conduct page

### ISSUE THREAD

**Issue by beofhelp** [rust-lang/www.rust-lang.org#1793]
### What needs to be fixed?
An extra space typo causes the formatting to be inconsistent since there is not a similar extra space following a link lower on the page.

> These are the policies for upholding our community’s standards of conduct. If you feel that a thread needs moderation, please contact the [Rust moderation team](https://www.rust-lang.org/governance/teams/moderation) .

vs

> Adapted from the [Node.js Policy on Trolling](http://blog.izs.me/post/30036893703/policy-on-trolling) as well as the [Contributor Covenant v1.3.0](https://www.contributor-covenant.org/version/1/3/0/).

### Page(s) Affected
https://www.rust-lang.org/policies/code-of-conduct

### Suggested Improvement
Remove the extra space before the period in the following sentence:
> These are the policies for upholding our community’s standards of conduct. If you feel that a thread needs moderation, please contact the [Rust moderation team](https://www.rust-lang.org/governance/teams/moderation) .

**Comment by remlse** [comment]
I think the extra whitespace comes from the fact that one link is a fluent parameter (depends on the currently selected language), while the other is "hardcoded" in the template. The witespace around the parameter seems to be added automatically, I'm not sure how to suppress it.
