### ISSUE TITLE
Allow to use MSVC - VS 2022

### ISSUE THREAD

**Issue by Andrysky** [rust-lang/www.rust-lang.org#1799]
### Summary
RUSTUP-INIT.EXE https://www.rust-lang.org/tools/install
requires old toolchain (MSVC - VS 2019 and older)

### Motivation
the modern version is visual studio 2022 / MSVC - VS 2022 please support this version - so that you do not need to install an outdated toolchain on your computer

**Comment by Manishearth** [comment]
This repository is for the website
