### ISSUE TITLE
The link to the "getting started" page from the install page is broken

### ISSUE THREAD

**Issue by dicaeffe** [rust-lang/www.rust-lang.org#1804]
### What needs to be fixed?

The link to the "getting started" page from the install page is broken.

### Page(s) Affected

I saw it for the italian and english version. I do not know if are affected all languages.

| language | page | sentence | link |
| --------- | ----- | --------- | ---- |
| Italian | [Install](https://www.rust-lang.org/it/tools/install) | Se stai iniziando con Rust e vorresti una guida passo passo più dettagliata, guarda la nostra pagina [getting started](https://www.rust-lang.org/it/tools/%E2%81%A8%20%20%20%20%20%20%20%20%20%20%20%20/it/learn/get-started%E2%81%A9) . |
| English | [Install](https://www.rust-lang.org/tools/install) | If you're just [getting started](https://www.rust-lang.org/tools/%E2%81%A8%20%20%20%20%20%20%20%20%20%20%20%20/learn/get-started%E2%81%A9) with Rust and would like a more detailed walk-through, see our getting started page. |

### Suggested Improvement

Probably the correct link is:

| language | link |
| --------- | ---- |
| Italian | https://www.rust-lang.org/it/learn/get-started |
| English | https://www.rust-lang.org/learn/get-started |

**Comment by Manishearth** [comment]
@remlse uh oh, this might be a rocket upgrade problem

**Comment by remlse** [comment]
I'll have a look!

**Comment by Manishearth** [comment]
The FSI is due to fluent applying isolation (scope.bundle.use_isolating).

In the long run we probably want handlebars-fluent to distinguish between actual text and non-text stuff like URLs

**Comment by Manishearth** [comment]
https://github.com/Manishearth/handlebars-fluent/pull/12

**Comment by Manishearth** [comment]
The spaces are coming from the fact thatwe've got space indents in there, I _think_ fixing the FSI problem will get them to be trimmed, but if not we should fix up fluent-handlebars to do this (and maybe add a notrim param)

**Comment by Manishearth** [comment]
The fix works https://github.com/rust-lang/www.rust-lang.org/pull/1805

**Comment by remlse** [comment]
Wow, that was fast :smiley:
