### ISSUE TITLE
Please add links to Chinese translations of the rust reference and cargo book.

### ISSUE THREAD

**Issue by VectorWorkshopBaoErJie** [rust-lang/www.rust-lang.org#1813]
Please add links to Chinese translations of the rust reference and cargo book.

https://vectorworkshopbaoerjie.github.io/book/cargobook/

https://vectorworkshopbaoerjie.github.io/book/rustreference/

**Comment by remlse** [comment]
Is there a precedent for linking to unofficial translations of official documentation? I don't think so. I know there is an unofficial translation of the book for German and the website doesn't link to that. If it is desired to link to translations, it would probably make sense for them to be under the official governance of the project.

**Comment by Manishearth** [comment]
As a rule we do not link to unofficial material on the website.

That said, the Chinese localized website does additionally link to a translation of the book with a note that it is unofficial.
