### ISSUE TITLE
The `?` operator and side-effects

### ISSUE THREAD

**Issue by detreville** [rust-lang/www.rust-lang.org#1814]
### What needs to be fixed?
Are the two `add_last_numbers` examples really the same? Or _might_ the second example `pop` just one element from the `Vec`, while the first always `pop`s two (if there are enough to `pop`, of course)?

### Page(s) Affected
https://doc.rust-lang.org/std/option/

### Suggested Improvement
Rust's rules are poorly explained here for short-circuiting function execution in the presence of side-effects and  the `?` operator. Either change the examples (most simply by executing all the side-effects before any use of the `?` operator) or explain the evaluation rules that give these two examples the same semantics.

**Comment by Manishearth** [comment]
The repo for the stdlib docs is https://github.com/rust-lang/rust

**Comment by Manishearth** [comment]
(also in this case I don't think it matters wrt short circuiting due to the behavior of `pop()`: it only returns None if there's nothing to pop, so the behavior of subsequent pops is irrelevant)

**Comment by detreville** [comment]
Thanks. That’ll be another issue, to come. Cheers,JohnOn Apr 27, 2023, at 20:44, Manish Goregaokar ***@***.***> wrote:﻿
The repo for the stdlib docs is https://github.com/rust-lang/rust
