### ISSUE TITLE
I think I found a sentence with a problematic meaning

### ISSUE THREAD

**Issue by V4yukon** [rust-lang/www.rust-lang.org#1816]

**Comment by V4yukon** [comment]
robot error

**Comment by V4yukon** [comment]
sorry

**Comment by remlse** [comment]
Why did you edit and remove the description?

This is the repository of the website, not the book, which is [here](https://github.com/rust-lang/book).

That being said, I think the sentence you think has an error is fine. It refers to the listing *above*, not the one below.

I recommend closing this.

**Comment by V4yukon** [comment]
ok，I'm sorry，I think I'm mistaken。

**Comment by V4yukon** [comment]
sorry
