### ISSUE TITLE
Out of date "Email the Core Team" button on /policies/licenses

### ISSUE THREAD

**Issue by steffahn** [rust-lang/www.rust-lang.org#1826]
The title says it all ^^

Core team is replaced by the new Leadership Council on /governance/teams already, so for consistency, the licenses page needs updating, too.

**Comment by Manishearth** [comment]
Going to be a bit inconsistent wrt computer access this week, would appreciate a PR fixing the English translation, and updating other translations that literally use the phrase "core team". If you list the translations that translated the word "core team" as well I can figure out what to do with them later.

**Comment by steffahn** [comment]
I'll make a PR later today. Looks like in /governance/teams, there are no translations of "leadership council" yet either, so adding translations can probably be a subsequent issue applying to both places, right? Just to confirm, the leadership council is indeed supposed to be the new recipient to be listed on the license page, right?

**Comment by Manishearth** [comment]
Yes.

**Comment by steffahn** [comment]
I've partially finished the PR today.

I’ve gone with applying minimal edits to all translations, even the ones that translated "core teams", employing some help from ChatGPT in order to insert the English term "Leadership Council" or "Rust Leadership Council" in the correct place and in a (hopefully) grammatically correct way. Except for Japanese, which I’m a bit familiar with, so I felt it was appropriate to insert a transcription, in a similar style as was done to the term "core team" previously.

I’ll also list the names of the labels that were updated so that any _actual_ translators can feel free to follow-up by inserting a more appropriate native term, at a later point in time, presumably one matching the eventual translation of the new entry on the /governance/teams page.

While I was at it, I’ve also found an instance of a label mentioning "Core Team", on the /production page, where [until 2020](https://github.com/rust-lang/www.rust-lang.org/pull/1037) the "production team" used to be mentioned, but that change never made it into any of the translations, so they kept mentioning a non-existing team (whilst the link was a mailto pointing to the core team).

I'll most likely publish a PR within the next 24h :-)

**Comment by steffahn** [comment]
I've also seen that there's files, sometimes partial ones, for more languages than the ones that appear in the dropdown. I’ve only modified the 10 languages that *do* appear, notably e.g. Korean and Polish are not shown on the website, so I reduced my effort and excluded those so far. If anyone could point me to more information what's up with languages that don't appear on the website, and whether they should be kept updated to any degree, feel free to leave a link or explanation.

**Comment by Manishearth** [comment]
Yeah, that should be fine, those are partial translations that the translator teams have not finished.

**Comment by steffahn** [comment]
Took a little longer to get back to finishing this PR is up in a second
