### ISSUE TITLE
[css] remove Skeleton

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#183]

**Comment by nrc** [comment]
Things we are using Skeleton for:

- [ ] - container and columns layout
- [ ] - some styles on `body`
- [ ] - some header styles
- [ ] - `code` styles
- [ ] - spacing
- [ ] - `hr`

**Comment by nrc** [comment]
Seeing as we're already using flexbox in some places, IMO we should flexbox for all of our layout, rather than replacing the Skeleton grid with the Tachyons one.

I think everything else is a matter of seeing what the Tachyons defaults look like and tweak anything we're unhappy with.

**Comment by skade** [comment]
Superseded by #780
