### ISSUE TITLE
"Getting Started" page code font is difficult to read

### ISSUE THREAD

**Issue by tgross35** [rust-lang/www.rust-lang.org#1840]
### Page(s) Affected

Getting started https://www.rust-lang.org/learn/get-started, possibly other pages with code

### What needs to be fixed?

The theming of code blocks is pretty difficult to read and has really low contrast, especially in sections with the white background. Almost seems like it is intentionally muted?

![image](https://github.com/rust-lang/www.rust-lang.org/assets/13724985/910299bf-067c-4efc-b473-74804212087d)

![image](https://github.com/rust-lang/www.rust-lang.org/assets/13724985/4a4c51f3-abb9-4956-89d8-2a841aaaac06)

### Suggested Improvement

Just adjust the theme to something that stands out more

**Comment by senekor** [comment]
I don't have a strong opinion on whether this should be changed. Out of curiosity, I clicked through a couple themes from [this list](https://github.com/highlightjs/highlight.js/tree/main/src/styles) and I quite like `ally-dark`, I think it has good contrast while being easy on the eyes on most backgrounds. I can open a PR if it is desired.

![image](https://github.com/rust-lang/www.rust-lang.org/assets/54984957/077325bc-7442-44b4-8932-1c41cfe8365d)

![image](https://github.com/rust-lang/www.rust-lang.org/assets/54984957/231f0536-58a0-43ff-a8c5-bf8b4825346b)

![image](https://github.com/rust-lang/www.rust-lang.org/assets/54984957/8a5099b1-a841-4128-84cb-cb60471cbcfb)

![image](https://github.com/rust-lang/www.rust-lang.org/assets/54984957/e951d48e-d397-4b32-b3bd-775a51aed3c2)

**Comment by tgross35** [comment]
That looks 1000x better to me! I can barely make out "dependencies" in my first screenshot unless I put my face up to the screen, much easier to read in your example.

**Comment by Manishearth** [comment]
I do like that too; I would be open to a PR fixing this! Thanks for investigating, @senekor!
