### ISSUE TITLE
"Old" signing key missing from rust-lang.org 

### ISSUE THREAD

**Issue by ernstki** [rust-lang/www.rust-lang.org#1851]
<abbr title="too long; didn't read"><em>tl;dr</em></abbr>: The "old" (but not "very old") GPG signing key referred to by https://forge.rust-lang.org/archive/release-history.html is not available for download from rust-lang.org, and should be re-uploaded.

### What needs to be fixed?

Context from [`src/archive/release-history.md`](https://github.com/rust-lang/rust-forge/blob/ddb67aeb2f56052f05cc5ec7b07ad2cff894d4fd/src/archive/release-history.md#L6C8-L6C52):

```markdown
# Rust Release history
This is an archive of Rust release artifacts from 0.1–1.7.0. Each release is
signed with the Rust [GPG signing key][key] ([older key][pre-0.8-key], [even
older key][pre-0.5-key]).

[key]: https://www.rust-lang.org/rust-key.gpg.ascii
[pre-0.8-key]: https://www.rust-lang.org/rust-key-old.gpg.ascii
[pre-0.5-key]: https://www.rust-lang.org/rust-key-very-old.gpg.ascii
```

All three of these URLs are currently 404s. This has been reported in rust-lang/rust-forge#695, and I intend to do the PR.

The other two keys have moved from www.rust-lang.org to static.rust-lang.org (which is fine). However, the target of the `pre-0.8-key` link is not on static.rust-lang.org alongside the others, and should probably be re-uploaded.

### Page(s) Affected

* https://www.rust-lang.org/rust-key-old.gpg.ascii (old link; now a 404)
* https://static.rust-lang.org/rust-key-old.gpg.ascii (probably the intended new location)

#### See also

* https://github.com/search?q=org%3Arust-lang+rust-key.gpg+language%3AMarkdown&type=code
* https://github.com/search?q=org%3Arust-lang+rust-key-old.gpg+language%3AMarkdown&type=code

### Suggested Improvement

<s>Re-upload the ["old" signing key](https://github.com/rust-lang/prev.rust-lang.org/blob/master/rust-key-old.gpg) to static.rust-lang.org so that the relevant forge.rust-lang.org document can have its links updated (rust-lang/rust-forge#695).</s> Rename `rust-key-old.gpg` → `rust-key-old.gpg.ascii` for consistency with the other two signing keys.

**Edit**: See comment [below](https://github.com/rust-lang/www.rust-lang.org/issues/1851#issuecomment-1666568091).

**Comment by ernstki** [comment]
OK, after looking at https://github.com/rust-lang/prev.rust-lang.org more closely, I can see that the only problem with finding the "old" signing key on static.rust-lang.org is it lacks the `.ascii` extension of the other ones.

Maybe the error in forge's `src/archive/release-history.md` just wasn't noticed for all those years because of this inconsistency, which fooled me, too.

What do you all recommend? Rename the `rust-key-old.gpg` → `rust-key-old.gpg.ascii` to match the other two, or just live with it?

**Comment by Manishearth** [comment]
cc @rust-lang/infra, I think they're the ones who deploy this

(closing here since this repo is only for www.rust-lang.org)

**Comment by ernstki** [comment]
@Manishearth Thanks for taking a look. In that case, where would I report a problem with static.rust-lang.org?

I figured this was the correct repo, since the GPG signing keys in question were up until recently hosted on www.rust-lang.org (for a liberal definition of "recently").

**Comment by Manishearth** [comment]
you should ask on t-infra on zulip in the further

I cc'd the infra team so they've already been informed about this issue

**Comment by ernstki** [comment]
OK, thanks. I don't know what "t-infra on Zulip" means off-hand, but if something like this comes up again, I'll respect your wishes and look into that option instead.

**Comment by Manishearth** [comment]
The infra team largely discusses things on the t-infra channel [here](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra).

It's fine, I'm glad to help redirect you to the right spot, don't worry about it.
