### ISSUE TITLE
Format Macro Named Argument Example is Confusing

### ISSUE THREAD

**Issue by thisisscotts** [rust-lang/www.rust-lang.org#1862]
### What needs to be fixed?
format! macro documentation could be improved by changing one of the examples to be more obvious to new users.

### Page(s) Affected
https://doc.rust-lang.org/std/macro.format.html

### Suggested Improvement
Change example 
```format!("x = {}, y = {y}", 10, y = 30);```
to
```format!("x = {}, y = {z}", 10, z = 30);```

Additionally, assert! could be used to demonstrate final string values:
```format!("test");
let greeting = format!("hello {}", "world!");
assert!(greeting=="hello world!");
let xy = format!("x = {}, y = {z}", 10, z = 30);
assert!(xy=="x = 10, y = 30");
let (a, b) = (1, 2);
let ab = format!("{a} + {b} = 3");
assert!(ab=="1 + 2 = 3");```

**Comment by Manishearth** [comment]
This is the tracker for the website, please post on rust-lang/rust for the stdlib and its docs.

**Comment by thisisscotts** [comment]
@Manishearth Sorry, this is my first contribution on github ever. Have I missed something? 

My intention was to have the documentation updated to help new users (like me).

**Comment by Manishearth** [comment]
Yes, this is the wrong repository for documentation fixes, this repository is for www.rust-lang.org only. Check out https://github.com/rust-lang/rust instead

**Comment by thisisscotts** [comment]
Will do, thanks!
