### ISSUE TITLE
Incorrect ferris-says crate version referenced for Getting Started example.

### ISSUE THREAD

**Issue by Ninja-Spotted** [rust-lang/www.rust-lang.org#1866]
### What needs to be fixed?

In the getting started page there is a reference to the ferris-says crate that uses syntax from version 0.3.1 in the "A small Rust application" code but when installed via cargo the command shown is `cargo add ferris-says@0.2`. Which throws a type error when building.

### Page(s) Affected
The page affected is the [Getting Started](https://www.rust-lang.org/learn/get-started).

### Suggested Improvement
To fix it, simply change `cargo add ferris-says@0.2` to `cargo add ferris-says@0.3.1` or similar.

**Comment by Manishearth** [comment]
Fixed in https://github.com/rust-lang/www.rust-lang.org/pull/1861 . We haven't deployed yet
