### ISSUE TITLE
The Rust book - The code sample listing 18-15 contains spare comma

### ISSUE THREAD

**Issue by pkmichalak** [rust-lang/www.rust-lang.org#1873]
### What needs to be fixed?
The Rust book - The code sample contains spare comma.

### Page(s) Affected
Listing 18-15: Destructuring enum variants that hold different kinds of values

### Suggested Improvement
Removal of the comma
Is:
println!("Change the color to red {r}, green {g}, and blue {b}",)
Should be:
println!("Change the color to red {r}, green {g}, and blue {b}")

**Comment by senekor** [comment]
This is the repository of the website, the one of the book is [here](https://github.com/rust-lang/book).
