### ISSUE TITLE
Footer old twitter logo 

### ISSUE THREAD

**Issue by captain-Akshay** [rust-lang/www.rust-lang.org#1874]
### Page(s) Affected
All pages

### What needs to be fixed?
new svg for the the new twitter logo

### Suggested Improvement
I can would love to work on that !

**Comment by ParthMakode** [comment]
the frontend code is not hosted in this repo . where is the frontend code hosted so this bug could be solved

**Comment by senekor** [comment]
it's right here
https://github.com/rust-lang/www.rust-lang.org/blob/master/templates/components/footer.html.hbs#L34

**Comment by ParthMakode** [comment]
Thank you for showing the repo . Is it okay if i start working on it?

**Comment by captain-Akshay** [comment]
@ParthMakode thanks but i already mentioned that i could work on it once assigned.But you can work on other open issues!
@senekor please assign it to me !

**Comment by ParthMakode** [comment]
do issues have to be strictly assigned to be considered for a pull reuqest? @senekor

**Comment by senekor** [comment]
> do issues have to be strictly assigned to be considered for a pull reuqest?

Not that I know. Note that I'm not a maintainer. The fix is just copying one file and maybe changing one line of code. Just open the PR if you want (anyone).

**Comment by Manishearth** [comment]
(@senekor I'm comfortable having you consider yourself a maintainer here, btw, you've certainly earned the right)
