### ISSUE TITLE
Install Web Page Has no Appropriate Message for Debian Linux riscv64

### ISSUE THREAD

**Issue by MartinOlsenDev** [rust-lang/www.rust-lang.org#1886]
### Known Page(s) Affected:
https://www.rust-lang.org/tools/install

### Issue:
Instead of receiving an appropriate greeting message (such as "It looks like you're running macOS, Linux, or another Unix-like OS...."), it instead generates a message instructing me to file a report here using the following generated values.

navigator.platform: Linux riscv64
navigator.appVersion: 5.0 (X11; Linux riscv64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Suggested Solution
Apply the Unix-like greeting when the above web browser information is received.

**Comment by senekor** [comment]
@MartinOlsenDev maybe you can test this PR locally?

https://github.com/rust-lang/www.rust-lang.org/pull/1887

Btw. what hardware are you using and can you recommend it? I'd love to get my hands on a riscv board and take it for a spin.
