### ISSUE TITLE
bug(content): Community page links to old event lineup (2020)

### ISSUE THREAD

**Issue by onkoe** [rust-lang/www.rust-lang.org#1902]
### What needs to be fixed?

On the [Community section](https://www.rust-lang.org/community) of rust-lang.org, under the Events heading, there's a button that asks users to "Check out the 2020 Conference lineup." It dates the page a bit, making it seem outdated despite everything working fine. 🫣

### Page(s) Affected

It seems to be present only on the `/community` page. 

### Suggested Improvements

1. Refactor the text to be something like: 
   - See Previous Conferences
   - Check Out Previous Conferences
   - etc.
2. Consider changing the link to point to another list of conferences. I couldn't find a match on the Rust Blog (`blog.rust-lang.org`), but it may exist elsewhere! For example, `foundation.rust-lang.org` has a [list of previous events](https://foundation.rust-lang.org/events/) from late 2020 and beyond! 
3. Remove the button..? 

If we decide to change the button text, I'm happy to PR a change quickly, or someone else can work to make it sound perfect! 

I'm also good to work on the other two ideas or anything else, though I may need time to gather sources, ensure compliance with the site styling, etc. 

Thanks for taking a look at this minor issue! 😄✨

**Comment by Manishearth** [comment]
At this point since the events team isn't super active I'd say we should remove the button, or perhaps comment it out (in case we need the translations later)
