### ISSUE TITLE
Rust install issue

### ISSUE THREAD

**Issue by Hestel808** [rust-lang/www.rust-lang.org#1920]
I have a problem with installing Rust complier on my platform: navigator.platform: Linux armv81
navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36

**Comment by senekor** [comment]
What is the problem?

**Comment by Hestel808** [comment]
I can't download Rust compiler through pip in my IDE, rustup site also
doesn't recognize my device. I'm trying to get Rust or rustup for my IDE
for working with web3 libraries.


сб, 3 февр. 2024 г. в 10:16, Remo Senekowitsch ***@***.***>:

**Comment by Manishearth** [comment]
(this repository doesn't track the rustup website)
