### ISSUE TITLE
freedom to add curly braces to next line in rust fmt

### ISSUE THREAD

**Issue by coderboyisongithub** [rust-lang/www.rust-lang.org#1935]
### Summary

I use sublime text for rust coding and rust fmt package for formatting. One thing that simple annoys me so much is '{' bracket is auto formatted to same line of the function declaration.This is small thing but very unsettling to the mind.
for example 
```
fn main(){
}

instead of 
fn main()
{
}
```

### Motivation

Its a small diorder that in a way irritates the mind of a rust learner disrupting the flow. Everytime I create rust function, I am always annoyed by curly bracket auto formatted beside function declaration instead of next line

### Drawbacks
Affects motivation and disrupts flow.Its just irritating.There are devlopers who are curly braces in same line and there are some who want curly braces on next line.We shound have freedom to do that

**Comment by senekor** [comment]
You're in the wrong repo, the rustfmt repo is [here](https://github.com/rust-lang/rustfmt).

The configuration option you're asking for [already exists](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#brace_style), but it is unstable.
