### ISSUE TITLE
en-GB Localisation

### ISSUE THREAD

**Issue by BurntNail** [rust-lang/www.rust-lang.org#1936]
### Summary
Hello! There currently exists a wide variety of localisations, but so far none for British English - I'd like to propse the creation of (and probably eventually do the creation of) an en-GB localisation.

### Motivation
I'm a Brit, and I love my language. I get that it's insanely petty, but it'd be nice to see.

### Drawbacks
This will be 99% identical to the en-US localisation, and will be an extra localisation that needs to be kept up-to-date. It also doesn't increase accessibility to a wider number of people or have most of the normal benefits of adding another localisation.

### Rationale and alternatives
The alternative is for me to shut up and deal with it, but I feel that if I don't ask then the answer will always be no - at least there's now a PR with (hopefully coming relatively soon) a definitive answer.

### Maintenance
This isn't super high maintenance (as far as I can tell. please feel free to correct me if i'm being stupid) - as I mentioned, it's almost identical to the en-US localisation, and just another tickbox for content updates. I'm happy to keep maintaining it.

### Unresolved Questions
`-`

**Comment by Manishearth** [comment]
In general we've been having trouble keeping these maintained, and the website team is currently on a skeleton crew so not taking on too much.

Typically for a translation we ask there to be a decently sized group of people committing to keeping these maintained.

Given this, and given that this does not produce a major a11y benefit, I'm reluctant to add this right now.

**Comment by BurntNail** [comment]
In that case, no worries.
