### ISSUE TITLE
Adding korean i18n

### ISSUE THREAD

**Issue by HotoRas** [rust-lang/www.rust-lang.org#1951]
### Summary

We want to add korean translation of the page, since adoption of Rust is becoming the global standards.

### Motivation

We want to introduce Rust into more of our country, Korea, and make it one of the norms of programming.

### Drawbacks

As you know, the translation already exists in the code (check locales/ko), incomplete. But the last pulls from pontoon is already past 3 years- thinking it's nearly dead- and no more indivisual pulls about the language. Maybe it should be done by manually having translated.

### Rationale and alternatives

Right now, koreans who want to learn about Rust will meet English site (of course) and have no choice of selecting Korean (ko) as displaying language. Those who can't understand English will use machine translations to read it, but it's known to mislead when translating from any to Korean.

**Comment by HotoRas** [comment]
### Additional comments

- I started doing this work within [my fork](https://github.com/HotoRas/www.rust-lang.org/tree/l10n/ko). However, since it doesn't have a team rigjt now (so no confirmations have done until now), and it's at the starting phase- not many have done. Making PR from this issue will take time if possible.
- If you need and want to, please contact me to `@ras@hoto.moe` via mastodon.

**Comment by Manishearth** [comment]
To do this you would need to gather a group of people willing to commit to keeping it maintained. I believe pontoon still works it's just that the contributors have become less active.

**Comment by HotoRas** [comment]
OK, closing then.
