### ISSUE TITLE
I'm running on aarch64 Android

### ISSUE THREAD

**Issue by Nomanali3468** [rust-lang/www.rust-lang.org#1956]
It's Showing me
navigator.platform: Linux armv81
navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36
And even I can't install rust on termux

**Comment by Nomanali3468** [comment]
Current installation options:


   default host triple: aarch64-linux-android
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with standard installation (default - just press enter)
2) Customize installation
3) Cancel installation
>

info: profile set to 'default'
info: default host triple is aarch64-linux-android
info: syncing channel updates for 'stable-aarch64-linux-android'
632.6 KiB / 730.9 KiB ( 87 %)   0 B/s in  1s ETA:                                                   730.9 KiB / 730.9 KiB (100 %) 632.6 KiB/s in  1s ETA:  0s
info: latest update on 2024-05-02, rust version 1.78.0 (9b00956e5 2024-04-29)
error: target 'aarch64-linux-android' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets

**Comment by senekor** [comment]
What are you trying to do? Compile Rust code on Android? Following the link at the bottom of your error message, it looks like `aarch64-linux-android` is only supported [without host tools](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2-without-host-tools).

Quoting from the section above that one:

> Tier 2 targets **with host tools** additionally support running tools like rustc and cargo natively on the target

(emphasis mine)

It looks to me like you can't compile Rust code on Adroid.

That being said, this is the repository of the website and not a general support forum. If you have further questions, please take them elsewhere (discord, reddit...)
