### ISSUE TITLE
Docs should recommend using `#rustlang` on other forums when seeking help to maximize discoverability

### ISSUE THREAD

**Issue by heaths** [rust-lang/www.rust-lang.org#1961]
### Summary
On other forums where devs may seek help like Mastodon, it's best to use a distinct hashtag like `#rustlang` instead of `#rust` which tends to get used for other things as well. On pages like https://www.rust-lang.org/community it would be great if this practice were recommended. Perhaps other places as well to be more discoverable to new devs.

### Motivation
Using a distinct hashtag improves discoverability over more general names like "rust".

### Drawbacks
Can't think of any reasons *not* to at least recommend the practice.

### Rationale and alternatives
"rust" is too general and people tend to use it for other things like pictures of rust or the Rust movie or game on social forums.

**Comment by senekor** [comment]
That seems "oddly specific" to me. The community spaces that are mentioned on the website are all about Rust, so there is no risk of confusion.

**Comment by Manishearth** [comment]
I agree. I don't think we need to cover this here.

**Comment by Rodhlann** [comment]
It seems like there are plenty of people discussing rust topics on Mastodon. I'm new to both Rust and Mastodon, but the majority of consistent community involvement I've seen has been on that platform, over Discord, which I also use. 

I don't see why it would hurt to have a section about Mastodon and how to effectively find the community on there, given that seems to be the intent of that page?

**Comment by senekor** [comment]
We have a [code of conduct](https://www.rust-lang.org/policies/code-of-conduct). The community spaces mentioned on the website are ones where this code of conduct is enforced. Mastodon inherently isn't such a space.

**Comment by Rodhlann** [comment]
Perhaps having a tip about what tags to use to effectively find the Rust communities on various well-used social media platforms without specifically calling them out or endorsing them could be a compromise?

As a newcomer to Rust and Rust communities it is helpful to have as much information as possible in finding where the communities congregate and how they prefer to communicate, especially in the context of something that shares it's name with so many other popular products and frequent searches.

**Comment by heaths** [comment]
I wasn’t thinking any mention of Mastodon but just a “best practice“ mention of using that hashtag on any open forum. Even the Twitter community recommended it. Given the linked page states, “Rust’s greatest strength is the community of people who come together to make working in Rust a rewarding experience.” wouldn’t it make sense to suggest it, meeting users where they already are?
