### ISSUE TITLE
Low text contrast causing accessibility issues

### ISSUE THREAD

**Issue by istankovic** [rust-lang/www.rust-lang.org#1976]
### Page(s) Affected
Pages under https://foundation.rust-lang.org/news/, e.g.
 
https://foundation.rust-lang.org/news/announcing-the-first-set-of-rustconf-2024-talks-keynotes/
https://foundation.rust-lang.org/news/welcoming-marketing-program-manager-christina-gorton-to-the-rust-foundation-team/

### What needs to be fixed?
The text contrast on those pages is bad; main content looks readable, but could definitely be improved.
However, some of the (sub)section titles have very low contrast, which makes them very hard to read.  

### Suggested Improvement
Please improve the text contrast on those pages to make the content more accessible.
Checking compliance with Web Content Accessibility Guidelines would also be a great start.

**Comment by Manishearth** [comment]
This repo doesn't handle foundation.rust-lang.org
