### ISSUE TITLE
navigator.platform: Linux armv81 navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36

### ISSUE THREAD

**Issue by Mafiogangsta1** [rust-lang/www.rust-lang.org#2021]
navigator.platform: Linux armv81
navigator.appVersion: 5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36

**Comment by senekor** [comment]
Am I right to assume you opened this issue because of this?

![image](https://github.com/user-attachments/assets/83fa42e0-d507-4c6a-b93c-50a83f4b417a)

It looks like you are running android, which is not supported by rustup afaik.
