### ISSUE TITLE
rustacean.net dead link

### ISSUE THREAD

**Issue by IsaacCloos** [rust-lang/www.rust-lang.org#2023]
### What needs to be fixed?
The [Ferris](https://www.rust-lang.org/learn/get-started#ferris) section includes a link to [additional branding](https://web.archive.org/web/20240726180531/https://rustacean.net/). Currently the site is offline 😢. 

**Note:**
This problem has already been [reported ](https://github.com/aldeka/rustacean.net/issues/26) on that sites repo.

### Page(s) Affected
[learn/get-started](https://www.rust-lang.org/learn/get-started)

### Suggested Improvement
I see there is a [history of outages](https://github.com/rust-lang/www.rust-lang.org/issues?q=is%3Aissue+rustacean.net+is%3Aclosed), and the [repo](https://github.com/aldeka/rustacean.net) is 2 years stale (that's probably a non-factor).

Some ideas:
1. Contact the maintainer, and get the site back up.
2. Rehost the site somewhere more reliably (given the history of availability) 🤷🏻‍♂️.
3. Remove section?? I would much prefer it be revived.

**Comment by senekor** [comment]
I'd wait a little longer before doing anything. Hopefully the problem solves itself.

The repo doesn't have a license, I'm not sure if that would technically be a problem if someone wanted to rehost it.

**Comment by senekor** [comment]
It's back online.
