### ISSUE TITLE
Testimonial logos too large on mobile (/what/wasm)

### ISSUE THREAD

**Issue by Jap2-0** [rust-lang/www.rust-lang.org#2029]
### Page(s) Affected

https://www.rust-lang.org/what/wasm
(templates/components/what/wasm/production.html.hbs)

### What needs to be fixed?

On narrow screens (e.g. mobile), the logos in the "production use" section are very large—for example, on my phone, the Firefox logo takes up nearly half of the screen's height.

![image](https://github.com/user-attachments/assets/5633279f-be0b-4707-b7ce-2769e0f5cb53)

### Suggested Improvement

I'm not sure what the best way to deal with this is (other than, obviously, making the images smaller), but it may also be useful to note that, unlike on desktop/the horizontal layout, in this mobile/narrow/vertical layout, the association between images and testimonial does not appear as clear.  (Also: currently the Firefox logo is a link, and neither of the other two area.)

**Comment by Manishearth** [comment]
Yeah I'd be open to improving this if folks have ideas how best to do it

**Comment by senekor** [comment]
what if we hide the logos completely on mobile? All the quotes have names and links which lead to the websites of the respective organisations, so there wouldn't be any loss of information.

**Comment by Manishearth** [comment]
Probably the simplest route, yeah!
