### ISSUE TITLE
Unrecognized platform

### ISSUE THREAD

**Issue by alphachart** [rust-lang/www.rust-lang.org#2045]
navigator.platform: `Linux armv81`
navigator.appVersion: `5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36`

The website did not recognize the platform I'm on, so I am unable to install rustup.

**Comment by senekor** [comment]
What device are you using? Are you on an Android phone? Why do you want to install rustup on an Android phone?

**Comment by senekor** [comment]
Sorry, there's no Android in your appVersion. Linux on arm should work. Can you install rustup with the normal install command for a unix-like OS?

```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
