### ISSUE TITLE
Playground Communication: timeout

### ISSUE THREAD

**Issue by martinpucala** [rust-lang/www.rust-lang.org#2077]
### What needs to be fixed?

Requests to play.rust-lang.org are  timing out/failing.

### Page(s) Affected

All examples in all sections on https://doc.rust-lang.org/stable/rust-by-example/ that can be run and show results.

### Suggested Improvement

Make the server run again.

**Comment by senekor** [comment]
moved to the playground repo: https://github.com/rust-lang/rust-playground/issues/1109
