### ISSUE TITLE
Some trait methods don't appear in the docs of types that implement the trait

### ISSUE THREAD

**Issue by ahjones** [rust-lang/www.rust-lang.org#2078]
### What needs to be fixed?
Here's a specific example: the doc for Bufreader doesn't include the method `lines` in the Bufreader impl section. Other methods like `has_data_left` are documented. Both `has_data_left` and `lines` are default methods, and yet only one of them is described.

It's causing an issue because I can't find if a method is implemented on a structure by searching through the structure's documentation.

### Page(s) Affected
https://doc.rust-lang.org/std/io/struct.BufReader.html#impl-BufRead-for-BufReader%3CR%3E

I believe I've seen the same issue elsewhere, but I don't have an example to hand right now.

**Comment by Manishearth** [comment]
This is a repository for the main website (not docs), rustdoc bugs are rust-lang/rust.

I suspect this has to do with the Sizes bound.

**Comment by ahjones** [comment]
Created here: https://github.com/rust-lang/rust/issues/131839
