### ISSUE TITLE
Possibly misleading Error Message when trying to modify a immutable variable

### ISSUE THREAD

**Issue by ShivVM** [rust-lang/www.rust-lang.org#2079]
When I compile below code 

fn main() {
	
    let x = "Sai";
    println!("The value of x is: {x}");
    x = 3.142
    println!("The value of x is: {x}");

}

I get below error "
error[E0308]: mismatched types
 --> src/main.rs:7:10
  |
3 |     let x = "Sai";
  |             ----- expected due to this value
4 |     println!("The value of x is: {x}");
6 |      x = 3.142;
  |          ^^^^^ expected `&str`, found floating-point number"

I believe, this error is misleading to the programmer because even &str type value can't be assigned as its immutable variable.
When I change the program as below

fn main() {
	
    let x = "Sai";
    println!("The value of x is: {x}");
    x = "Test";
    println!("The value of x is: {x}");
}

 I get below error

error[E0384]: cannot assign twice to immutable variable `x`
 --> src/main.rs:5:5
  |
3 |     let x = "Sai";
  |         - first assignment to `x`
4 |     println!("The value of x is: {x}");
5 |     x = "Test";
  |     ^^^^^^^^^^ cannot assign twice to immutable variable

I suggest that Error E0384 with text "^^^^^^^^^^ cannot assign twice to immutable variable" should have been reported when I tried to modify x in first program instead of recommending "    ^^^^^ expected `&str`, found floating-point number"

**Comment by senekor** [comment]
First of all, this is the repository of the website. The right place to discuss compiler error messages would be the repo of the compiler: https://github.com/rust-lang/rust

My own opinion on this is that the same argument goes for your suggestion: If the compiler told you to make `x` mutable, it would then complain in a next step that you cannot assign a floating point number to a variable of type `&str`. Fundamentally, the program contains two unrelated errors and which one of them is reported first doesn't really matter in my opinion.

But I'm not on the compiler team. If you want to discuss with people whose opinion on this matters, do go ahead and reopen the issue in the compiler repo.
