### ISSUE TITLE
Typo plus syntax error on matching patterns

### ISSUE THREAD

**Issue by lapinbleu0077** [rust-lang/www.rust-lang.org#2099]
There is a typo and a syntax error for the match code via the page https://doc.rust-lang.org/rust-by-example/flow_control/match.html

I tried following the logic behind the following phrase but the I am still allowed to add the number 13 despite the number 13 already appearing in the following test. The program still compiles with the number 13. 

// TODO ^ Try adding 13 to the list of prime values

There is also an equal symbol just befor the 19. If I remove it or leave it in, the code still compiles. I am not sure if both these issues are linked or not.

My Code : 
`

fn main() {
    let number = 13;
    // TODO ^ Try different values for `number`

    println!("Tell me about {}", number);
    match number {
        // Match a single value
        1 => println!("One!"),
        // Match several values
        2 | 3 | 5 | 7 | 11 | 13 => println!("This is a prime"),
        // TODO ^ Try adding 13 to the list of prime values
        // Match an inclusive range
        13..19 => println!("A teen"),
        // Handle the rest of cases
        _ => println!("Ain't special"),
        // TODO ^ Try commenting out this catch-all arm
    }

}`

Versions
rustc 1.83.0 (90b35a623 2024-11-26)
rust-analyzer 1 (b65911d5ee 2024-11-30)

Page(s) Affected
https://doc.rust-lang.org/rust-by-example/flow_control/match.html

**Comment by senekor** [comment]
This is the repository of the website, the repo for [rust-by-example](https://github.com/rust-lang/rust-by-example) is technically the correct place for this issue.

However, the code on the linked site runs fine and I don't see any typos. So I'm closing instead of transferring.

Feel free to reply with more specifics about what you think is wrong if you disagree.

**Comment by lapinbleu0077** [comment]
Hi, thanks for repying so fast. Actually, the title I wrote was a little misleading. Sorry about that.

The code does compile but the following phrase has one to believe that the following line that includes 13..=19 would give an error and it doesn't. 

// TODO ^ Try adding 13 to the list of prime values

Also, the code compiles without the equal sign or if the equal sign appears in the match between 13 and 19. 

There is no explanation of why these two syntax variations are allowed. 

However, if I were to add a duplicate number on the same line then I'll get an error as expected. 

ex. 

To make it even clearer, the following two examples work : 

```
fn main() {
    let number = 13;

    match number {
        // Match several values
        2 | 3 | 5 | 7 | 11 | 13 => println!("This is a prime"),
        // TODO ^ Try adding 13 to the list of prime values
        // Match an inclusive range
        13..=19 => println!("A teen"),
        // Handle the rest of cases
        _ => println!("Ain't special"),
        // TODO ^ Try commenting out this catch-all arm
    }
}
```

and 

```
fn main() {
    let number = 13;

    match number {
        // Match several values
        2 | 3 | 5 | 7 | 11  => println!("This is a prime"),
        // TODO ^ Try adding 13 to the list of prime values
        // Match an inclusive range
        13..19 => println!("A teen"),
        // Handle the rest of cases
        _ => println!("Ain't special"),
        // TODO ^ Try commenting out this catch-all arm
    }
}
```

**Comment by senekor** [comment]
> the following phrase has one to believe that the following line that includes 13..=19 would give an error and it doesn't.
>
>> // TODO ^ Try adding 13 to the list of prime values

I don't see how this line indicates anything about an expected error. Adding 13 simply changes the output of the program.

> the code compiles without the equal sign or if the equal sign appears in the match between 13 and 19.
>
> There is no explanation of why these two syntax variations are allowed.

`13..19` and `13..=19` is range syntax, which is a different topic. It would be inappropriate to go into detail about that on the page about match statements. Actually, the [preceeding page](https://doc.rust-lang.org/rust-by-example/flow_control/for.html#for-and-range) explains range syntax.

I don't think it would be reasonable to include cross-references to every single aspect of Rust syntax that's used in any of the examples. The examples would get quite noisy.
