### ISSUE TITLE
`prev.rust-lang.org` has no new website banner on translated pages

### ISSUE THREAD

**Issue by Marcono1234** [rust-lang/www.rust-lang.org#2101]
The old website https://prev.rust-lang.org/en-US/ has a "Try out the new site!" banner at the top of the page.
However, for the translated variants such as https://prev.rust-lang.org/de-DE/ don't have this.

This could cause confusion if users open these translated pages and then see outdated information.[^1]

[^1]: I am not completely sure how likely it is that someone lands on the old website. It seems when I restrict Google search results to German language, it finds the old website on the first results page. But I am not sure if users would really restrict the language when searching for Rust.

**Comment by senekor** [comment]
The old website has its own [repo](https://github.com/rust-lang/prev.rust-lang.org), but it's archived.
