### ISSUE TITLE
[qa] Tracking issue: production users/quotes audit

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/www.rust-lang.org#216]
Diff since last review: https://github.com/rust-lang/wubwub/compare/dd18c9ac01904bb1a1fb6d68caafbb5f9831f6f8...master

Homepage:
 - Chucklefish
   - "Rust is one of the few languages that really gives you a large amount of confidence that your parallel and concurrent code is anywhere near correct." - Catherine West, Technical Lead, Chucklefish
   - https://blog.chucklefish.org/about/
   - Logo
   - Status: **requested**

WASM:
 - Dropbox
   - "[Rust’s] properties make it easy to embed the DivANS codec in a webpage with WASM, as shown above." - Daniel Reiter Horn and Jongmin Baek
   - Link: https://blogs.dropbox.com/tech/2018/06/building-better-compression-together-with-divans/ - Building Better Compression Together with DivANS
   - Logo
   - Status: **approved**
 - Firefox/Mozilla
   - "The JavaScript implementation [of the <code>source-map</code> library] has accumulated convoluted code in the name of performance, and we replaced it with idiomatic Rust. Rust does not force us to choose between clearly expressing intent and runtime performance." - Nick Fitzgerald
   - https://hacks.mozilla.org/2018/01/oxidizing-source-maps-with-rust-and-webassembly/ - Oxidizing Source Maps with Rust and WebAssembly
   - Logo
   - Status: **assumed complete**
 - Cloudflare
   - "We can compile Rust to WASM, and call it from Serverless functions woven into the very fabric of the Internet. That's huge and I can't wait to do more of it." - Steven Pack
   - https://blog.cloudflare.com/cloudflare-workers-as-a-serverless-rust-platform/ -                             Serverless Rust with Cloudflare Workers
   - Logo
   - Status: **logo implicit approval (old friends page), others pending**

CLI:
 - Sentry
   - "One of the reasons we liked Rust was the crates.io ecosystem. [...] There is a lot of really good already existing infrastructure for building very nice command-line interfaces." - Armin Ronacher
   - https://www.youtube.com/watch?v=2Xu6EdEBa5E - Watch Armin Ronacher's talk at PolyConf 17
   - Logo
   - Status: **complete** (via CLI WG; production user group also requested this)
- Habitat
  - "I have zero regrets with living in this code base. […] This was sort of an added bonus for me: Using Rust to make CLI or console based tools. It is very good at compiling for different target systems." - Fletcher Nichol
  - https://www.youtube.com/watch?v=zAXbPnfTJg4 - Taking Rust to Production – RustFest Kyiv
  - Logo
  - Status: **complete** (via CLI WG)

Embedded:
 - Cambridge consultants
   - "I was so excited when I came across Rust, from Mozilla. Rust is a new programming language, with the tag line 'safe, fast, concurrent - pick three'. It also has an assured future, with a powerful, committed user community." - Jonathan Pallant, Senior Consultant, Cambridge Consultants
   - Video
   - No logo
   - Status: **complete** (via embedded WG)
 - Sensirion
   - "At Sensirion we recently used Rust to create an embedded demonstrator for Sensirion's <a href="https://sensirion-automotive.com/products#PM2_5">Particulate Matter Sensor</a>. Due to the easy cross-compilation and the availability of many high quality crates on crates.io we quickly ended up with a fast and robust demonstrator." - Raphael Nestler, Software Engineer, Sensirion
   - Logo
   - Status: **complete** (via embedded WG)
 - Airborne Engineering Ltd
   - "At Airborne Engineering Ltd. we recently used Rust to write an Ethernet bootloader, <a href="https://github.com/airborneengineering/blethrs">blethrs</a>, for our in-house data acquisition system. Rust is a promising language and we're excited to use it for our future projects, embedded and otherwise." - Dr. Adam Greig, Instrumentation Engineer, Airborne Engineering Ltd.
   - Logo
   - Status: **complete** (via embedded WG)
 - 49nord
   - "[Rust] enables us to ship software faster and more correct than we thought possible. Thanks to Rust, we can take memory safety for granted, while other benefits of a zero-overhead language with a sophisticated type system help us develop maintainable software.\n\nRust makes our customers happy, as well as our engineers." - Marc Brinkmann, CEO, 49nord
   - Logo
   - Status: **complete** (via embedded WG)
 - Terminal Technologies
   - "We think it's really cool that we can use a modern nice language in the embedded space where usually there's no alternative to C/C++" - Aleksei Arbuzov, Senior Software Engineer, Terminal Technologies
   - Logo
   - Status: **complete** (via embedded WG)

Networking:
  - Mozilla app services
    - Status: **waiting for response** (via networking WG)
  - Bouyant
    - Status: **waiting for response** (via networking WG)
  - 1aim
    - Status: **waiting for response** (via networking WG)

**Comment by nrc** [comment]
@aidanhs is there any more to do here or can this be closed now?

**Comment by skade** [comment]
I'll close this. This seems done. Please reopen otherwise.
