### ISSUE TITLE
Make external links to open in a new tab

### ISSUE THREAD

**Issue by sendilkumarn** [rust-lang/www.rust-lang.org#246]
Currently, all the external links are opening in the same tab. It would be great to open them in the new tabs to avoid any security issues.

P.S. Do we want any visually differentiate the links? I feel it is quite natural to make this links `target=_blank` but open for suggestions

**Comment by amarshall** [comment]
@sendilkumarn Would you mind elaborating what “security issues” arise when opening external links in the same tab?

**Comment by sendilkumarn** [comment]
Maybe this helps https://mathiasbynens.github.io/rel-noopener/

**Comment by amarshall** [comment]
The opener vulnerability is only an issue when a link has a non-empty `target`, as otherwise `window.opener` is always `null`, regardless of `rel=noopener`.
