### ISSUE TITLE
Learn page doesn't link Getting Started page

### ISSUE THREAD

**Issue by killercup** [rust-lang/www.rust-lang.org#285]

**Comment by cdeil** [comment]
I'm new to Rust, landed at https://www.rust-lang.org/learn and since it doesn't link to https://www.rust-lang.org/learn/get-started or https://play.rust-lang.org/ missed those initially.

+1 to add a prominent link to https://www.rust-lang.org/learn/get-started from https://www.rust-lang.org/learn

**Comment by AliSajid** [comment]
This can also be closed since this is fixed on the new website
