### ISSUE TITLE
syntax highlighting for code blocks

### ISSUE THREAD

**Issue by alercah** [rust-lang/www.rust-lang.org#349]
Separately from my comments on #348, the styling makes the Getting Started page really hard to read for me. The thick colour bands are attractive as a marketing thing, or showing off individual features that aren't strongly connected, but I find them extremely disruptive when I'm trying to do a more careful read.

Additionally, there's no syntax highlighting on the code, which really hurts especially given that it's the first code I see coming through the site.

**Comment by andrei-cacio** [comment]
I would like to help with this if there isn't somebody already working on it

**Comment by andrei-cacio** [comment]
Posting some samples here (please ignore the margin issues for now):
What do you think about the background/highlight ratio?

## Sample1
<img width="1003" alt="screenshot 2018-12-02 at 13 39 36" src="https://user-images.githubusercontent.com/5195546/49339262-0490cc80-f638-11e8-80f2-eb135a96c00a.png">

## Sample2
<img width="997" alt="screenshot 2018-12-02 at 13 39 51" src="https://user-images.githubusercontent.com/5195546/49339263-0490cc80-f638-11e8-807c-80afe2b259e3.png">

## Sample3
<img width="1003" alt="screenshot 2018-12-02 at 13 40 07" src="https://user-images.githubusercontent.com/5195546/49339264-0490cc80-f638-11e8-8ad5-cbc3b47491b3.png">

## Sample4
<img width="1001" alt="screenshot 2018-12-02 at 13 40 28" src="https://user-images.githubusercontent.com/5195546/49339265-0490cc80-f638-11e8-8265-685b25456ae4.png">

## Sample5
<img width="991" alt="screenshot 2018-12-02 at 13 40 43" src="https://user-images.githubusercontent.com/5195546/49339266-0490cc80-f638-11e8-8833-1639117d5296.png">

**Comment by rugk** [comment]
Oh that's hard. I guess the black background version has the best contrast (also mind WCAG), but it looks a little too strong compared to the red background. Could not you maybe try another syntax highlighting style (i.e. foreground/text color set)?
Or maybe let the light white background of the original be there…

**Comment by andrei-cacio** [comment]
Yeah, I think it is a good idea to keep the original background. I will try to find a better highlight to match the white background.

**Comment by andrei-cacio** [comment]
For now only this version passes the Accessibility Audit. What do you think?

![image](https://user-images.githubusercontent.com/5195546/49342295-7978fc00-f662-11e8-9fb4-594cb623581d.png)

**Comment by chriskrycho** [comment]
The best/most-likely-to-work thing here is going to be a *white* background, possibly with the Tomorrow theme. We're using white throughout the site, so it shouldn't look weird, and Tomorrow is the current theme used for API docs is either Tomorrow or something very close to it.

**Comment by andrei-cacio** [comment]
I have found a light theme which passes the audit: https://github.com/ericwbailey/a11y-syntax-highlighting

Thoughts?

![image](https://user-images.githubusercontent.com/5195546/49542660-ded92100-f8de-11e8-9226-eca050001137.png)

**Comment by rugk** [comment]
Looks good, IMHO. :smile:

**Comment by andrei-cacio** [comment]
Awesome ! I will prepare a PR then.

**Comment by andrei-cacio** [comment]
With the risk of affecting the general theme, I think that all `<code>` blocks should be moved to the new theme. This way the accessibility support will be improved on the whole website.

An example of plain text with and without the theme: 
![image](https://user-images.githubusercontent.com/5195546/49669680-c72ea380-fa6a-11e8-87b4-0912b43e6ecb.png)

**Comment by Aloso** [comment]
Here's another idea: Give `<code>` and `<pre>` a black, transparent background:

![syntax highlighting](https://user-images.githubusercontent.com/15658558/49690037-9ca41f80-fb2a-11e8-8cff-f5d58df57433.png)

This works very well with the design of the website. However, a dark theme might not look as good in the **white sections**. I have a few ideas for this:

- Use a different, light theme for white sections
- Automatically invert the theme colours in white sections using CSS `filter: invert(1) hue-rotate(180deg)`; this, however, is not supported in IE
- Use a light theme everywhere, as @andrei-cacio suggested
- Give all sections that contain code a white background

**Comment by sondr3** [comment]
As someone who is red-green color blind the `a11y-syntax-highlighting` theme is really hard on my eyes when combined with the background in these examples, the difference to @Aloso's version is night and day.

**Comment by andrei-cacio** [comment]
@Aloso @sondr3 some great feedback ! Thank you !

**Comment by andrei-cacio** [comment]
@Aloso 
> - Use a different, light theme for white sections

Right now only the `a11y` themes seem to be passing the accesibility audit. I couldn't find other themes which performed the same.

**Comment by andrei-cacio** [comment]
@sondr3 would the dark theme be more suitable?

![image](https://user-images.githubusercontent.com/5195546/50108472-fe0c7280-023d-11e9-8010-baccc8322e60.png)

**Comment by sondr3** [comment]
I like the dark one better but am normally a bigger fan of light background. It looks fine in the README, I think you should just be careful not to combine the light theme with a red background.

**Comment by andrei-cacio** [comment]
moving the discussion tot he PR

**Comment by XAMPPRocky** [comment]
This has now been implemented and deployed to rust-lang.org
