### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/www.rust-lang.org#372]
Heroku's hosting [gives us https for the website](https://beta.rust-lang.org/), but it's up to us to redirect to it if accessed over http. We'll need to manually add a redirect from http://beta.rust-lang.org to https://beta.rust-lang.org/ (accounting for other hostnames once we've fully moved!)

This is a pretty minor issue, but just wanted to make sure it was catalogued!

**Comment by nagisa** [comment]
Note, that this is not as trivial as "just" redirecting. There are more considerations to make there… For example, do we want to prevent possibility of MiTM for this redirect (after the very first visit)? In that case HSTS should be set-up as well… however, it should only done if we trust ourselves to correctly manage our certs correctly and never mess up handling them.

**Comment by pietroalbini** [comment]
> In that case HSTS should be set-up as well…

And we can't preload it, since some of our subdomains (like ping.rl.o) don't have support for HTTPS.

**Comment by Darkspirit** [comment]
Please put rust-lang.org and rustup.sh [like Servo](https://www.hardenize.com/report/servo.org#www_hsts) behind Cloudflare. You may configure a Cloudflare origin certificate at Heroku. Benefits:
* HTTP to HTTPS redirect directly made at Cloudflare
* TLS 1.3
* Cloudflare + Firefox = [ESNI](https://blog.cloudflare.com/encrypted-sni/)
* reliable and modern DNSSEC based on ECDSA P-256
* You can still have ping.rust-lang.org. If Cloudflare itself would be down, the Internet would notice.
* You might be even able to compile the website to wasm and run it in a Cloudflare worker.

Please [activate](https://www.hardenize.com/report/sh.rustup.rs#www_hsts) HSTS + preloading for rustup.rs as soon as possible. May I help somehow?

**Comment by coder543** [comment]
I don't understand why the main website needs to have an active backend at all. Why can't it just be hosted directly on a CDN as static HTML/CSS/JS?

**Comment by Coder206** [comment]
I navigated to the HTTP version of the site with Firefox ESR, Firefox Nightly, Chromium (latest for Pop!OS), it redirected to HTTPS automatically.

**Comment by ashleygwilliams** [comment]
great! we can close now :)
