### ISSUE TITLE
The "Getting started" page is confusing

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/www.rust-lang.org#398]
# Content Bug Report
The "Getting Started" page seems to hierarchise the information between rustup and cargo, which is confusing. People need *both* rustup and cargo, or actually they need rustup to get cargo.

How about a script containing all the steps needed to write a program that prints "Hello, world!"?

## Page(s) Affected
Getting Started, as linked from the front page

**Comment by aturon** [comment]
I think this could be helped by grouping the "Cargo" and "Other tools" subsections under a different header: "The Rust toolchain".

Care to make a PR along those lines, and tag me for review?

**Comment by XAMPPRocky** [comment]
Closing this as the current status is unclear.
