### ISSUE TITLE
the formatting of the "Rust in production" section feels jarring to me

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/www.rust-lang.org#400]
Some scattered thoughts:

- The content of that section uses a different font size and layout from the two section that came before it.
- The white background makes it feel like it's not a specific section, unlike the sections around it that have colored backgrounds.
- The layout of the testimonial quotes feels kind of haphazard, but I'm not much of a designer myself, so it's hard for me to be more specific. Also I imagine that part is going to get expanded over time anyway.

The overall effect for me was that I read through two clearly delimited sections ("Why Rust?" and "Build it in Rust"), and then I got to "Rust in production" and assumed I was reading a different type of content that was going to occupy the remainder of the page. But then I got down to "Get Involved" and realized "oh, that white area was also a delimited section."

**Comment by ariasuni** [comment]
Also the section is much bigger than the others, I think we should try to not make it take more than «one screen» (as big or a bit bigger than the «Get Involved» section?)

On mobile:

- the content font is bigger than the header font
![capture d ecran - 2018-11-30 a 04 36 18](https://user-images.githubusercontent.com/2446451/49267239-baea8b00-f459-11e8-9e62-e6ef4a1e8c82.png)
- the logos takes all the place
![capture d ecran - 2018-11-30 a 04 36 41](https://user-images.githubusercontent.com/2446451/49267240-baea8b00-f459-11e8-9b8c-81884ec2c35b.png)

**Comment by skade** [comment]
Closing in favor of #772, I'll nominate that for a full rebuild.
