### ISSUE TITLE
Handle a JSON POST - Missing Angle Brackets

### ISSUE THREAD

**Issue by Mcat12** [rust-lang/www.rust-lang.org#429]
# Content Bug Report

## Page(s) Affected
Networking -> Handle a JSON POST

## What needs to be fixed?
The code snippet's angle bracket sections are missing (see the method signature):
```rust
#[derive(FromForm)]
struct Task { name: String, completed: bool }

#[post("/", data = "")]
fn new(task: Form) -> Flash {
    if task.name.is_empty() {
        Flash::error(Redirect::to("/"),
            "Cannot be empty.")
    } else {
        Flash::success(Redirect::to("/"),
            "Task added.")
    }
}
```

This appears to be taken from the Rocket front page example, which is correct.

## Suggested Improvement
The method signature should be:
```rust
#[post("/", data = "<task>")]
fn new(task: Form<Task>) -> Flash<Redirect>
```

**Comment by ashleygwilliams** [comment]
i would accept a PR to fix this! thanks for filing.

**Comment by Mcat12** [comment]
@ashleygwilliams Is this now unblocked, as the Rocket 0.4 update has been merged?

**Comment by yoshuawuyts** [comment]
@Mcat12 yeah, it's unblocked now. Looks like we're waiting for the PR to be updated https://github.com/rust-lang/www.rust-lang.org/pull/465.
