### ISSUE TITLE
Highlighting 4 working group areas may discourage other use cases

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/www.rust-lang.org#458]
# Content Feature Request
## Summary
Add at least a paragraph explaining that the "Build it with Rust" section of the home page is just a sampling of things that we know work well. In particular, there are great crates for everything from SIMD to graphics. A link to crates.io's categories page might be helpful too.

## Motivation
Highlighting only the four areas with working groups is a great way to help common use cases. However, the fact that no other use cases are mention IMHO implies that you can pretty much only do those 4 things. This is not a message we should convey, I think.

## Drawbacks
More text/clutter on the website, though I think it's worth it.

## Rationale and alternatives
The proposed change is a minimal change to the existing design that should be possible with minimal effort. It's of course possible to not do anything, but that has the stated downsides.

## Maintenance
None necessary.

## Unresolved Questions
None, TMK

**Comment by mark-i-m** [comment]
@aturon Thanks! So I thought about it a bit more, and I think there are actually two related messages we want to convey in this section:

1. Rust is usable for many different types of programs
2. If you are working on one of these 4 areas, we have particularly awesome resources you may want to check out.

I think we probably want to convey these in that order. Perhaps we could do this as follows:

- We split the "Build it in Rust" section into two sub-panels (still within the purple band). The first would be about `crates.io` and the cookbook (which I notice are also missing from the beta home page). Perhaps a short blurb like "crates.io is the Rust community's package repository. There are tons of high-quality crates published that you can use with a one-line edit to your Cargo.toml. Check out the "top crates" and "categories" lists to see the most popular crates. Alternately, checkout the cookbook for some recipes to do common things. <link to crates.io> <link to cookbook>"

- The second subpanel would be the current existing content. I would suggest preceding it with a blurb like "In 2018, the Rust community decided to improve programming experience for a few distinct domains. For these, you can find many high-quality crates _and_ some guides on how to get started."

What do you think?

**Comment by aturon** [comment]
Calling out crates.io is a great idea! For the cookbook, unfortunately it's not yet in a good place for linking to in such a high-profile way. But otherwise, this sounds really good to me.

Do you have time to make a PR? I'd be happy to review!

**Comment by mark-i-m** [comment]
Done :)

#501

**Comment by mark-i-m** [comment]
@ashleygwilliams 

Re: https://github.com/rust-lang/beta.rust-lang.org/pull/501#pullrequestreview-180441720

Could you elaborate on what you felt didn't work?

**Comment by ashleygwilliams** [comment]
hi @mark-i-m - there were a few things including that the crates.io section didn't seem to fit with the build it in rust section. in my head it should perhaps be it's own section (below the build it in rust section or maybe before or after contribute?)

@aturon how do we feel about including crates.io on the main page? i sorta like it but i'm not sure we're running out of space perhaps?

**Comment by aturon** [comment]
Personally, I like the idea of crates.io within "Built it in Rust", in the sense that the section encompasses both specific domains where Rust makes sense, as well as showing off our existing ecosystem that you can build on.

**Comment by ashleygwilliams** [comment]
yeah, in that respect im not against it at all, i‘m just trying to sort how it worls with the four column layout without making the swction too long. do u have thought on how itd look @aturon?

**Comment by skade** [comment]
@mark-i-m Is this still a need?

There might be a chance to roll this together with #351 and #445 come up with a set of suggestions for the frontpage.

**Comment by mark-i-m** [comment]
I'm ok with explicit use cases. I agree with you there. My concern is that it sounds like you should only use it for those use cases.

**Comment by pietroalbini** [comment]
Maybe we should add a fifth "other use cases" section? Dunno how much content we can fill in it though.

**Comment by skade** [comment]
If there is a use-case we want to highlight, I'd make it a full page. We want to avoid bags of info with no goal. Still, some notion of "Rust is used for tons of things, here's a couple of highlights" sounds good,

**Comment by XAMPPRocky** [comment]
I'm going to close this, I agree with @skade, if someone has a specific use case we can discuss that in a seperate. At the very least we should probably have pages for the new working groups.
