### ISSUE TITLE
try to limit contrast in colors

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/www.rust-lang.org#478]
# Design Feature Request

(sorry for both the tone of this issue and for not following the template, the reaction at https://github.com/rust-lang/beta.rust-lang.org/issues/468#issuecomment-443089612 makes me want to not spend a minute more than strictly needed to convey information, given I'm going under the assumption it'll be closed non-sequitur)

Rant about the current site and my inability to actually read the text in a reasonable amount of time is available at https://github.com/rust-lang/beta.rust-lang.org/issues/468#issuecomment-443150282.

Issue: The text is so small and un-contrasted that reading it is hard.

Ideas:
 * Decrease the contrast between background colors compared to the contrast between background and foreground colors
 * Decrease the font size/impact of titles compared to the main text font size/impact

Overall, the proposal in https://github.com/rust-lang/beta.rust-lang.org/issues/468 is, to me, *much* more readable.

**Comment by lbolla** [comment]
There seem to be no semantic associated with colors either. E.g. blue is used in the second banner ("Build it in Rust"), but then the same color is used for buttons in the "Get involved" section. I find it confusing.
Moreover, the same color used for buttons in all sections is used to underline the header, making it look like it's clickable.
Headlines are difficult to read because they are stroke through by those colorful lines.

**Comment by ashleygwilliams** [comment]
We are not currently looking to overhaul the color or font scheme at this time. If you have small actionable tweaks you think we can make to improve this, I encourage you to file other issues.

**Comment by Ekleog** [comment]
@ashleygwilliams What **is** a small actionable tweak? I gave you two. If you don't consider these small actionable tweaks, you may as well say that the design is not up to debate and just close the issue tracker on this repository, as it is effectively useless.

Anyway, looks like I was right to assume it would be closed non-sequitur.

**Comment by e-oz** [comment]
Hope you will excuse my tone as well, but you can use some browser addon/extension to customize CSS of sites you want. I understand black-and-white design is more readable, but really not all sites in the internet should be black and white.

**Comment by e-oz** [comment]
> We are not currently looking to overhaul the color or font scheme at this time.

Is it really "beta"?

**Comment by Ekleog** [comment]
@e-oz This is not about black-and-white design, just about increasing the contrast between (text, background) compared to the contrast between (background1, background2), for the part about the colors.

@ashleygwilliams In case you assumed my point was about black-and-white, like @e-oz appears to have, could you consider reopening it? I really think the tweaks proposed here are minor and actionable, they're basically a minor color shift. If it's not, then I would love to hear what you consider minor and actionable style tweak, because I can't see anything more minor.

**Comment by ashleygwilliams** [comment]
hi @Ekleog ! i had thought so- but i will reopen to discuss just tweaks to some of the colors (bump them slightly darker or light)! sorry about that :)

**Comment by ashleygwilliams** [comment]
@e-oz yes this is a beta- which means we already went through an alpha (all members of any rust team or working group). in the beta we are looking to polish, not do major overhauls. let me know if i can clarify further.

**Comment by e-oz** [comment]
I got it from the first time, no need to aggresive.

**Comment by ashleygwilliams** [comment]
renaming this issue as #524 covers the text size in a bit more detail

**Comment by dogweather** [comment]
> Headlines are difficult to read because they are stroke through by those colorful lines.

:+1:

**Comment by CAD97** [comment]
> Headlines are difficult to read because they are stroke through by those colorful lines.

Minor tweak proposal: align the backstroke such that it lines up with the low upper bound of the letters, rather than being just below it. (I don't know the font setting term, but such that only the risers are off the stroke rather than every character going above it.) This aligns the background line with one that already visually exists -- the top of non-riser characters -- but keeps the distinctive style.

All in all, I like the new design, and realize that taking ideas from the community pushes into "design by committee" rather than the designer who actually designed the site, but this feels like an actionable suggestion that could work to mitigate that concern.

**Comment by stevensonmt** [comment]
> > Headlines are difficult to read because they are stroke through by those colorful lines.
> 
> Minor tweak proposal: align the backstroke such that it lines up with the low upper bound of the letters, rather than being just below it. (I don't know the font setting term, but such that only the risers are off the stroke rather than every character going above it.) This aligns the background line with one that already visually exists -- the top of non-riser characters -- but keeps the distinctive style.

I may be misunderstanding, but my impression of your suggestion is to create a tangent between the background and the text. This would decrease legibility in my opinion. I would suggest either not having lower case break the bounds of the background at all or lowering the background height further to create more distance between the lines of sight. The colors and levels of contrast are a bigger issue with regards to legibility, though.

**Comment by eddyp** [comment]
> reduce the number of colors used, [..] at least to 4.

Looking at the current page, I think eliminating the yellow is easiest, by replacing it with the pink-ish color int the "GET STARTED" background. I think the yellow at the bottom of the page could be replaced either with the green or plain white (since links are underlined, anyway).

**Comment by skade** [comment]
Hm, replacing yellow by pinkish doesn't sound like a good way here. The idea is to always have color triples and the color corresponding going with white background and black text is yellow. It's consistent here, even if the "get started" button is a special element that is not use somewhere else.

(Ignoring the footer)

Given the road this issue has taken (and that it's basically a bit of a proxy issue towards #478) I consider closing it in favour of a more holistic design review.

**Comment by skade** [comment]
Decided to leave this one open instead of other ones on that subject.

**Comment by XAMPPRocky** [comment]
Closing as no longer relevant as the colours have changed.
