### ISSUE TITLE
"POST some JSON" example could show off serde

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/www.rust-lang.org#482]
# Content Feature Request
## Summary
Instead of doing

```rust
let mut map = HashMap::new();
map.insert("lang", "rust");
map.insert("body", "json");
```

The example could try to show off serde by defining a struct similar to this:

```rust
#[derive(Serialize)]
struct Body {
    lang: String,
    body: String,
}
```

## Motivation
Serde is one of Rust's "killer apps": Not having to write (de)serialization code by hand is an amazing feature that I think deserves to be shown prominently on the website.

## Drawbacks
Using `String` for the field types means slightly nontrivial initialization using `"bla".to_string()` or `.into()`. Using `&'a str` means introducing lifetimes very early. Maybe this example should use integers or other types instead?

It makes the example longer: 2 additional lines for the struct definition + 2 when you create the struct inside the `json` method (4-5 if you create it out of line).

## Rationale and alternatives
- Why is this design the best in the space of possible designs?

  It shows how easy serialization is and what a more idiomatic way of performing this request looks like.
  
- What other designs have been considered and what is the rationale for not
  choosing them?

  The current example: `HashMap`s with stringly-typed keys/values are not generally considered best practice, so showing them off on the website might wrongly suggest that they are.

- What is the impact of not doing this?

  Stringly typed `HashMap`s are shown off as idiomatic code while they're generally not.

## Maintenance
Not needed anymore than with the existing example.

## Unresolved Questions
It's unclear which field types to use (see above).

**Comment by aturon** [comment]
This is a good suggestion, thank you!  I do agree with the concerns about owned strings though -- maybe we can workshop something here on this thread? FWIW, I think it's fine for the example to be a bit longer, if that means it does a better job illustrating what's possible with Rust.

**Comment by jonas-schievink** [comment]
How about this?

```rust
// This will POST a body of
//     `{"delete": true, "user": 42}`
#[derive(Serialize)]
struct Body {
    delete: bool,
    user: u32,
}

let client = reqwest::Client::new();
let res = client.post("http://httpbin.org/post")
    .json(&Body {
        delete: true,
        user: 42,
    })
    .send()?;
```

**Comment by jonas-schievink** [comment]
Ah, now it probably shouldn't use `http://httpbin.org` and instead might want to just use `http://example.org`.

**Comment by aturon** [comment]
@jonas-schievink That looks awesome! Want to make a PR?
