### ISSUE TITLE
add "design bug" issue template

### ISSUE THREAD

**Issue by rustonaut** [rust-lang/www.rust-lang.org#488]
# Design Feature Request
## Summary

The lowercase `g` (in `Getting`) overlaps with the `l` (in `development`).

Also the spacing between the sub-headline (mainly the bottom of the
`p`'s in `app`) and the following section with dark background is uncanny
small.

Both spacings should be slightly increased.

---

PS (partially unrelated):
Is there a reason why there is not something like a `design bug` for fixing small issues
like misalignment without fundamentally changing the design? I mean many parts of
the issue template just don't apply to this kind of design bug reports.

**Comment by ashleygwilliams** [comment]
this should have been fixed by reverting an accepted PR in #489 - i think design bug sounds like a great issue template- i would happily accept a PR for that! (you can probably cut and paste a lot to get it.) thanks for filing @rustonaut !
