### ISSUE TITLE
Inconsistent Governance Formatting

### ISSUE THREAD

**Issue by LEARAX** [rust-lang/www.rust-lang.org#499]
# Content Bug Report

## Page(s) Affected

The formatting of the YAML describing the teams found on the Governance page is very inconsistent. [There's also an unescaped "#" character in a chat field.](https://beta.rust-lang.org/governance/teams/crates-io)

## What needs to be fixed?

[Alumni](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/alumni/team.yml#L3):
```yml
description: "enjoying a leisurely retirement"
```
- Unneeded quotations
- Might seem unprofessional

[Community](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/community/team.yml#L3):
```yml
description: coordination and supporting events, content creation, the RustBridge program, and the survey
```
- There should probably be a verb before "the RustBridge program" and "the survey"

[Community/teams/content](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/community/teams/content.yml#L2-L3):
```yml
name: Content Team
description: Helping support community content collection and development.
```
- "Team" is capitalized in name
- Description starts with capital letter
- Terminates with period

[Community/teams/events](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/community/teams/events.yml#L2-L3):
```yml
name: Events Team
description: Supporting community events with knowledge and resources.
```
- "Team" is capitalized in name
- Description starts with capital letter
- Terminates with period

[Community/teams/rustbridge](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/community/teams/rustbridge.yml#L2-L3):
```yml
name: Community Team
description: An inclusive educational initiative focused on bringing underrepresented groups into Rust.
```
- "Team" is capitalized (it is not capitalized in any other root team)
- Description starts with capital letter
- Terminates with period

[Community/teams/survey](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/community/teams/survey.yml#L3):
```yml
description: Running, analysing, and presenting the community survey.
```
- Description starts with capital letter
- Terminates with period

[Core](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/core/team.yml#L3):
```yml
description: Overall direction and policies of the project, subteam leadership, cross-cutting concerns.
```
- Description starts with capital letter
- Terminates with period

[Crates.io](https://github.com/rust-lang/beta.rust-lang.org/blob/fda74914228b4e43082f353d24f31a21a15f9669/src/data/teams/crates-io/team.yml#L4):
```yml
chat: Infra #crates-io channel on Discord
```
- Quotes are needed for chat field (unescaped octothorpe)

I haven't gone through the rest of the teams yet, but there are almost certainly more formatting issues.

**Comment by ashleygwilliams** [comment]
@LEARAX thanks for filing- if you'd like to make a PR to improve the quality of this data that would be greatly appreciated. thank you!

**Comment by skade** [comment]
I did some cleanup over in https://github.com/rust-lang/team/pull/68. Most of the issues were already fixed, I made consistent what I found.

Thanks for the report!
