### ISSUE TITLE
Mention the rust playground on the website

### ISSUE THREAD

**Issue by mattgathu** [rust-lang/www.rust-lang.org#520]
# Content Feature Request
## Summary
The rust playground is not mentioned on the website.

## Motivation
It's a great resource for learning and collaboration.

## Drawbacks
None

## Rationale 
- Adding a link to the playground.

**Comment by ashleygwilliams** [comment]
thanks for this! you are so right, great catch! which page do you think it would work best one? i was thinking maybe learn, tools, or getting started? (or all 3?) let me know what you think!

**Comment by ashleygwilliams** [comment]
the top level nav is already getting quite crowded and i don't think we can devote another top level callout to the playpen. do you have suggestions on including it on some of the pages tho (this is definitely something we should do!)

**Comment by ashleygwilliams** [comment]
as for having it link to example code- the "empty"/bare link to the playpen includes:

```
fn main() {
    println!("{}", "Hello, world!.exe".to_string().slice(-4, 4));
}
```

i think that is generally fine and given how very difficult it is to come up with a snippet, i'd like to keep this issue to just mentioning the playpen- perhaps some places we call out could have a different snippet, but i'd like to keep that as a separate issue for the moment while we decide where to link to it from.

i do think that the code samples that already exist on the site could link to the playpen, and i'm opening another issue for that: https://github.com/rust-lang/beta.rust-lang.org/issues/523
