### ISSUE TITLE
code snippets should link to the play pen

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/www.rust-lang.org#523]
we should link to a prefilled playpen with the code snippets that currently exist:
- [ ] getting-started
- [ ] networking
- [ ] ~~embedded~~ CLI

this may require adding new crates to the playpen cc @carols10cents @shepmaster

**Comment by shepmaster** [comment]
The playpen no longer exists. The Rust playground crates are those that are commonly downloaded or those that have been accepted as part of the [Rust Cookbook](https://rust-lang-nursery.github.io/rust-cookbook/)

**Comment by ashleygwilliams** [comment]
i meant the playground, sorry. what is the process for adding crates to the playground? (i believe the cookbook is no longer maintained, fyi/fwiw)

**Comment by shepmaster** [comment]
> i believe the cookbook is no longer maintained

It's had commits in the last two weeks — does that not count as maintained?

> the process for adding crates to the playground

The reason for choosing the Cookbook is that there's a presumably impartial group of people who have decided that a library is good, maintained, documented, and otherwise should be presented to arbitrary Rust programmers. 

What crates do you need to be added? Why *those* specific crates? What group vouches for those crates?

**Comment by nrc** [comment]
> What crates do you need to be added?

The crates we'd need are 'ferris-says' (for getting started), 'reqwest' and 'rocket' (for networking), 'quicli' and 'structopt' (for CLI)

> Why those specific crates?

They are the ones which are dependencies of the code snippets used on the website.

> What group vouches for those crates?

I guess the website team? Perhaps the individual working groups for the WG snippets

**Comment by ashleygwilliams** [comment]
agree with everything @nrc has said. and i agree with the vouching strategy- the `ferris-says` crate will be vouched for by the "website team" (not yet formed, but i will take point on that) and the crates for the individual working groups pages are vouched for by them.
