### ISSUE TITLE
better align headings and body font size 

### ISSUE THREAD

**Issue by kornelski** [rust-lang/www.rust-lang.org#524]
I find the main text size (starting from "Rust is blazingly fast and memory-efficient…") a little bit too small for comfortable reading. That's usually not a big deal and I enlarge the text in my browser. However, other text on the page, like headers, and especially the "Rust in production" section (starting from "Hundreds of companies around the world are using Rust…) are relatively much much larger. If I zoom in, they become huge to the point of being hard to read because they're too large.

When I enlarge the page to make the smallest body copy comfortable to read:

<img width="377" alt="screenshot 2018-12-02 at 19 20 45" src="https://user-images.githubusercontent.com/72159/49343799-66b4f600-f667-11e8-9aff-26f75a9db083.png">

other text is blown up in size waaay too much:

<img width="519" alt="screenshot 2018-12-02 at 19 21 47" src="https://user-images.githubusercontent.com/72159/49343817-8815e200-f667-11e8-9fae-d81d5e505009.png">

Both screenshots are of the same page at the same zoom level, but they're like from completely different worlds.

To me the page would be more readable if text sizes of different sections and headers were matching more closely.

**Comment by Maxgy** [comment]
The Rust in Production section is especially too large on the mobile site.

**Comment by skade** [comment]
I added the production-section issue as #772.

**Comment by skade** [comment]
Closing in favor of #772
