### ISSUE TITLE
Different line-heights used together

### ISSUE THREAD

**Issue by kornelski** [rust-lang/www.rust-lang.org#525]
The site uses multiple different line-heights (1.2, 1.25, 1.5, 1.6), and the various line-heights aren't merely scaled proportionally to number of words per line. This use that's more stylistic than merely utilitarian seems jarring to me, as the different spacing gives very different feel to various blocks of text, and they IMHO don't fit together.

I find the Rust in production section especially jarring, where large line height in the initial paragraph is followed by a tight one in the quotes:

<img width="631" alt="screenshot 2018-12-02 at 19 33 50" src="https://user-images.githubusercontent.com/72159/49343977-366e5700-f669-11e8-91bc-5f89ee2bb4fc.png">

**Comment by chriskrycho** [comment]
Entirely agreed!

For context, this is largely an artifact of the still-in-progress transition from Skeleton.css (which had some serious problems on smaller screens, and we opted to move away from it) to Tachyons – so there is no consistent relationship between the measure and the leading.

It's on my list of things that needs substantial tightening up across the site as we finish the migration to Tachyons and generally polish things – both before the edition launch and also as part of the polishing effort through the end of the year.

**Comment by skade** [comment]
Closing in favor of #772, I'll nominate that for a full rebuild.
