### ISSUE TITLE
Add margin between build it in rust intro and the domains section

### ISSUE THREAD

**Issue by meven** [rust-lang/www.rust-lang.org#543]
# Design Feature Request
## Summary
On landing page, I think we should add more margin between the phrase after "build it en Rust" and the next section.
![screenshot_20181204_215638](https://user-images.githubusercontent.com/620941/49472378-969efd80-f80f-11e8-9482-d13447554db9.png)

The spacing seems odd, unbalanced.

My proposition would be :

![screenshot_20181204_220122](https://user-images.githubusercontent.com/620941/49472630-38264f00-f810-11e8-9f5c-740319d0f82f.png)

(Adding 25px more to the phrase block margin bottom)

I can volunteer to send a PR.

**Comment by nrc** [comment]
> I can volunteer to send a PR.

Please do!
