### ISSUE TITLE
current stable version should link to blog

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/www.rust-lang.org#557]
I think that the current stable version text under the get started button should link to that version's blog post like in the old website.

**Comment by meven** [comment]
I think this is already in the mind of the Rust core team :
#388

**Comment by ashleygwilliams** [comment]
i agree! it's a bit hard maintenance wise but i'll work with @Mark-Simulacrum to see if we can't figure something out!

@meven it's similar to what #388 says but it goes beyond it, for all releases!

**Comment by Mark-Simulacrum** [comment]
FWIW at this point I think the best solution if we want this is to just edit the code/template manually and re-deploy at release to link the version string to the blog post. From the release team's/my point of view, that's fine, but I can imagine that being something we're hesitant to do right around big publicity

**Comment by nrc** [comment]
IMO, the fewer manual steps for a release the better, and we should avoid doing this if the only way involves a manual step.

**Comment by pietroalbini** [comment]
Fixed by #692
