### ISSUE TITLE
Missing link to this-week-in-rust

### ISSUE THREAD

**Issue by agentsim** [rust-lang/www.rust-lang.org#568]
# Content Feature Request
## Summary
A link to this-week-in-rust from the community page.

## Motivation
This-week-in-rust is a great way to stay up to date with news about Rust, about best practices, interesting projects and crates, and generally a great way to learn about the language. I've found it very valuable.

**Comment by ashleygwilliams** [comment]
i agree! i'm not entirely sure where it would go but i would welcome a PR for this! perhaps the community page?

**Comment by Munkyfoot** [comment]
Link created. PR submitted.

**Comment by Coder206** [comment]
@ashleygwilliams This issue seems to be resolved by #583

**Comment by ashleygwilliams** [comment]
thanks @coder206!
