### ISSUE TITLE
Reduce height of highlight blocks to improve readability of section headers

### ISSUE THREAD

**Issue by stevensonmt** [rust-lang/www.rust-lang.org#575]
# Design Feature Request
## Summary
The current highlight blocks have a height that creates a distracting interruption of the text. Reducing this height still provides the effect of boldly setting of the section headers without increasing the difficulty of visually scanning the text.

## Motivation
Expected outcome is to improve readability of text.

## Drawbacks
Drawbacks are minimal. Would impact the overall extremely bold, blocky design approach to some degree for better or worse.

## Maintenance
Maintenance would be minimal as it should be a single property change in the css for the highlight class.

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?
Scaling back the bold contrast and multiple color scheme would also improve readability and attractiveness, imo, but that is more subjective.

My suggestion below reduces the height from 30px to 24px. I also had to adjust the `top` positioning property slightly.

![scrnshotrustbeta](https://user-images.githubusercontent.com/8891908/49606088-36ab7280-f947-11e8-89fa-465854dcfb1f.png)

**Comment by jthile** [comment]
The readability improvement comes from not slicing through the interior, empty spaces of glyphs, just to put a precise description on the change. The shapes of those spaces are important in recognizing the letters.

**Comment by stevensonmt** [comment]
When putting together the PR I'd like to not introduce other problems/inconsistencies. The positioning of the bottom of the highlight block is a little inconsistent relative to the bottom edge of descender portion of the 'p' in 'production' versus the 'y' in 'Why Rust'. Is there a preference for which spacing to preserve?

**Comment by ashleygwilliams** [comment]
@stevensonmt i don't have strong feelings- i defer to what you'd prefer!
