### ISSUE TITLE
Terms and Policy Links 404 from blog post

### ISSUE THREAD

**Issue by donald-pinckney** [rust-lang/www.rust-lang.org#581]
## Summary
From the Rust 2018 announcement blog post, the Terms and Policy links 404.

### Steps to Reproduce:

1. Visit https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html
2. Go to the bottom of the page, and open any link under “Terms and policies” in the footer. It then 404s.

Note: I can’t reproduce from a non-blog post page.

## Your Environment
Mobile Safari, iPhone 8+, iOS 12.1

**Comment by ashleygwilliams** [comment]
this is a dupe of https://github.com/rust-lang/blog.rust-lang.org/issues/304! thank you! we'll get right on it!
