### ISSUE TITLE
Add autistic.rust-lang.org with less colors

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/www.rust-lang.org#584]
# Design Feature Request
## Summary
One paragraph explanation of the design you'd like to see added.

There should be an autistic.rust-lang.org that's a variant of the main website with a different design, mainly colors.

## Motivation
Why are we doing this? What use cases does it support? What is the expected
outcome?

The current colors are too harsh for autistic ppl.

## Drawbacks
Why should we _not_ do this?

It means having to maintain two designs. I think it's an acceptable tradeoff because you can't please everyone with the same design. It's much better to have many tried and proven designs than to try and come up with something that won't work. Different ppl have different needs, and some of them can conflict with eachother.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?
- What other designs have been considered and what is the rationale for not
  choosing them?
- What is the impact of not doing this?

Uh, I think I accidentally already explained this in the previous section.

## Maintenance
How will this design be maintained? Who will do it?

The same ppl who maintain the current design would maintain the autistic-friendly design.

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?

Maybe themes should be done with javascript rather than separate domains. I don't know.

**Comment by ashleygwilliams** [comment]
Hi @SoniEx2 ! We are only interested in maintaining a single design at this time.
