### ISSUE TITLE
get started button too small and off center

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/www.rust-lang.org#587]
The "Get Started" button seems shrunken and the current stable version link is too large.  Can this be changed?  I have no specifics but the Get Started button being enlarged and centered in the right side of that desktop screen and the version link to be smaller.

![image](https://user-images.githubusercontent.com/19353212/49627467-3a1d1900-f99c-11e8-8882-e3a864b1cb7d.png)

**Comment by ashleygwilliams** [comment]
I agree! I'm not entirely sure how this happened, but it's something I noticed yesterday as well. cc @chriskrycho 

I would happily welcome a PR to fix this!

**Comment by Aloso** [comment]
I don't believe this is an accident. Right now, the "Get started" buttons has the same height and is on the same level as the "Rust" logotype.

**Comment by XAMPPRocky** [comment]
I'm going to close this as it is no longer relevant, the page has since changed.
