### ISSUE TITLE
Some suggestions for localizing new websites(Some lessons learned when localizing old websites)

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/www.rust-lang.org#589]
I have already read [issue 96](https://github.com/rust-lang/www.rust-lang.org/issues/96).

- Translate in sentences and give the English text when the mouse stays on this sentence. 
    -  Some words do not exist in languages such as Chinese, so that translators can only explain the meaning of the original sentence as much as possible.
    - The emotional tendencies expressed in certain sentences may differ in different languages.
    - Helps check for errors in translation.
- If the language has honorific words, use the honorific words first.
- For some languages such as Spanish and French, please unify the gender of the thing before translating.
- Make pages for languages that read from right to left, such as Arabic.

**Comment by renyuneyun** [comment]
Just to dump a bit thoughts: (as the OP of #96 )

It's previously planned to use [fluent](https://projectfluent.org/) to do the i18n (at least before I was focusing on something else). From what I understand, all (except for the last one which I'm not familiar with) can be accomplished with fluent (and also the support of JS (?)).

The misc thing is that fluent-rs (the rust port of fluent) is not yet ready for use (at least from what I see)...

**Comment by skade** [comment]
@3442853561 I'd be interested in starting some editing guidelines for the website. Do you think you could add some of these learnings (and maybe some more) to something like that?

**Comment by 3442853561** [comment]
@skade Thank you for your recognition. I am willing to join!

**Comment by skade** [comment]
@3442853561 the first draft for a translation guideline was merged here, feel free to post PRs to that :).

https://github.com/rust-lang/www.rust-lang.org/blob/master/TRANSLATIONS.md

**Comment by skade** [comment]
Hi, I'll close this issue. @3442853561 - please feel encouraged to open PRs giving your experience to the TRANSLATIONS.md file!
