### ISSUE TITLE
Rust 1.31 / 2018 release noted states clippy, rustfmt and rls are stable, but install instructions don't work on Windows

### ISSUE THREAD

**Issue by eddyp** [rust-lang/www.rust-lang.org#591]
# Content Bug Report
It seems that clippy and rustfmt are still not stable on Windows MSVC, even if the release notes for 1.31/Edition 2018 say they are. Only the -preview flavors are available:

```
C:\Temp\test2018\foo>rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: checking for self-updates

    stable-x86_64-pc-windows-gnu unchanged - rustc 1.31.0 (abe02cefd 2018-12-04)
   stable-x86_64-pc-windows-msvc unchanged - rustc 1.31.0 (abe02cefd 2018-12-04)
  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.32.0-nightly (14997d56a 2018-12-05)


C:\Temp\test2018\foo>rustup component add clippy
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'clippy' for target 'x86_64-pc-windows-msvc'

C:\Temp\test2018\foo>rustup component add rustfmt
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'rustfmt' for target 'x86_64-pc-windows-msvc'

C:\Temp\test2018\foo>rustup component add rls
error: toolchain 'stable-x86_64-pc-windows-msvc' does not contain component 'rls' for target 'x86_64-pc-windows-msvc'

C:\Temp\test2018\foo>rustup component add clippy-preview
info: component 'clippy-preview' for target 'x86_64-pc-windows-msvc' is up to date

C:\Temp\test2018\foo>rustup component add rustfmt-preview
info: component 'rustfmt-preview' for target 'x86_64-pc-windows-msvc' is up to date

C:\Temp\test2018\foo>rustup component add rls-preview
info: component 'rls-preview' for target 'x86_64-pc-windows-msvc' is up to date

```

## Page(s) Affected
https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html
section New tools says:

> [..] a new generation of tools ready for all users: Clippy, Rustfmt, and IDE support.
> 
> Rust's linter, clippy, is now available on stable Rust. You can install it via _rustup component add clippy_
> ...
> You can install with _rustup component add rustfmt_ and use it with cargo fmt

And says nothing about rls, but only about the IDEs.

## What needs to be fixed?
Should at least mention the tools are not yet stable on Windows MSVC(?) and you can use the *-preview flavors instead.

## Suggested Improvement
see above.

**Comment by ashleygwilliams** [comment]
I believe this was a bug with these tools specifically! They are well known and being addressed.

**Comment by steveklabnik** [comment]
Update rustup, uninstall 1.31, and install it again. It should work. If not, please file a bug against rustup.

**Comment by eddyp** [comment]
So on a "from scratch" install it should also work as expected, correct?

**Comment by ashleygwilliams** [comment]
please take this convo to the rustup repo, this is not the correct place to have this conversation.

**Comment by eddyp** [comment]
Just to close things up, things worked after following @steveklabnik 's instructions.
@ashleygwilliams sorry for the noise.
