### ISSUE TITLE
Typo on "Community" page

### ISSUE THREAD

**Issue by TropicSapling** [rust-lang/www.rust-lang.org#600]
# Content Bug Report

## Page(s) Affected
Community

## What needs to be fixed?
The "Increasing Rust's Reach" section says `Increasing Rust’s Reach is a program matches Rust team members [...]` when it should say `Increasing Rust’s Reach is a program that matches Rust team members [...]` (the word `that` is missing and needs to be added)

**Comment by ashleygwilliams** [comment]
great catch! thanks so much for filing! i would happily welcome a PR for this!

**Comment by chriskrycho** [comment]
Resolved by #609.
