### ISSUE TITLE
The Getting started Items of the WASM Page are misaligned 

### ISSUE THREAD

**Issue by andrei-cacio** [rust-lang/www.rust-lang.org#604]
# Content Bug Report

## Page(s) Affected
The [wasm](https://www.rust-lang.org/what/wasm) page

## What needs to be fixed?
There seems to be a miss alignment of the getting started row
![image](https://user-images.githubusercontent.com/5195546/49671164-a61c8180-fa6f-11e8-8978-cf627c59b183.png)

## Suggested Improvement
Fixing the alignment

**Comment by Soria0906** [comment]
All

**Comment by ashleygwilliams** [comment]
i would welcome a PR to fix this! thanks for filing!

**Comment by Coder206** [comment]
@ashleygwilliams I noticed this as well, y investigation concluded that this is due to differences in the sizes of the images, I think flexbox could help with the alignment. Do you have a preference in the method used to solve this?

**Comment by chriskrycho** [comment]
@Coder206 using flex box (with the Tachyons classes to that end) is exactly the desired approach here! A PR to that effect would be great.

**Comment by Coder206** [comment]
I am not familiar with Tachyons, are you referring to http://tachyons.io/?

**Comment by chriskrycho** [comment]
Yep! If you look at the page as implemented currently, you'll see a heavy use of Tachyons, which you can take as an example of how we're currently working.

**Comment by PTrottier** [comment]
I can take a look at this within the next two weeks

**Comment by Coder206** [comment]
I am happy to tackle this, I expect to start working on it within the next two weeks.

**Comment by skade** [comment]
Fixed by skeleton removal, tiny followup here: https://github.com/rust-lang/www.rust-lang.org/issues/830
