### ISSUE TITLE
The link to the homepage is too wide

### ISSUE THREAD

**Issue by Aloso** [rust-lang/www.rust-lang.org#617]
![homepage link](https://user-images.githubusercontent.com/15658558/49688012-1c6ec180-fb0c-11e8-89c1-64af750daf82.png)

When you click on a white area on a website (e.g. to focus the window), you don't expect to open a link.

Suggestion: Wrap the link to the homepage into a `<span>` or `<div>` and make the link only as wide as its text.

This also affects blog.rust-lang.org. Should I file an issue there, too?

**Comment by ashleygwilliams** [comment]
good catch! i would happily accept a PR for this! thanks so much for filing!

**Comment by ashleygwilliams** [comment]
re the blog- once u solve it here i think u can reference this issue and just send a PR to the blog :)

**Comment by Aloso** [comment]
The continuous-integration check failed, and I don't know why. Did I do something wrong?
