### ISSUE TITLE
Any plans to change contributing guidelines to allow design feedback?

### ISSUE THREAD

**Issue by kornelski** [rust-lang/www.rust-lang.org#622]
Currently contributing guidelines state:

> Design and content are complicated thing, and many folks have lots of polarizing feels about it. For the moment, large design changes are made exclusively by the team

(and this is very strictly enforced 😢)

I'm guessing that you don't want to have a design-by-committee, and don't have time to deal with design bikeshedding — especially when you've had Edition 2018 deadline.

But now that the deadline has passed, maybe you would have time to change the way the design is evolved from now on?

Rust-the-language managed to create a structured way to get language design ideas and feedback from the community, and it worked very well. Maybe the website team could also come up with some structured, productive way of working with the community?

**Comment by ashleygwilliams** [comment]
i believe that this will eventually happen, likely as a new team for the website spins up in the upcoming year.

**Comment by kornelski** [comment]
Thanks
