### ISSUE TITLE
White-dark-white section sandwich is easily overlooked

### ISSUE THREAD

**Issue by heftig** [rust-lang/www.rust-lang.org#624]
# Design Bug Report

## Page(s) Affected
- Install
- Community

## What needs to be fixed?
The way the rather short and dark initial section ("rustup" on Install and "TWIR" on Community) is sandwiched between the white header and the next (also white) content section makes my eyes skip right over it to read the black-on-white content, perhaps because it looks like a banner and not like content. This is unfortunate as these sections have the most important content.

The Learn page is similar but the "Get started" section is just tall enough that the content of the "Grow" section is off the screen, so my eyes are drawn back again.

**Comment by ashleygwilliams** [comment]
@heftig thank you for filing! using the colors that currently exist- do you think you could make a suggestion/PR to improve? i'd be happy to look at a PR and/or screencaps to work with you to remedy this!

**Comment by heftig** [comment]
Sorry, I'm not a designer.

**Comment by jacobpledger** [comment]
I had a similar reaction, but as you scroll down the page you realize your mistake and may go back. Therefore I think it's only really an issue at the top of the page, where you're expecting a banner. I think the community page might be more affected by the coloured section not having a header.
Perhaps keep the coloured sections lower on the page?

**Comment by XAMPPRocky** [comment]
I'm going to close this, as this doesn't appear actionable. And at least for the install page this is no longer the case as it now uses white-green-white.
