### ISSUE TITLE
Platform support is not clear on the new site / Where is https://forge.rust-lang.org/platform-support.html ?

### ISSUE THREAD

**Issue by eddyp** [rust-lang/www.rust-lang.org#627]
# Technical Feature Request
## Summary
It is important when choosing a language to check if your targetted platfrom is supported or not.
On the old site, from https://prev.rust-lang.org/en-US/documentation.html, in the **References** section there was a link to https://forge.rust-lang.org/platform-support.html which provided info about platfrom targets, but now this info is not longer visible, at least not from the "Learn" or "Install" sections.

## Motivation
Why are we doing this? What use cases does it support? What is the expected
outcome?

It is important to evaluate easily if an intended platform is supported, without installing first Rust.
On Windows, if you don't want to use MSVC, you need to know the MINGW triple to install rust, otherwise the install will stop ahead of time.

## Drawbacks
Why should we _not_ do this?

I see little downsides, especially since the info should not be linked from the main page, but from some relevant section.
Not sure if the forge.rust-lang.org page is migrated yet, this might be a blocker.

Unfortunately I am unsure whre on the new site would the link fit best since this is not a "Learn"-ing issue, and the "Install" section seems to be focused exclusively on the host system, based on the name.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?

The only alternative is only the link via the old site, which is non-obvious to new commers.

- What other designs have been considered and what is the rationale for not
  choosing them?

Not according to new look.

- What is the impact of not doing this?

People might assume the range of supported platforms is a lot smaller and skip Rust for their new projects. Incorrect evaluation of Rust ecosystem.

## Maintenance
How will this feature be maintained? Who will do it?

(re)Generated based on rustc/cargo output? Site team? 

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?

Updating the actual list/table should be out of scope.
Having a link from the new site to the actual content is the only thing in scope.

**Comment by nrc** [comment]
This should probably be included in Rust's documentation, rather than on the website. I.e., so that after clicking the 'documentation' link at the bottom of the site there is a link from there to the information. If that information exists in the docs (where it can more easily be kept up to date), then we can consider adding a link to it form the 'getting started' section or elsewhere.

If that sounds like a good idea, please file an issue or send a PR to the main Rust repo.
