### ISSUE TITLE
Does the New Site Supports Multiple Languages? Looking for Translators?

### ISSUE THREAD

**Issue by brunoczim** [rust-lang/www.rust-lang.org#629]
# Question

## Question
Does the New Site Supports Multiple Languages? Looking for Translators?

## Context
There is a telegram group I administrate and we use Rust's CoC, but the group is brazilian. Although it sounds weird for programmers, not everybody speaks english well. It would be nice to link a translated CoC. We currently link the old site's CoC, but this is the problem: it is "old". I am sorry, I could not find any button that translates the site to some other language. I would like to help with portuguese, if you are interested.

**Comment by nrc** [comment]
The site does not currently, but I think we intend to in the future. I don't think we are looking for people to translate yet. Thank you for the offer though! Please see https://github.com/rust-lang/www.rust-lang.org/issues/96 for the first step in the process (and probably a good issue to track to find out what is happening here). In the interests of keeping the issue tracker manageable, I'll close this issue in favour of #96.

**Comment by skade** [comment]
@brunoczim We have just merged the initial work for translations and would love a pt-BR translation. A draft of the translations can be found here: https://github.com/rust-lang/www.rust-lang.org/blob/master/TRANSLATIONS.md
