### ISSUE TITLE
Policy page: "no approval" section documents things that require approval

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#638]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/policies/media-guide

## What needs to be fixed?

Under the heading "Uses that do not require explicit approval", there's a section: 

> Using the Rust trademarks (even in modified form) for social events like meetups, tutorials, and the like is allowed for events that are free to attend. For commercial events (including sponsored ones), please check in at trademark@rust-lang.org. **However, the words “RustCamp,” “RustCon” or “RustConf” cannot be used without explicit permission. And, as with all of the above uses, the event cannot appear to be officially endorsed or run by the Rust project without written permission.**

(emphasis mine)

This documents things that require explicit approval.

## Suggested Improvement

We could move down the relevant sentences in the section of disallowed things and optionally add a link to them.

## Sidenote

Also: the current policy, as it stands, includes all Rust conferences in existence. This isn't quite part of this ticket, but I have no idea where to log policy issues.

**Comment by ashleygwilliams** [comment]
re: the Policy question- i'm not entirely sure. cc @rust-lang/core
