### ISSUE TITLE
Old rust install link should redirect to the new one

### ISSUE THREAD

**Issue by bakirov** [rust-lang/www.rust-lang.org#640]
# Content Feature Request
## Summary
Old rust install link (https://www.rust-lang.org/install.html) should redirect to the new install link (https://www.rust-lang.org/tools/install)

## Motivation
Many news, blog posts refer to the old install link and they are now all broken: all requests will fail with 404 error, and that's not a user-friendly as a new site aims to be.

**Comment by joshtriplett** [comment]
Likewise for pages like https://www.rust-lang.org/en-US/team.html

**Comment by skade** [comment]
Both of these are fixed by https://github.com/rust-lang/www.rust-lang.org/pull/597, but not deployed yet.

**Comment by ashleygwilliams** [comment]
closing as this is deploying currently
