### ISSUE TITLE
ping.rust-lang.org still lists website as "beta"

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/www.rust-lang.org#643]
http://ping.rust-lang.org/

We might also want to capitalize the title, i.e., "Rust Website Status", but I don't feel strongly about that at all?

<img width="753" alt="image" src="https://user-images.githubusercontent.com/5047365/49957470-1f2f3500-fec5-11e8-9adf-3dd80e9daf35.png">

**Comment by ashleygwilliams** [comment]
ack- good call! will fix. thanks!

**Comment by ashleygwilliams** [comment]
fixed! thanks again for catching that @Mark-Simulacrum 
<img width="564" alt="screen shot 2018-12-13 at 12 53 41 pm" src="https://user-images.githubusercontent.com/1163554/49957537-27dc3700-fed6-11e8-8547-447c6878b67d.png">
