### ISSUE TITLE
Some redirects are still missing

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/www.rust-lang.org#645]
The old site supported URLS like this:

    https://www.rust-lang.org/install.html

This would redirect to

    https://www.rust-lang.org/en-US/install.html

or whatever it would detect your language was.

See here: https://github.com/rust-lang/prev.rust-lang.org/blob/master/_layouts/redirect.html#L6-L46

The current site does not support these.

**Comment by steveklabnik** [comment]
My understanding was that that was deployed.

**Comment by mbrubeck** [comment]
> My understanding was that that was deployed.

It doesn't appear to be deployed.  None of the redirects it added are working in production.

**Comment by spk** [comment]
The redirect works now https://www.rust-lang.org/install.html this can be closed I think

```
< HTTP/2 308
< content-length: 0
< location: /tools/install
< server: Rocket
< date: Fri, 15 Mar 2019 17:49:39 GMT
```
