### ISSUE TITLE
Buttons on the community page are broken

### ISSUE THREAD

**Issue by spacekookie** [rust-lang/www.rust-lang.org#646]
# Design Bug Report

The buttons in the top section of the community page are misaligned and don't look the way they should.

## Page(s) Affected

- http://rust-lang.org/community

## What needs to be fixed?

Not sure how this should look but I would maybe suggest splitting it out into two columns with the two buttons being side-by-side.

Attaching a screenshot for clarity below

![screenshot from 2018-12-13 23-31-12](https://user-images.githubusercontent.com/7669898/49972263-5f2c0180-ff31-11e8-9cf6-d09157104bd6.png)

**Comment by skade** [comment]
Fixed by #647
