### ISSUE TITLE
"Get involved" boxes should align buttons at 1024px width

### ISSUE THREAD

**Issue by rugk** [rust-lang/www.rust-lang.org#653]
# Design Bug Report

## Page(s) Affected
https://www.rust-lang.org/#read-rust

## What needs to be fixed?
Responsive design

That these buttons (who are black and thus totally highlighted) are not aligned makes it look as if the right block would be "too high", i.e. to much at the top. I get the headlines are aligned, but it still looks like that (on the first look):

![image](https://user-images.githubusercontent.com/11966684/50026938-e1c4c780-ffea-11e8-8e5c-905dc212a340.png)

This only happens when you are around 100px width, in my case 1024px. Note this is a usual size of these smaller, old monitors, so it is not uncommon…

## Suggested Improvement
I'd say you can solve it, if you align the buttons. You can leave some space in the middle, but align the buttons. This is – for most screen widths – also automatically done by the text content, which spans three lines on both sides then:

![image](https://user-images.githubusercontent.com/11966684/50027087-56980180-ffeb-11e8-842c-05f9bbb6f7e4.png)

**Comment by skade** [comment]
There's a couple of issues like this, mostly caused by the half-finished move to a new design system. The main work is finding a page that works and using that structure where it doesn't work.
