### ISSUE TITLE
Chucklefish logo too large

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/www.rust-lang.org#655]
The Chucklefish logo on the main page seems to be just a little too large:

![image](https://user-images.githubusercontent.com/19353212/50046713-fc3b8700-0064-11e9-90dc-4ab66977f6b5.png)

**Comment by mglax** [comment]
Would be cool to make the image responsive too. Here is how it renders on an iPhone 6
![3af29740-c8e0-43f0-9fa7-957141758fb7](https://user-images.githubusercontent.com/44877814/50378812-30054680-063b-11e9-876c-74b1b6f59eac.jpeg)

I think it's a bit too large.

**Comment by Maxgy** [comment]
closing this issue since the Chucklefish logo is no longer present
