### ISSUE TITLE
Missing fonts 

### ISSUE THREAD

**Issue by andrei-cacio** [rust-lang/www.rust-lang.org#657]
# Technical Bug Report
In production there are some missing fonts. It can also be reproduced on local as well.
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | Desktop |
| Browser Type     |Chrome |
| Browser Version  | 70 |

## Is this an issue with Rust, CSS, or HTML (or a combination)?
HTML
## Expected Behavior
There should be no errors in the console

## Step to Reproduce
Open dev tools on production or local dev.

## Screenshots
![image](https://user-images.githubusercontent.com/5195546/50058625-aad5e980-0183-11e9-9f55-98c7120934da.png)

**Comment by mbrubeck** [comment]
Fixed by #626 but not yet deployed.
