### ISSUE TITLE
Too many colours on initial screen

### ISSUE THREAD

**Issue by drahnr** [rust-lang/www.rust-lang.org#661]
# Design Bug Report

## Page(s) Affected
Landing page.

## What needs to be fixed?
Overflow of colours, a feel of unorderedness by the use of too many colours on one page without a clear content relation.

## Suggested Improvement
Make sure at max 3 dominant colours are visibly on a page, unless there is a clear colour to content association.

![toomanycolours](https://user-images.githubusercontent.com/667047/50340112-f1c43600-0519-11e9-9f66-df8d613aec9d.png)

**Comment by skade** [comment]
Should be fixed by removing the edition banner #756
