### ISSUE TITLE
Lets change the subtitle.

### ISSUE THREAD

**Issue by ericfindlay** [rust-lang/www.rust-lang.org#665]
Subtitles are hard to get right. Currently the subtitle is "Empowering everyone
to build reliable and efficient software." I think the reasoning behind this subtitle is to communicate both that

1. Rust is a powerful programming language.
2. The Rust community is very friendly.

I agree that these are the two most important messages, so I agree with
the underlying motivation, but I don't think the implementation/wording works.

#### 'Empower' is politically loaded.

"To empower" is a politically loaded verb. It is often used in the context of
some group 'empowering' some other group. I'll take an example from the
internet,

["Empower women in STEM to close gender gap in Malaysia by 2030"](https://www.techinasia.com/talk/empower-women-stem-close-gender-gap-2030).

The implication is that some group with more power is acting in a way to give
power to another group with less power. Maybe the term is Ok at a political
level but its not good at a personal level. I don't want to be told that I'm
being empowered. My reaction is "I'm not a victim, I can look after myself."
Anyway, the point is that the word is politically loaded, so there must be a
better way to get our message across.

#### Its better not to use currently fashionable words

Empower' is recently a fashionable word in the United States and less so in
English speaking countries outside the U.S. I don't think we should be using
words that a only currently popular because there is an implication that Rust
is for 'cool kids' only.

#### Its better not to use localized words

As mentioned above 'empower' is in common usage in the United States but
less so outside the U.S. So there is a implication that Rust is U.S. centered.
That's true (and not necessarily so bad), but not something the Rust community
wants to project.

#### Its better not to use 'everyone'

This is factually incorrect. Rust does not empower 'everyone' and never will.
Most people aren't interested in programming, let alone Rust, and that's Ok.
There's a subtle, unintended implication that if your not into Rust your not
worthy of being a member even of 'everyone', as in 'everyone knows that!'.

#### The subtitle is ambiguous.

Javascript: "Empowering everyone to build reliable and efficient software."

Haskell: "Empowering everyone to build reliable and efficient software."

PL/2: "Empowering everyone to build reliable and efficient software."

Computer science at MIT: "Empowering everyone to build reliable and efficient software."

Coffee: "Empowering everyone to build reliable and efficient software."

Subscription glasses "Empowering everyone to build reliable and efficient
software."

Meditation: "Empowering everyone to build reliable and efficient
software."

#### Make the 'friendly' message more direct.

If our message is that the Rust community is friend, we shouls be saying
"The Rust community is friendly" and try to give some evidence.

#### Make the 'powerful' message more direct.

If our message is that Rust is powerful, we should be saying "Rust is
powerful" and try to give some evidence.

### Solution

Lets go back to the old subtitle for the moment and discuss a new one.

**Comment by yoshuawuyts** [comment]
@ericfindlay thanks for opening up this issue. This has been discussed several times already, and it's been decided that the subtitle is staying the way it is for now. The team currently doesn't have the bandwidth to reopen the discussion, so we'll be closing this issue for now.

Thanks for your contributions & happy holidays! :sparkles:

**Comment by ericfindlay** [comment]
I found some discussion about this on Discord [here](https://discordapp.com/channels/442252698964721669/448237931136679936/518498086549585920). This matter is important and certainly not bikeshedding and needs to be addressed again in the New Year.

**Comment by ericfindlay** [comment]
"This has been discussed several times already." After searching through Discord there is no evidence for this. I can't find any evidence that there was a discussion at the time the subtitle was added. I am getting a very uneasy feeling about the whole process. If the teach currently doesn't have the bandwidth then why is the website prematurely up?

**Comment by ashleygwilliams** [comment]
https://github.com/rust-lang/www.rust-lang.org/issues/419
