### ISSUE TITLE
Member list for reference team has duplicate members

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#669]
# Content Bug Report

## Page(s) Affected

* [Havvy is listed twice as a reference team member](https://www.rust-lang.org/governance/teams/documentation);

## What needs to be fixed?

N/A

## Suggested Improvement

N/A

**Comment by yoshuawuyts** [comment]
Thanks for reporting! -- duplicate of https://github.com/rust-lang/www.rust-lang.org/issues/659
