### ISSUE TITLE
Compiler&Language workgroups have missing members

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#670]
# Content Bug Report

## Page(s) Affected

* [Many members are not listed for workgroups on the language and compiler page](https://www.rust-lang.org/governance/teams/language-and-compiler) ­– I know for sure that at least codegen has more members than just @nox, and fairly sure same could be said for NLL/Traits/Compiler Performance.

## What needs to be fixed?

N/A

## Suggested Improvement

N/A

**Comment by skade** [comment]
Codegen doesn't seem to exist anymore and I pinged @nikomatsakis about the other groups.

**Comment by nikomatsakis** [comment]
Yeah, so, I raised this issue when the website was first launched. Overall it doesn't really fit the model of working groups in the compiler team, which don't have formal membership typically.

**Comment by nikomatsakis** [comment]
I think what I would like is to have a presentation that lists out the purpose of the working group in a sentence or two, some contact info, and a link to the working group page.

Of course, we could also try to adopt a model with more formal membership, but so far that hasn't ever felt like it works out so well. (That would be a good thing to discuss in #t-compiler/wg-meta on Zulip)

**Comment by nikomatsakis** [comment]
Looking at the current display, it's not *that far* from what I would like. I think my main concern is that the "members" display makes it look like these are all the members, when in fact that set is not well defined. I might prefer if it listed just "lead", but I think I wouldn't object to omitting membership info all together and instead *just* linking to the repository, which includes info on how to get in touch etc.

**Comment by skade** [comment]
I think it's useful to have face and person attached, even if they are just a proxy. Still, that mainly means we need to cover the case where we have teams with no fixed membership, but a contact point is wanted.

**Comment by XAMPPRocky** [comment]
I believe everyone is represented now, and if there are any missing teams they should be added to https://github.com/rust-lang/team instead. If there are teams that are on `team` but not on the website, please file an issue for the relevant teams
