### ISSUE TITLE
Avatars for governance members have style & positioning issues

### ISSUE THREAD

**Issue by nagisa** [rust-lang/www.rust-lang.org#671]
# Design Bug Report

## Page(s) Affected

Specific team pages such as

* https://www.rust-lang.org/governance/teams/dev-tools
* https://www.rust-lang.org/governance/teams/documentation
* https://www.rust-lang.org/governance/teams/library
* https://www.rust-lang.org/governance/teams/operations
* etc...

## What needs to be fixed?

First of all, if the title does not fit in a single line, that single avatar will break the grid and make the whole page look extremely messy. The avatars should be laid out in a nice grid with all avatars being aligned with each other regardless of how titles are laid out. This can be seen on 

Secondly, the first avatar for some reason lacks the margin that is present for all other members, which makes the first row offset to the left compared to the following rows. Remove the `.columns:first-child { margin-left: 0px }` rule.

Thirdly, avatars that are smaller than the grid size look bad. Specific examples are Aaronepower’s small avatar in the [Operations page[(https://www.rust-lang.org/governance/teams/operations). At the very least it should be centered (both vertically and horizontally within its own cell). This is especially notable when in "mobile mode", where more avatars end up not filling the container.

## Suggested Improvement

Use CSS grid with fallbacks to lay out the content here… perhaps?

**Comment by yoshuawuyts** [comment]
> Use CSS grid with fallbacks to lay out the content here… perhaps?

I think we can probably keep using the existing approach to CSS, but we need to make sure the padding works correctly on new rows (and mobile).

**Comment by geminigamers882** [comment]
Hmmm
