### ISSUE TITLE
Getting Started page's instructions to generate new project are incorrect

### ISSUE THREAD

**Issue by yashaslokesh** [rust-lang/www.rust-lang.org#675]
# Content Bug Report

## Page(s) Affected
Getting Started - Generating a new project

## What needs to be fixed?
The website tells readers to use the command 'cargo new hello-rust' to generate a new project, and then lists the files in the generated 'hello-rust' directory. 
When I ran the command on my Mac, a library was created with src/lib.rs, instead of the expected src/main.rs. Subsequently, the 'cargo run' command failed.

## Suggested Improvement
Change the project generation command from 'cargo new hello-rust' to 'cargo new hello-rust --bin'. When I ran the latter command, 'cargo run' worked and 'Hello, world!' was printed in the terminal.

**Comment by steveklabnik** [comment]
What version is your rustc and cargo?

**Comment by yashaslokesh** [comment]
Cargo's version is 0.23.0
Rustc's version is 1.22.1

It seems I had already installed Rust, and the command on the getting started page didn't upgrade my cargo and rustc versions, so that's why I got these problems. Maybe a snippet on updating rustc and cargo should be provided for people who haven't used Rust in a while.
