### ISSUE TITLE
Citizen Code of Conduct Page not loading

### ISSUE THREAD

**Issue by aug2uag** [rust-lang/www.rust-lang.org#683]
# Technical Bug Report
## Your Environment
| Software         | OSX 10.14 |
| ---------------- | ---------- |
| Form Factor      | Laptop |
| Browser Type     | Firefox / Chrome / Safari |
| Browser Version  | 63.0 / 71.0 / 12.0.1 |

## Is this an issue with Rust, CSS, or HTML (or a combination)?
http://citizencodeofconduct.org/ server

## Expected Behavior
Page should load

## Current Behavior
Displays `Error establishing a database connection`

## Step to Reproduce
visit http://citizencodeofconduct.org/

**Comment by yoshuawuyts** [comment]
- [website cached in wayback machine](https://web.archive.org/web/20181116012721/http://citizencodeofconduct.org/)

I've informed the Stumptown Project that the website is down in https://github.com/stumpsyn/policies/issues/23. Fingers crossed it'll be resolved soon!

**Comment by ilyapopov** [comment]
Citizen code of conduct is down again. Maybe rust-lang.org should host a copy of that document?
