### ISSUE TITLE
New site is missing pdfs

### ISSUE THREAD

**Issue by lilyball** [rust-lang/www.rust-lang.org#684]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/pdfs/Rust-Chucklefish-Whitepaper.pdf

## What needs to be fixed?
I don't know how many PDFs were hosted on the old site but there's at least one, https://prev.rust-lang.org/pdfs/Rust-Chucklefish-Whitepaper.pdf, which is a 404 on the new site. I'm also not sure if this was linked from anywhere on the old site (I found the link in a Reddit post).

Either the PDFs should be accessible from the new site, or the new site should redirect to the old for them.

**Comment by yoshuawuyts** [comment]
@kballard Ah yes. Sorry about that! The page for PDFs has moved to [rust-lang.org/production](https://www.rust-lang.org/production). The Chucklefish PDF can now be found [here](https://www.rust-lang.org/production). 

## How to Fix
We should probably redirect `/pdfs` to `/production` so links resolve correctly. And probably also link the old PDF locations to the new PDF locations.
