### ISSUE TITLE
CoC Mod Team link relies on anchor from old site

### ISSUE THREAD

**Issue by khionu** [rust-lang/www.rust-lang.org#685]
# Design Bug Report

## Page(s) Affected
https://www.rust-lang.org/policies/code-of-conduct#moderation

## What needs to be fixed?
The "Rust moderation team" link uses a link with a broken anchor

## Suggested Improvement
Link directly to the Moderation Team page

**Comment by yoshuawuyts** [comment]
@khionu thanks for reporting! Looks like the teams pages are missing IDs for their entries which makes it impossible to jump to them.

**Comment by khionu** [comment]
Since the Team Pages are separate from the list of Teams, I would suggest linking directly to the Mod Team Page. Jumping to a div that's a square in a row is less obvious than jumping to the dedicated page.

**Comment by yoshuawuyts** [comment]
@khionu ah yes, that makes a lot of sense! Would you like to make a PR for this?

**Comment by khionu** [comment]
Umm, sure. Give me 10 min.
