### ISSUE TITLE
Installer for Windows may be stuck at version 1.22.1

### ISSUE THREAD

**Issue by kornelski** [rust-lang/www.rust-lang.org#687]
I've got a report from a user that the installer they've got from the site was 1.22.1 instead of the latest version. I can't verify this myself, since I'm not on Windows.

> Strange, the installer for Windows ([downloaded from here](https://www.rust-lang.org/tools/install)) installs 1.22.1, but by running `rustup update` it reaches 1.31.1

**Comment by yoshuawuyts** [comment]
Ah dang, I also don't have a Windows machine. I can swear there's a way to spoof user agents to make it seem like a request comes from Windows but I forgot how to do it.

The source for the user-agent detection code can be found [here](https://github.com/rust-lang/www.rust-lang.org/blob/master/templates/components/tools/install-script.hbs). Perhaps we can spot the bug by hand?

**Comment by yoshuawuyts** [comment]
Hmmm, people on windows would see [these instructions](https://github.com/rust-lang/www.rust-lang.org/blob/7b164222f5d3ecc87a9eda6b8f6e03da3d9d7b85/templates/components/tools/rustup.hbs#L6-L13):
```html
 <div id="platform-instructions-win" class="instructions" style="display: none;">
    <p>It looks like you’re running Windows. To install Rust, download and run</p>
    <a href="https://win.rustup.rs" class="button button-secondary">rustup‑init.exe</a>
    <p>...then follow the onscreen instructions.</p>
    <p><b>Windows Subsystem for Linux</b></p>
    <p>If you’re a Windows Subsystem for Linux user run the following in your terminal, then follow the on-screen instructions to install Rust.</p>
    <pre><code>curl https://sh.rustup.rs -sSf | sh</code></pre>
</div>
```
This would seem to be an issue with https://win.rustup.rs, and not with this repo. @kornelski would you mind opening an issue on the rustup (windows) repo?
