### ISSUE TITLE
"Other Installation Methods" out of date

### ISSUE THREAD

**Issue by njaard** [rust-lang/www.rust-lang.org#688]
# Content Bug Report

## Page(s) Affected

The links on https://forge.rust-lang.org/other-installation-methods.html#standalone only show downloads for the 1.31.0 release.

## What needs to be fixed?
It should always be updated at the same time as the front page gets updated to show the latest release.

**Comment by yoshuawuyts** [comment]
@njaard thanks for reporting! That definitely sounds like a bug. Unfortunately this repository does not include the Rust Lang forge, so I've gone and opened an issue on the forge repo. https://github.com/rust-lang/rust-forge/issues/191

Crossing fingers this can be resolved soon!
