### ISSUE TITLE
Duplicate collection of documentation links

### ISSUE THREAD

**Issue by siddharthasahu** [rust-lang/www.rust-lang.org#696]
Hi,

Now that we have https://www.rust-lang.org/learn, I think https://doc.rust-lang.org should be redirected to the new page.

Also, the edition-guide (https://doc.rust-lang.org/edition-guide) link is missing from both of these places.

**Comment by siddharthasahu** [comment]
Well, doc.rust-lang.org is also the one available locally with rustup. I suppose the web version could be special cased and redirected.

I'll let this remain open for comments, but the issue can be closed now.

**Comment by yoshuawuyts** [comment]
cc/ @steveklabnik do you have any thoughts on this?

**Comment by steveklabnik** [comment]
The second one is a different bug that has a PR attached.

I am not totally opposed; we still need the page to *exist*, as it's what exists locally, but redirecting from doc.rust-lang.org to rust-lang.org/learn makes sense, I think. That work wouldn't be done in this repository; I think @rust-lang/infra would need to get involved?

**Comment by skade** [comment]
I'll check up with infra on this.

**Comment by pietroalbini** [comment]
By the way it's easy to add this kind of redirects: all of the doc.rust-lang.org requests already go through a Lambda@Edge for routing, and this would just be yet another `if`.

**Comment by pietroalbini** [comment]
If y'all want to try this I can setup the redirect on https://dev-doc.rust-lang.org.

**Comment by skade** [comment]
Okay, I'd love to have this redirect. The side-issue of the edition guide not being linked is fixed. I'll change this into two different issues.

**Comment by skade** [comment]
Closed in favor of the linked issues. The edition guide problem is fixed. Thanks for the report @siddharthasahu .
