### ISSUE TITLE
link to eclipse IDE out of date

### ISSUE THREAD

**Issue by rimathia** [rust-lang/www.rust-lang.org#703]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/tools

## What needs to be fixed?
the link for Eclipse points to
https://www.eclipse.org/downloads/packages/release/photon/r/eclipse-ide-rust-developers-includes-incubating-components
which has a header:
This package was released on 06/27/2018. A newer package is available here.

## Suggested Improvement
make the link point to the latest Eclipse version for which it is available:
https://www.eclipse.org/downloads/packages/release/2018-09/r/eclipse-ide-rust-developers-includes-incubating-components

**Comment by rimathia** [comment]
Since this is a very simple suggestion I have made a pull request as well:
https://github.com/rust-lang/www.rust-lang.org/pull/704

**Comment by yoshuawuyts** [comment]
Closed by #704. Thanks!
