### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang/www.rust-lang.org#707]
I just wanted to let you know that we are translating the contents into Japanese. Since we do not know yet how the i18n/l10n method goes, we are currently keeping out translations under ja-JP directory of our fork: https://github.com/rust-lang-ja/www.rust-lang.org/tree/japanese/ja-JP/

Please keep this issue open to avoid somebody duplicates our efforts. Thanks!

**Comment by yoshuawuyts** [comment]
@tatsuya6502 this is fantastic, thanks so much!

Re: i18n/l10n -- as far as I know there hasn't been much talk about this yet; if you have any preferences on how we could integrate translations into the website, input would be very welcome!

**Comment by skade** [comment]
Hi @tatsuya6502. The translation method will probably be pontoon/fluent-rs, mostly because of having organisational knowledge and support close.

@renyuneyun is currently working on an integration and I'd be happy to help to have this take off!

**Comment by skade** [comment]
@tatsuya6502 the basics for i18n is merged and we'd be happy to start integrating :).

**Comment by skade** [comment]
@tatsuya6502 Please see https://github.com/rust-lang/www.rust-lang.org/blob/master/TRANSLATIONS.md for informations on how to get a translation team registered and your translations transferred to the page.

**Comment by tatsuya6502** [comment]
@skade Thank you for integrating pontoon/fluent-rs to Rust website. I followed the information on the guideline and sent an email with a list of the initial team members. Please check the email and create our team on pontoon. Thanks!

**Comment by Manishearth** [comment]
Your team has already been created, it seems. You're marked as the manager for the japanese locale. Feel free to make other people managers.

As a manager all your edits get automatically approved, please make sure you click the gear in the translations interface and enable suggestions mode before adding translations.

**Comment by tatsuya6502** [comment]
Thank you for checking about my team.

> As a manager all your edits get automatically approved, please make sure you click the gear in the translations interface and enable suggestions mode before adding translations.

Thanks for the heads up. We will try to remember to enable suggestions mode.

**Comment by skade** [comment]
I'll close this issue here, thank you all for being on board! \o/
