### ISSUE TITLE
Please do not use gray fonts!

### ISSUE THREAD

**Issue by jayeye** [rust-lang/www.rust-lang.org#710]
# Design Feature Request
## Summary
I tried reading the various documentation pages. What is the point of having gray fonts on a white background? What's wrong with black fonts on a white background? The other "themes" with the colored fonts are even worse!

**Comment by yoshuawuyts** [comment]
@jayeye thanks for the feedback! Examples of where this is happening would be very helpful.

**Comment by skade** [comment]
Superseded by https://github.com/rust-lang/www.rust-lang.org/issues/758
