### ISSUE TITLE
Update governance core team to reflect core team

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/www.rust-lang.org#714]
# Content Bug Report

## Page(s) Affected
Core team page in governance

## What needs to be fixed?
This isn't in sync with https://blog.rust-lang.org/2019/02/22/Core-team-changes.html - namely nrc is listed as having left the core team but is still on the governance page

## Suggested Improvement
Remove nrc from governance core team page :(

**Comment by yoshuawuyts** [comment]
I believe all that's needed is to update is the core team listing in https://github.com/rust-lang/team.

**Comment by skade** [comment]
Thanks for mentioning that!

NRC is currently still taking part in core team meetings and is active at giving valuable feedback. We'll update the page once the announced move of not participating actually happens.
