### ISSUE TITLE
Rust Security Team public key link is inaccessible

### ISSUE THREAD

**Issue by jens1o** [rust-lang/www.rust-lang.org#715]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/policies/security

## What needs to be fixed?
The second paragraph links to a public key security researchers are able to encrypt their emails with. 

## Suggested Improvement
We could simply add a text version of the public key given below, or make an anchor to it. (Although personally I'd prefer having a new tab open with the plain key).

**Comment by yoshuawuyts** [comment]
@jens1o could you say more about what's motivating your suggestion?

**Comment by jens1o** [comment]
I wanted to know how I report security issues, finding that the link is no longer accessible?

Sorry, but I'm not really sure where exactly I should elaborate on.

**Comment by steveklabnik** [comment]
The plaintext version of the key is at the bottom of the page, right?

And yeah, that link does 404 so we should fix it.

**Comment by jens1o** [comment]
> The plaintext version of the key is at the bottom of the page, right?

Yeah, there is. I just wanted to say that. I didn't know how this is an suggestion. Just restoring intended behavior.
