### ISSUE TITLE
Remove Chucklefish Whitepaper

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/www.rust-lang.org#720]
# Content Bug Report

## Page(s) Affected
Chucklefish is not using Rust in Witchbrook anymore, after Catherine West left. 

Source(s):
https://www.reddit.com/r/programming/comments/atyzz4/halley_a_lightweight_game_engine_written_in_c14/eh69lz7/

https://www.reddit.com/r/rust/comments/avwxq1/chucklefish_is_no_longer_using_rust_for_witchbrook/ehijdwx/

## What needs to be fixed?
Remove the Chucklefish PDF and possibly the quote related to Chucklefish.

**Comment by josh-kean** [comment]
hi jonathandturner, I found the page that Chucklefish is mentioned on, and I think I can effectivley remove it. Mind if I take a crack at this?

**Comment by lzutao** [comment]
@josh-kean You're welcome to do that.

**Comment by skade** [comment]
Hm, there's a PR for that, which was closed.
