### ISSUE TITLE
Are there any solutions to view other platform installation page?

### ISSUE THREAD

**Issue by lzutao** [rust-lang/www.rust-lang.org#726]
# Question

## Question

This maybe related to #423.

I'm trying to find a link that talk about **two different toolchains** on 
Windows (see [rust-lang/rustup.rs#1707#discussion_r264291131](https://github.com/rust-lang/rustup.rs/pull/1707#discussion_r264291131)). 
The old link https://www.rust-lang.org/downloads.html#win-foot is no longer exists.

Can I view other platform's installation page (https://www.rust-lang.org/tools/install) 
with a URL HTML marker (`#platform-win`) or URL GET paramenter (`?platform=windows`) ?

## Context

I'm using Ubuntu and I want to view Windows installation page.

After skimming through install page of r-l.o code, it seems like `platform-button` 
[is not used in `install-script.js`](
https://github.com/rust-lang/www.rust-lang.org/blob/master/templates/components/tools/install-script.hbs#L114-L141).

**Comment by yoshuawuyts** [comment]
@lzutao what screen are you referring to? Is that https://www.rust-lang.org/learn/get-started ?

**Comment by lzutao** [comment]
@yoshuawuyts Sorry for ambiguous. I've updated the issue with more context.

**Comment by yoshuawuyts** [comment]
@lzutao hah, yeah this has annoyed me before too. I think having a query string indeed makes for a reasonable (interim) solution that can be added without too much trouble. Would you be willing to write a patch to add it?

**Comment by lzutao** [comment]
@yoshuawuyts kinnison has written a patch for this issue. Feel free to take a look at it.
