### ISSUE TITLE
Windows installation instructions

### ISSUE THREAD

**Issue by dcarosone** [rust-lang/www.rust-lang.org#733]
# Content Bug Report

## Page(s) Affected
Getting started / installation 

~https://www.rust-lang.org/learn/get-started~
https://www.rust-lang.org/tools/install

## What needs to be fixed?

I wanted to look at the instructions for installing on Windows the other day, because i remembered that there were a bunch of extra steps and dependencies. I don't normally use windows, but I was curious about the viability of installing it on a customer workstation for a quick task.

So I went to the website, but I couldn't even *see* the Windows install instructions unless I changed my user-agent string to pretend to be on Windows.  And even then, all I was told was "get rustup-init.exe and follow the on-screen instructions".

I just want to review those instructions!

Following through a series of "learn more" type links led me on a path through these pages, neither of which contained the information needed.
* https://www.rust-lang.org/tools/install
* https://forge.rust-lang.org/other-installation-methods.html

I'm sure this used to be visible previously.
**Edit**: it's in the install page, but hidden for non-windows users, with no noticable way of exposing it.

## Suggested Improvement

Provide users a way to view instructions for platforms other than what's auto-detected, maybe via an expanding section or tabbed panel (have the detection pick the relevant tab, rather than completely hide other content). Or just don't hide this paragraph for anyone.

~Provide detail about platform steps and additional dependencies in the online installation instructions, rather than (only) in the installation tool.~

**Comment by steveklabnik** [comment]
Here's the old page: https://prev.rust-lang.org/en-US/install.html

I think that everything that used to be visible is the exact same on the new page.

**Comment by dcarosone** [comment]
Thanks, this (and the link to the additional detail) was precisely what I remembered and was looking for:

![image](https://user-images.githubusercontent.com/11495017/55199353-b9d02d00-51b1-11e9-9d47-a223f1960267.png)

It's not in the main page. It turns out, it *is* in the second page (tools/install) behind the "learn more" banner link, *when I come from a browser on Windows*.  It's there in the source, with some class and style stuff to hide it - apparently my user-agent tricks didn't work well enough.

So, the request reduces to the first part: being able to find this information from other platforms: something that can be collapsed by default but visible and expanded if you want. 

We (effectively) show the linux instructions to Windows users for WSL anyway, so there might be some nice way to generalise this selection/navigation.

**Comment by dcarosone** [comment]
(or, frankly, since it's only a heading and single paragraph, already behind a would-you-like-to-know-more? link, just don't hide this at all)

**Comment by steveklabnik** [comment]
> It turns out, it is in the second page (tools/install)

Ah ha, I think that's some of the issue here too; I thought you were talking about the install page, not the main page.

**Comment by dcarosone** [comment]
I was looking in the "getting started" page, where (navigationally) it used to be. The old site didn't have the extra first step; a "getting started" link on the homepage went directly to the "install" page you linked to with the content in question. 

I didn't find it, either there or in the series of "more info" pages. I didn't remember what I was looking for clearly enough to notice that the text on the install page was identical to what used to be *next to* what I was looking for.

I don't really mind whether we consider the insertion of an earlier page as having moved content or not; now that you've helped find it, I'm fine with where it is - just not with it being completely invisible. I'll amend the report above to refer to the install page.
