### ISSUE TITLE
Replace Fira with FiraGO

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#755]
# Design Feature Request
## Summary
FiraGo is an extended version Fira with better support for non-latin fonts.

## Motivation
This might help in i18n efforts.

## Drawbacks
Potentially increased font file size.

**Comment by skade** [comment]
Confirmed: Fira doesn't render characters necessary for the Turkish translation.

**Comment by skade** [comment]
Wrong, Fira renders correctly, our headlines are in Alfa Sans, see #858

**Comment by XAMPPRocky** [comment]
Closing as a duplicate of #867
