### ISSUE TITLE
Change redirect implementation

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#767]
# Technical Feature Request
## Summary
Redirection is currently a simple match table from filename to filename. It would be better to configure them through a configuration file that goes (regex) -> (replacement).

This file could also act as a history of past redirects.

## Motivation
The current redirect systems is a set of functions together with a match table for the `<dest>` parameter. That has multiple drawbacks, including the necessity to have multiple redirect functions.

**Comment by dzhibas** [comment]
@skade @XAMPPRocky  what do you guys think of this proposal: https://github.com/rust-lang/www.rust-lang.org/pull/1304/files
