### ISSUE TITLE
More automated conference page that includes upcoming and past events

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/www.rust-lang.org#777]
# Content Feature Request
## Summary

Right now, https://www.rust-lang.org/community links to https://blog.rust-lang.org/2018/01/31/The-2018-Rust-Event-Lineup.html. I'm about to write a blog post like this for 2019. For the long term though, and as more Rust conferences form (🤞), it'd be nicer to have a way that conference organizers could submit their event info and we have a page that shows a section of upcoming events when the conference's date is in the future, and a section of past events when the conference's date has passed.

## Motivation

We would be doing this to promote conferences for attendees, speakers, and sponsors. It would let us always have an up-to-date list on the site. It would also let folks find content from previous events.

## Drawbacks

The page might get long and unwieldy, we might need to split it into multiple pages by years or by continent or something.

These events might appear more official than we want them to be, but we can make sure the page says "community conferences" or similar to try and make that clearer.

## Rationale and alternatives

We could keep doing a yearly blog post like what we did last year and what i'm about to do this year, but that relies on someone remembering to do it. I'm proposing we switch to a model where conferences tell us about their event, rather than us reaching out to conferences.

## Maintenance

Conference organizers will submit pull requests for their event and edit details like links to videos after the vent occurs.

**Comment by skade** [comment]
Hi, I'd like to note down the current line of thinking behind the current implementation. There's two points:

The website avoids having any dynamic elements that need constant editorial oversight, also to make sure that it can be well internationalised.

The second is the editorial concern concerning which conferences are featured and which not.

The current situation shows though that the current iteration already needs that work, so if both points are somewhat addressed, I'd be happy to have that.

**Comment by XAMPPRocky** [comment]
I'm going to close this as their is now https://timetill.rs which has this functionality, is being maintained (admittedly by me), and we link to it on the Rust website. In the future we could integrate it into the Rust site directly.
