### ISSUE TITLE
Typo in chapter 12 of the rust book.

### ISSUE THREAD

**Issue by josephleblanc** [rust-lang/www.rust-lang.org#779]
# Content Bug Report

## Page(s) Affected
https://doc.rust-lang.org/stable/book/ch12-01-accepting-command-line-arguments.html

## What needs to be fixed?
Under the section "Reading the Argument Values" there is a formatting error. The first paragraph of this section ends with "We’ll cover iterators fully in Chapter", followed by a new line and then an indented number point, "13. For now, you only need to know..."

## Suggested Improvement
My guess is that this is supposed to read, "We'll cover iterators fully in Chapter 13. For now, you only need to know...".

**Comment by tshepang** [comment]
This is fixed in the [beta version of the docs](https://doc.rust-lang.org/beta/book/ch12-01-accepting-command-line-arguments.html). Beta will be promoted to stable on Thursday, so the link you gave will have a fixed version then.

**Comment by skade** [comment]
The book is not part of the website (project-wise), bugs must be reported to https://github.com/rust-lang/rust.

Thanks for reporting and thanks @tshepang for checking for the fix!
