### ISSUE TITLE
Frontend cleanup: Remove Skeleton

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#780]
Supersedes #183 

The Rust website currently uses two CSS frameworks: Skeleton and Tachyons (http://tachyons.io/docs/layout/flexbox/). This is due to an unfinished migration. This unfinished migration is a blocker for further extensions of the website.

We'd like to completely move over to Tachyons. There's two wishes here:

* We should avoid tachyons _grid_ and instead us its flexbox classes: http://tachyons.io/docs/layout/flexbox/
* If possible, elements of similar shape should use the same code.

It's easy to help out! Here are some instructions:

* Check out the website
* Pick _one_ of the subpages
* Post here that you care for that subpage. You will have 7 days to post a PR (otherwise, we'll ping you)
* (optional) join https://discord.gg/rust-lang and go to #website if you need help or feedback.
* remove skeletons from the page: https://github.com/rust-lang/www.rust-lang.org/pull/774/files
* Fix what's broken, using Tachyons or custom CSS. Also try to thoroughly remove now unused CSS classes.
* Optional: check this bugtracker for issues concerning you page and try to fix them on the go

Handy page list for everyone to check:

| URL                         | Page Name       | Assigned   | Fixed
| ---                         | ---             | ---        | ---
| `/`                         | Index           |  @dzhibas         | yes
| `/install`                | Install           | @andirotter | yes
| `/learn`                    | Learn           | @Pjb518             |  yes
| `/tools`                    | Tools           | @dzhibas           |  yes
| `/governance`               | Governance      |   @dzhibas         | yes
| `/community`                | Community       | @yayoc           |  yes
| `/what`                     | What            |  @skade          |  yes
| `/what/cli`                 | CLI             |  @skade      |  
| `/what/embedded`            | Embedded        |  @skade           |  
| `/what/wasm`                | WASM            |   @skade          |  
| `/what/networking`          | Server          |  @dzhibas           |  yes
| `/what/production`          | Production      |   @dzhibas       | yes
| `/policies`                 | Policies        |     @chriskrycho       | yes
| `/policies/media-guide`     | Media Guide     |   @chriskrycho         | yes
| `/policies/security`        | Security        |   @chriskrycho         | yes
| `/policies/license`         | License         |     @chriskrycho      |  yes
| `/policies/code-of-conduct` | Code of Conduct |  @chriskrycho          |  yes

**Comment by andirotter** [comment]
Hey there, 

i will start with the "Install" subpage. Also heading over to the discord chat for questions that might arose.

**Comment by Pjb518** [comment]
Hey,

I've actually almost completed the Learn page. This includes a lot of site-wide styles, such as the headers and the footer code.

**Comment by skade** [comment]
Thanks! @Pjb518 and @andirotter!

**Comment by wizofe** [comment]
I can get the `what/embedded` page :)

**Comment by skade** [comment]
@wizofe go ahead. Note that @Pjb518 got header and footer ported, no need to invest time there!

**Comment by eatrero** [comment]
Hi, I can help out on the `/policies` page

**Comment by Pjb518** [comment]
> @wizofe go ahead. Note that @Pjb518 got header and footer ported, no need to invest time there!

The section headings and global font size has also already been taken care of, so most of the changes now should be layout issues.

**Comment by yayoc** [comment]
Hi, I can get `/community` page.

**Comment by skade** [comment]
@yayoc yay! :tada:

**Comment by dzhibas** [comment]
`/tools` PR https://github.com/rust-lang/www.rust-lang.org/pull/787

**Comment by dzhibas** [comment]
`404 NotFound` template fix https://github.com/dzhibas/www.rust-lang.org/pull/new/780-get-rid-of-skeleton-404

**Comment by skade** [comment]
@dzhibas Indeed, the /contribute page doesn't exist anymore (I thought I caught all of them when I copied the list)

**Comment by lwshang** [comment]
I suggest to have some extra columns in the table which show the current status (like `Open`, `In Development`, `Done`) of a page and maybe who contributed to or is working on that page. That will make it easy to track the progress.

**Comment by dzhibas** [comment]
totally agree @lwshang , at this point it's hard to track whats left and where people can jump in and still contribute

**Comment by skade** [comment]
I changed the list above. Anything more complex would probably need breaking things up into tickets.

**Comment by skade** [comment]
Opened PRs for the last pages, we should be able to remove skeletons over this weekend \o/.

There's a few outstanding issues, but they were there before.

**Comment by skade** [comment]
I posted a final PR here. Thanks @dzhibas @yayoc @Pjb518 @wizofe @eatrero @andirotter

**Comment by skade** [comment]
Done.
