### ISSUE TITLE
Front page layout issue: Right column using too much space

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#805]
# Design Bug Report

## Page(s) Affected
"/"

## What needs to be fixed?

![Screenshot_2019-05-25 Rust programming language](https://user-images.githubusercontent.com/47542/58364554-9aeece00-7eb6-11e9-8dbc-f050a14e9bdf.png)

The right column is using all remaining space.

## Suggested Improvement

Have the right column use as much space as the others.

**Comment by dzhibas** [comment]
fix in here: https://github.com/rust-lang/www.rust-lang.org/pull/812
