### ISSUE TITLE
Networking page: buttons not aligned

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#808]
# Design Bug Report

## Page(s) Affected
`/what/networking`/

## What needs to be fixed?

![Screenshot_2019-05-25 Networking - Rust programming language](https://user-images.githubusercontent.com/47542/58367381-d30a0700-7ede-11e9-8862-3f9c486eb0e4.png)

The buttons are not aligned.

**Comment by travisboss** [comment]
@skade can this me marked closed?

**Comment by XAMPPRocky** [comment]
Closing as solved
