### ISSUE TITLE
Possible Typo on Code of Conduct Page

### ISSUE THREAD

**Issue by eignnx** [rust-lang/www.rust-lang.org#814]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/policies/code-of-conduct

## What needs to be fixed?
On the second-to-last sentence of the page:

> If you wish to use this code of conduct for your own project, consider explicitly mentioning **your** moderation policy or making a copy with your own moderation policy so as to avoid confusion.

Are we sure we want to be asking people to mention *their own* moderation policy? It seems like this should be either:

1. > . . . consider explicitly mentioning **our** moderation policy . . .
1. > . . . consider explicitly mentioning **it in** your moderation policy . . .

## Suggested Improvement
If this is indeed a typo, it might need to be changed in both `master` AND in the `i18n` branch.

**Comment by skade** [comment]
> Are we sure we want to be asking people to mention their own moderation policy?

To my reading, yes, that's the intention. People should set up their own moderation policy and link to it if they are using our Code of Conduct. Moderation policies are much more custom and ours is very much based on the project structure.

**Comment by skade** [comment]
I'll assign @Manishearth, you're part of mods and I think I'd be best to have a native speaker review this :).

**Comment by Manishearth** [comment]
I'm not a moderator anymore, but yes, @skade is correct. The current moderation policy is specific to things managed by the Rust moderation teams. These teams do not moderate random projects that choose to adopt the Rust CoC :smile: 

A recurring problem with code of conducts is that people use a well-known one but neglect to write down a moderation policy, which means that when there are issues people don't know where to report them or how they will be handled. We're trying to mitigate that here by explicitly bringing this to peoples' attention and urging them to write down a policy for it.
