### ISSUE TITLE
`cargo watch` Constantly Recompiles

### ISSUE THREAD

**Issue by eignnx** [rust-lang/www.rust-lang.org#827]
# Technical Bug Report
## Your Environment
| Software         | Version(s) |
|-------------------|--------------|
| (@eignnx) Ubuntu | 16.04 |
| (@madmalik) MacOS | 10.14.3 Mojave |
| cargo-watch | 7.2.1 |
| Form Factor      | Desktop |

## Is this an issue with Rust, CSS, or HTML (or a combination)?
Issue with `cargo watch`

## Expected Behavior
`cargo watch -x run` ought to recompile only when actual changes are detected

## Current Behavior
`cargo watch -x run` constantly recompiles the project even when no changes have been made. I have tried running the command when no text editors are open, and the problem persists.

## Step to Reproduce
1. Get on my or @madmalik 's computer,
1. clone the repo,
1. run `cargo watch -x run`.

## Screenshots
I ran `cargo watch --debug -x run` and screenshotted the output on the first recompile:

![image](https://user-images.githubusercontent.com/34199632/58509284-3062ba00-8164-11e9-8f4d-11f08e892f9b.png)

## Suggetions
This seems to indicate that the `static/styles` folder is changing upon compilation, and that is triggering `cargo watch` to recompile again.

I believe `cargo watch` checks your `.gitignore` for files to NOT watch. Is there some ignore pattern we could add that would solve this problem?

## Trace
Here's a file with the trace: [CargoWatchProblemTrace.txt](https://github.com/rust-lang/www.rust-lang.org/files/3229555/CargoWatchProblemTrace.txt)

**Comment by Manishearth** [comment]
Yeah the webapp adds some files to static/styles (these are gitignored already though) when run

**Comment by skade** [comment]
Hm, updated cargo-watch to 7.2.1, ran a full git clean and it works for me.

**Comment by madmalik** [comment]
Works flawlessly for me now!

**Comment by eignnx** [comment]
Works for me too! Could we update the README to ensure new contributors don't download the wrong version?

**Comment by Zexbe** [comment]
It works for me too, and I am a new contributor. I think the update has been out long enough that it's no longer an issue.

**Comment by XAMPPRocky** [comment]
Okay, I'm going to close this as solved.
