### ISSUE TITLE
Link forge from the website

### ISSUE THREAD

**Issue by spastorino** [rust-lang/www.rust-lang.org#843]
Forge has a lot of documented procedures that are very handy. Would be great to link it somewhere from the main site. I guess somewhere in the community section.

/cc @nikomatsakis

**Comment by nikomatsakis** [comment]
I'm not sure where, but it's definitely true that many contributors have no idea forge exists

**Comment by skade** [comment]
The planned Contribution page (https://github.com/rust-lang/www.rust-lang.org/issues/440) would be a good place.

**Comment by XAMPPRocky** [comment]
Going to close this as a duplicate of #440
