### ISSUE TITLE
Fix Alfa Sans One

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#858]
# Content Bug Report

## Page(s) Affected
Alfa Sans One currently doesn't render correctly in the turkish locale. Alfa Sans is our headline font.

https://rust-lang.org/tr/governance

Is a good example.

## What needs to be fixed?
Replace the current font files by new ones with the full latin-ext field and make sure it works.

**Comment by XAMPPRocky** [comment]
I'm going to close this as a duplicate of #867
