### ISSUE TITLE
Automatic language switch?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/www.rust-lang.org#884]
I think it should automatically language switch to tr/zh-CN on first landing, but currently it doesn't.

**Comment by Manishearth** [comment]
I'm not sure if we should, I'd like URLs to remain static. I've heard complaints about automatic language selection before, too.

**Comment by skade** [comment]
I would avoid an automatic language switch. There's a _ton_ of work involved there.

* Do you detect locale or browser signalling?
* How do you store preference if someone switches back?
* Locale settings in browsers are often wrong, confusing travelling users

As we're talking about a single-language website, every document has a clearly defined locale. What we could do is present a banner if the browsers language header doesn't match the served document. Same problem there: it needs to be dismissable and that choice needs to stick.

**Comment by XAMPPRocky** [comment]
I'm going to close this, as I also don't think automatic language switch would be worth the tradeoffs. I think we could do a bit of a better job advertising the localisations though.

What I think would be feasible is adding some kind of client side code that checks if your browsers language matches one of the available and spawns a popup that offers you to the choice to switch and once the user has picked either yes or no, a flag in localstorage is set to not bring up the popup on future page loads.

**Comment by Manishearth** [comment]
Browser language is set by header and detection can't be completely client side. We could parse the Accept-Language header server side instead and add a little JS.

**Comment by XAMPPRocky** [comment]
@Manishearth I don't think that's right. You can use [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language)/[`navigator.languages`](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) to pick up the language on the client side

**Comment by Manishearth** [comment]
Hmm, yeah, I usually find Accept-Language to be better for this, but I guess it's fine given that we're not autoswitching
