### ISSUE TITLE
Possible places for unified Chinese translation?

### ISSUE THREAD

**Issue by renyuneyun** [rust-lang/www.rust-lang.org#887]
# Technical Feature Request
## Summary

Is there any willing to make a unified Chinese translation effort + small amount of annotations for varients (like what Wikipedia does)? (There is an FLOSS library called [OpenCC](https://github.com/BYVoid/OpenCC) to automatically convert between different varients. There is also [a rust binding](https://github.com/messense/opencc-rs).)
Is there any possibility for elaborating this in Pontoon?

## Motivation

As people are normally aware, there are two main streams of Chinese, known as Simplified Chinese (SC for short) and Traditional Chinese (TC for short). And people are generally aware that the SC varient is mostly used by the mainland, while TC is mostly used by Taiwan.

However, the fact is more complicated. (#97 contains some explanation , and I'll explain a little bit more here.)

A very quick version is: five different translation teams are needed to support (the most commonly appeared varients) SC (mainland), SC (Singapore), SC (Malaysia), TC (Taiwan) and TC (Hong Kong) and most of the words (and even sentences) are the same.

Basically, that is because SC and TC are just the difference of glyphs; although different regions have their slight different localized terms (especially technical terms), the language itself is the same.

One more fact worth noting: among more than 60k glyphs in total, 2k of them are simplified in SC, of which most are 1-1 (e.g. 門 -> 门). This means most of them are exactly the same. (Though considering the frequency, based on my experience, around 30% are different in everyday use.)

Therefore, it's will make the maintanance easier and update (for all varients) faster if most of the translations is done in one (cross-regional) group, and each region only specify the different varients where OpenCC doesn't work well.

## Drawbacks

This will require efforts in providing a converting mechanism between different varients.

This will also require some change in the Pontoon side.

## Rationale and alternatives
The first alternative is to have separate teams for each varient, which will a) waste a lot of effort in doing the same thing; b) make them not synchronized.
The second alternative is to have only one varient (or two)... meaning some will not be supported.

The impact of not doing is a) have separate update frequencies for different varients; b) have more teams wasting effort.
A likely result is because mainland have more people, the SC (mainland) varient is updated more frequently, while other varients are left un-updated for a long time (like the current state: mainland 100%, Taiwan 9%, nothing else).

## Maintenance

I can do the implementation of the website code if this is approved.
The exact detail still needs some discussion (see the last part below).

## Unresolved Questions
Maybe Pontoon needs also be updated to incorporate this pattern. However, I'm not familiar with Pontoon, so I can't say anything yet.
But I would say, ideally, this can be integrate this into Pontoon and provide the "projected" result as if there is already a translation in that language (varient). (Like what wikipedia does: the article text only has one version, of mixed editors from differen regions, but the user can specify which varient to use in the rendered article. They have an automatic convertor; for the part that can not be automatically correctly handled, special syntax is used to allow the editors to specify which to use in each varient.)

This can be implemented in either of the two ways, but discussion of which to choose is needed:
1. Provide a series of fallbacks and use OpenCC to do the convert (maybe also cached?), whenever there is no translation available for that specific varient.
2. Map different varients in advance (i.e. during the website application initialize) to different translations, and use the existing fallback.

**Comment by Manishearth** [comment]
Note that the website will already fall back, e.g there's tons of simplified chinese on http://www-staging.rust-lang.org/zh-TW where it's untranslated.

I feel like Pontoon integration here may be challenging. One potential idea is to autogenerate the zh-* locale with OpenCC and maintain a separate file with the divergences (which gets merged in to the autogenerated file). The divergences file is what's actually translated. 

How does OpenCC deal with non-1-1 mappings? (e.g. 里, which maps to both itself and 裡 in traditional)

**Comment by tigercosmos** [comment]
I disagree with such a rough way for translation. Terms, words, phrases, tones and any other matter about the language itself are used very differently by different regions or groups of people. Even for TCs, the version of TW and of HK are not the same.

**Comment by tigercosmos** [comment]
I think the fallback mechanism is great, just like Wikipedia, but I don't know if it works.

For the experience by @rust-tw translation, we translated directly from English and only sometimes refer the SC version, and the difference of result between TC and SC looks very different.

For example (from the `governance` page):
```
EN: Each major decision in Rust starts as a Request for Comments (RFC). Everyone is invited to discuss the proposal, to work toward a shared understanding of the tradeoffs. Though sometimes arduous, this community deliberation is Rust’s secret sauce for quality. 

SC: Rust 中的每个重要决定都是从征求意见稿（RFC）开始的。 任何人都可以参与提案的讨论，权衡利弊以便达成共识。 虽然有时会很艰难，但社区这种深思熟虑正是保证 Rust 高质量的秘诀。 

TC: Rust 每項重要的決定都是從請求意見稿（RFC）開始的。每個人都可以參與提案的討論，衡量利弊來達成共識。雖然有時會遇到困難，但是這樣社群的審議正是維持 Rust 品質的秘訣。 
```
<detail>

As you can  see, terms, words, phrases, tones and any other matter about the language itself are used very differently by different regions or groups of people. This is why we don't translate SC to TC directly. Even for TCs, the version of TW and of HK are not the same.

p.s. I only see `ZH-CN` and `ZH-TW` on Pontoon, where are the others?

**Comment by wusyong** [comment]
I think it can be this way(OpenCC you proposed) if rust is going to translate documentations in the future. People can tolerate those difference when their goals are to learning and grabbing know-hows. The website is for promotion, hence it could be more localized.

**Comment by upsuper** [comment]
I agree with @wusyong that website and similar stuff is better translated manually by local teams, because different places can have different idioms. So I don't think we should apply the auto conversion for website.

Larger technical documentations can benefit more from having combined effort with auto conversion. Tutorials would be something less clear, though.

That said, I guess Pontoon was initially designed for UI translation (for Mozilla's various projects) which is like website that ideally should be translated manually, so its design makes sense. But we may need different system (or Pontoon may need to be improved) to support the documentation use case.

That reminds me... is there any effort to produce `en-UK` (or even `en-AU`)? If we have a system to do unified translation, maybe other languages can benefit from that as well.

**Comment by renyuneyun** [comment]
@Manishearth It deals with non 1-1 mappings, but I don't know the technical details (a word segmenter & mapping table?). Based on my personal experience, the accuracy is very high (but the context may be different).

------

I agree documents like manuals can benefit more from this kind of efforts. But I also don't think the website will benefit significantly less, even if considering the promotion aspect.

The reason is simple: we are doing a translation, not doing a localized website (with different layouts).
Therefore, there is limited space for region-specific promotions. From what I see (from the websites with different *versions* in different regions), the main difference is the eye-catching sentence(s). They may use a very regionalized popular (regarding time) way to sentence, but the rest is mainly the difference between localized phrases (translations, for example).
(But this is just based on my personal experience with limited websites, mainly technology companies and PC manufactures.)

------

@upsuper I also wonder the tool for different variants of English.
Shouldn't they be easier? Or do people just don't care (i.e. not putting a wall between each other)?

**Comment by renyuneyun** [comment]
@tigercosmos Have you ever considered the difference is because they are translated **by different people**, rather than the difference between regional wording?

For your example, from my perspective, most "different" words can be used interchangeably. And neither reads perfectly from my perspective. Therefore, it actually shows the potential benefit (just like wikipedia does) to bring the best from both.

![rust-zh](https://user-images.githubusercontent.com/3293723/60983744-6d5cc780-a332-11e9-9ed4-5f86fc4e9f26.png)

**Comment by tigercosmos** [comment]
@renyuneyun  I agree with your point, so I support the fallback mechanism if there isn't any manual translation.

**Comment by XAMPPRocky** [comment]
I'm going to close this as the current direction of this issue is unclear. For integrating this functionality into Pontoon, I would recommend filing a bug on their [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Webtools&component=Pontoon&rep_platform=all&op_sys=all). If there are specific changes we can make to make it easier on website side, please file a separate issue.
