### ISSUE TITLE
Embedded Page

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang/www.rust-lang.org#9]
WG-Embedded
![](https://d2mxuefqeaa7sj.cloudfront.net/s_819CC68F4AD785DDE5910F2358BFE4833C0B9CF624FEDFA0F1EF8C667531BC02_1522252757002_IMG_1575.jpg)

Artifacts

- Visual examples of projects (videos - hobbyist projects)
- Getting started documentation
  - audience: knows some Rust and some embedded
  - can point to extra docs like the Rust book / Discovery book
- Production users / user stories
- Attributes
  - code reuse: drivers that run everywhere. Image constrast

Critique

- might have a different audience (developers or CTOs??)
- Florian thinks this would be a very good thing based on his trip to Embedded World

**Comment by flosse** [comment]
Hi guys, would you mind if we add a testimonial of [slowtec](https://github.com/slowtec)? (see  https://github.com/rust-embedded/wg/issues/108#issuecomment-434796760)
