### ISSUE TITLE
anchors for the teams and working groups on governance page

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/www.rust-lang.org#900]
# Technical Feature Request
## Summary
Add some kind of HTML anchor to permit linking directly to a working group from governance pages.

## Motivation
I would like to link directly to the wg-triage team found on [the operations team page](https://www.rust-lang.org/governance/teams/operations), but I cannot! I would like to be able to do `https://www.rust-lang.org/governance/teams/operations#wg-triage`.

## Drawbacks
I can't think of a reason. Perhaps a concern about link rot as team structure changes? 

## Rationale and alternatives
N/A

## Maintenance
No real ongoing maintenance required.

## Unresolved Questions
None

**Comment by pietroalbini** [comment]
Well, the link you posted [already works](https://www.rust-lang.org/governance/teams/operations#wg-triage). We should probably add a way to retrieve it from the page though.

**Comment by travisboss** [comment]
For an ideas maybe something like [this](https://www.quackit.com/css/codes/css_floating_menu.cfm)?  
Have a floating menu that can take you to different sections on each page?

**Comment by nikomatsakis** [comment]
@pietroalbini ha ok -- I didn't try it, I just expected it to be clickable or something. Should've tried it!

**Comment by AliSajid** [comment]
This appears to be complete and usable on the website. Please close.
