### ISSUE TITLE
Wrong Rust logo in social media images

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/www.rust-lang.org#901]
# Content Bug Report

## Page(s) Affected

Facebook, LinkedIn, all platforms that display social images based on \<meta>.

## What needs to be fixed?

The images in https://github.com/rust-lang/www.rust-lang.org/issues/181 are not the current Rust logo. Notice that the screenshots in the last comment have sharp spikes and a flat segment parallel to the circumference. The logo is supposed to have wavy spikes and no flat segment.

## Suggested Improvement

Replace the images linked from \<meta> tags with an up to date logo.

**Comment by Zexbe** [comment]
Example of correct image: https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/rust-logo-blk.svg
Example of wrong images:
https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/rust-social.jpg
https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/rust-social-wide.jpg
