### ISSUE TITLE
Get started section column/image stretching

### ISSUE THREAD

**Issue by inscroggnito** [rust-lang/www.rust-lang.org#903]
# Technical Bug Report
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | (Desktop) |
| Browser Type     | | Chrome or Safari
| Browser Version  | | Latest

## Is this an issue with Rust, CSS, or HTML (or a combination)?
Likely CSS, this appears to be a cross-browser issue in that Firefox's default handling of styles works a bit differently than Chrome or Safari. The image file is extremely large for wasm-ferris.png.

## Expected Behavior
The "get started" section looks like this in Firefox
<img width="1460" alt="Screen Shot 2019-07-12 at 11 38 32 AM" src="https://user-images.githubusercontent.com/2235671/61144563-c6e00600-a49a-11e9-90bb-181810ad4964.png">

## Current Behavior
In Chrome or Safari it looks like this:
<img width="1414" alt="Screen Shot 2019-07-12 at 11 38 28 AM" src="https://user-images.githubusercontent.com/2235671/61144583-d95a3f80-a49a-11e9-8597-6597ae35c629.png">

## Step to Reproduce
You should be able to see the difference just by visiting the site in the latest versions of the above mentioned browsers.

## Screenshots
Attached above

Simply re-sizing the image to the height that firefox defaults to (77px) based on its percentage-based elements results in this:

<img width="1537" alt="Screen Shot 2019-07-12 at 11 39 16 AM" src="https://user-images.githubusercontent.com/2235671/61144733-584f7800-a49b-11e9-9b58-9d4856df5aa6.png">

Based on that, I'll go ahead and submit a PR for the resized image (I searched and the image doesn't appear anywhere else that this would negatively impact)

**Comment by bdjnk** [comment]
Hi @inscroggnito, resizing the image isn't the correct fix for this problem.

This bug is the result of changes made in PR #874 (to fix bug #830). If tachyons (the CSS toolkit) is used carefully, this problem can be resolved (without regressing on the previous one).

I will submit a PR which does so soon and link it here.
