### ISSUE TITLE
[Doc] Recursive redirect

### ISSUE THREAD

**Issue by uuttff8** [rust-lang/www.rust-lang.org#905]
# Content Bug Report
When I press Documentation button that is on the footer here: https://www.rust-lang.org/learn
![Screenshot 2019-07-13 at 9 23 32 AM](https://user-images.githubusercontent.com/40335671/61168049-395eed80-a550-11e9-8e86-cae79dd55426.png)

I got redirect to https://doc.rust-lang.org/ that is redirect me to https://www.rust-lang.org/learn
## Page(s) Affected
https://doc.rust-lang.org/
https://www.rust-lang.org/learn

## What needs to be fixed?
redirect to https://doc.rust-lang.org/std/index.html

**Comment by skade** [comment]
That's a good catch. I believe the redirect is right though and the footer link should go to `/learn`.

If not, it should go to the documentation landing page.

@steveklabnik what was the most recent take on this?

**Comment by XAMPPRocky** [comment]
I'm going to close this as wontfix as it seems this is intentional.
