### ISSUE TITLE
Link timetill.rs from the community page

### ISSUE THREAD

**Issue by skade** [rust-lang/www.rust-lang.org#914]
# Content Feature Request
## Summary
Find a good place to link timetill.rs

## Motivation
timetill.rs is a maintained website showing dates of conferences and their CFP dates.

## Drawbacks
timetill.rs might go out of maintenance. In that case, we can remove the link.

**Comment by XAMPPRocky** [comment]
In regards to maintenance, I have designed timetill.rs to be easily passively maintained. New conferences are added through a JSON file anyone can submit PR with containing their event. The site is hosted on GitHub Pages so the only thing that I need to actively ensure doesn't expire is the domain.

As to where to put it on the website, The events subsection on the community page seems appropriate. It could be a link there or inside the [2019 conference lineup](https://blog.rust-lang.org/2019/05/20/The-2019-Rust-Event-Lineup.html) page.

**Comment by skade** [comment]
Uh, we need to patch the lineup page. The dates are known and Rust.Tokyo isn't there.
________________________________
