### ISSUE TITLE
Buttons in `Where to talk` section on the Community page are not aligned

### ISSUE THREAD

**Issue by wyze** [rust-lang/www.rust-lang.org#918]
# Design Bug Report

## Page(s) Affected
Buttons in the `Where to talk` section on the community page are not aligned. They should be either top aligned or bottom aligned. Seems previously in #551 it was requested to be top-aligned. Looks like a combo of #793 and #872 caused the alignment to be off.

## What needs to be fixed?
To top align the buttons, we would just remove the `flex-grow-1` on the items in this section. This would currently work as all the `divs` have same number of lines of content. We could add a `height` (`250px` for 1 line, `290px` for 2 lines) to push them down further for a little buffer.

To bottom align the buttons, we would just remove the `mb3` class on the `li` element surrounding the `Learn more about teams` button.

## Suggested Improvement
I have no opinion on which way they should align. I would love to do the PR to fix it once a decision has been made.

Attaching some screenshots for clarity.

### Current

![image](https://user-images.githubusercontent.com/186971/63275947-0bb04700-c268-11e9-8fd4-056e6246d148.png)

### Bottom aligned

<details>
<img src="https://user-images.githubusercontent.com/186971/63276049-3bf7e580-c268-11e9-92a1-bb84067d3f93.png">
</details>

### Top aligned (with room for 1 more line)

<details>
<img src="https://user-images.githubusercontent.com/186971/63276466-0b647b80-c269-11e9-8630-fa44518aebd3.png">
</details>

### Top aligned (with room for 2 more lines)

<details>
<img src="https://user-images.githubusercontent.com/186971/63276273-aad53e80-c268-11e9-92f8-ba7d6b1a7c6e.png">
</details>

**Comment by jsjoeio** [comment]
Wow. Impressed with the thorough writeup + the suggestion on how to fix this 👏

Are you still planning to do this @wyze or can I pick it up?

**Comment by wyze** [comment]
Thanks! I did plan on fixing it, but was just waiting to hear from someone on the direction which they wanted to go.

**Comment by pietroalbini** [comment]
Hmm, personally I'd prefer top aligned, do you have any opinion @XAMPPRocky?

**Comment by XAMPPRocky** [comment]
@wyze Thank you for your issue! I agree with @pietroalbini and would say top-aligned would be preferred here.
