### ISSUE TITLE
Wrong Firefox logo

### ISSUE THREAD

**Issue by dashaw92** [rust-lang/www.rust-lang.org#938]
# Content Bug Report

## Page(s) Affected
[https://www.rust-lang.org/what/networking](https://www.rust-lang.org/what/networking)
[https://www.rust-lang.org/what/wasm](https://www.rust-lang.org/what/wasm)
(any page `static/images/firefox.png` is referenced)

## What needs to be fixed?
Update the logo used to reflect the current branding for Firefox. A full size image download can be found at [https://mozilla.design/firefox/logos-usage/](https://mozilla.design/firefox/logos-usage/)

**Comment by Manishearth** [comment]
https://github.com/rust-lang/www.rust-lang.org/pull/948#issuecomment-551920602
