### ISSUE TITLE
pdf doesn't display properly in Chrome

### ISSUE THREAD

**Issue by refee** [rust-lang/www.rust-lang.org#942]
# Technical Bug Report
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | Desktop |
| Browser Type     | Google Chrome |
| Browser Version  | 77.0.3865.120 |

This unexpected behavior also appears in version 78.0.3904.70.

## Is this an issue with Rust, CSS, or HTML (or a combination)?
seems to be an issue with HTML.
> When the server sends the PDF with Content-Security-Policy: default-src 'none'
> the attribute inline styles of the synthetic HTML page are not applied. So only a small portion of the PDF is being displayed in the browser. 

REF: https://bugs.chromium.org/p/chromium/issues/detail?id=271452#c22

## Expected Behavior
The PDF (viewer) should fulfill the webpage.

## Current Behavior
The PDF (viewer) only shows in the top 20% (seemly) on the webpage, the remaining part is left in blank.

In DevTools, the Console shows error messages:
`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-C7vpsE1KLI7RuUgCprJTQZin6dWK+ccynbOx+OqjVow='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`
`Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.`

## Step to Reproduce
In the Chrome browser, open https://www.rust-lang.org/static/pdfs/Rust-Tilde-Whitepaper.pdf

## Screenshots
![image](https://user-images.githubusercontent.com/38122305/67953755-b232a400-fc2a-11e9-8279-6d48b4b00b1c.png)
PS: not a picture/pdf loading issue, the scroll bar shows the height of the pdf viewer area.

**Comment by refee** [comment]
Related issue: 
https://github.com/webcompat/web-bugs/issues/5095
https://bugs.chromium.org/p/chromium/issues/detail?id=271452

**Comment by refee** [comment]
The page functions normally in Chrome version 78.0.3904.97.

**Comment by goalaleo** [comment]
I have this same issue, but I'm using Version 79.0.3945.130 (Official Build) (64-bit). There are also some CSP errors in the console
<img width="1195" alt="Screenshot 2020-01-24 10 56 20" src="https://user-images.githubusercontent.com/3275302/73056999-0dc2a580-3e99-11ea-854e-32db52818443.png">
