### ISSUE TITLE
'rand' version collision in "Guessing Game"

### ISSUE THREAD

**Issue by plattrap** [rust-lang/www.rust-lang.org#949]
# Content Bug Report

## Page(s) Affected
https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#generating-a-random-number

## What needs to be fixed?
When generating the documentation there is a conflict generating the documentation for the 'rand' package because two different versions get installed.

```
user@dk-gui:~/rust/projects/guessing_game$ cargo doc --open
warning: output filename collision.
The lib target `rand` in package `rand v0.4.6` has the same output filename as the lib target `rand` in package `rand v0.3.23`.
Colliding filename is: /home/user/rust/projects/guessing_game/target/doc/rand/index.html
The targets should have unique names.
This is a known bug where multiple crates with the same name use
the same path; see <https://github.com/rust-lang/cargo/issues/6313>.
    Checking libc v0.2.65
 Documenting libc v0.2.65
    Checking rand v0.4.6
    Checking rand v0.3.23
 Documenting rand v0.4.6
 Documenting rand v0.3.23
 Documenting guessing_game v0.1.0 (/home/user/rust/projects/guessing_game)
    Finished dev [unoptimized + debuginfo] target(s) in 6.02s
     Opening /home/user/rust/projects/guessing_game/target/doc/guessing_game/index.html
```

## Suggested Improvement
Update the version of 'rand' used.

**Comment by carols10cents** [comment]
Hi, please file this issue over in [the book repo](https://github.com/rust-lang/book) and include which version of Rust you're using and the exact contents of your Cargo.toml, Cargo.lock, and src/main.rs. Thanks!
