### ISSUE TITLE
rustup is crap: provide releases as .tar.bz2 for offline installation

### ISSUE THREAD

**Issue by elmarstellnberger** [rust-lang/www.rust-lang.org#953]
rustup has severe problems downloading rust. Especially when I try it with tor/tails it fails: https://trac.torproject.org/projects/tor/ticket/32577. It would need to interrupt and restart downloads inactive for a certain time. Even better would be a complete availability for offline use as .tar.bz2 - as offered by any decent program or application. The downloadable .tar.bz2 should have an additional SHA512SUMS and SHA512SUMS.signed file as this is f.i. the standard for the Debian distribution.

**Comment by Manishearth** [comment]
This is not the right repo for this issue, see github.com/rust-lang/rustup/

However, please also go through https://rust-lang.org/conduct.html, your title is unacceptable for this project.

We have an issue on file for signing rustup: https://github.com/rust-lang/rustup/issues/1568

**Comment by elmarstellnberger** [comment]
signing is no panacea: you would need to keep the signing key offline; something which hardly anyone does. Providing a SHA512SUMS downloadable via tor is to my mind the best existent solution. There are inherent problems with scripts like rustup and I would suggest a way to forgo using rustup.

**Comment by elmarstellnberger** [comment]
Please reopen. I´d desire some discussion about a way to avoid using rustup.

**Comment by Manishearth** [comment]
> Please reopen. I´d desire some discussion about a way to avoid using rustup.

Please read my comment in full: _This is not the right repo for this issue_

**Comment by Manishearth** [comment]
Also, uh, we have non-rustup ways of installing things: https://forge.rust-lang.org/infra/other-installation-methods.html

**Comment by elmarstellnberger** [comment]
Many thanks for this link. I must have overlooked it.

**Comment by elmarstellnberger** [comment]
I can install the compiler via the .tar.gz but when I download the -src.tar.gz I lack some way to install it. How can I achieve the effect of 'rustup component add --toolchain "$(cat rust-toolchain)" rust-src' with the -src.tar.gz? - need to work offline

**Comment by elmarstellnberger** [comment]
Please respond to me here as I am currently blocked from IRC. My computer can not log in for some reason.

**Comment by Manishearth** [comment]
Again, this is not the right repository for this issue. I don't know the answer to your question, furthermore you have been rude and demanding and I don't really have an obligation to help.

Try asking on Discord.
