### ISSUE TITLE
Was given the Unix instruction not the Windows ones.

### ISSUE THREAD

**Issue by Y-Less** [rust-lang/www.rust-lang.org#954]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/tools/install

## What needs to be fixed?

Windows download link in not on the getting started page.  The website detected me as on Unix, and didn't provide any fallback option to say "no I'm not":

![image](https://user-images.githubusercontent.com/991078/69952519-a2430400-14f7-11ea-8d4f-505782bacd9a.png)

There is a "Other installation methods" link, but it is a 404.  I eventually found a link to the Windows installer in the rustp repo, but it wasn't obvious.

## Suggested Improvement
(optional) Do you have a suggestion for how to fix the problem? Include your ideas
here.

**Comment by steveklabnik** [comment]
What OS (with version) are you on? What browser are you using?

**Comment by Y-Less** [comment]
Windows 8.1.  Waterfox 56.2.4 (64-bit)

The issue was less that the website got it wrong, and more that there's no way to correct it (which also means there's no way to download for a different computer).

I also just tested on Waterfox 2019.10 and got the same thing.

**Comment by skade** [comment]
Seems like Waterfox only reports itself as Win64 and we only check for Win32.

https://github.com/rust-lang/www.rust-lang.org/blob/master/static/scripts/tools-install.js#L13-L57

I'm wondering if we're even bugged on other platforms and only saved by the fallback triggering on all major browsers.

**Comment by steveklabnik** [comment]
> and more that there's no way to correct it (which also means there's no way to download for a different computer).

At the bottom of the page, there's a link to https://forge.rust-lang.org/infra/other-installation-methods.html, which shows you installation instructions for all platforms. Well, it *should* link to that, but doesn't, that's https://github.com/rust-lang/www.rust-lang.org/issues/955
