### ISSUE TITLE
Broken link on https://www.rust-lang.org/tools/install

### ISSUE THREAD

**Issue by flo-l** [rust-lang/www.rust-lang.org#955]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/tools/install

## What needs to be fixed?
The link `Learn More` in the section `Other installation methods` is broken.

## Suggested Improvement
well, fix the link :smile: But I don't know the correct link target.

**Comment by flo-l** [comment]
OK I found it: https://forge.rust-lang.org/infra/other-installation-methods.html

**Comment by pietroalbini** [comment]
There should be a redirect by now. Still, it would be nice to link to the right place from the start.
