### ISSUE TITLE
i18n / l10n method?

### ISSUE THREAD

**Issue by renyuneyun** [rust-lang/www.rust-lang.org#96]
So, yeah, as it seems explicit the website needs to be i18n / l10n, there must be the backend support for that.
Presumbly this is done by using [fluent-rs](https://github.com/projectfluent/fluent-rs), and so the [Fluent Translation Language](https://projectfluent.org/fluent/guide/) will be the method of defining translation language.

I can imagine some behaviours which probably be good:

* Translations are placed in different directories (or simply different filenames) for different languages correspondingly
* Replace the text in the webpage template with variables (from `Context`), and load the variables dynamically (according to the language) in the rust code

There are two main questions before it can really be implemented into action:
1. Where to place the tranlation file?
    1. Should they be placed within the directory of the webpage template; or should they be placed together?
    2. Should the translations (in the same language) be placed in a hierarchical manner, or centralized?
2. How to name the translation text id?
    * When to use underscore `_` and when to use hyphen `-`?
    * Or, either way?

**Comment by VitalyAnkh** [comment]
The new website will be shipped on Dec. 6 so how can we add i18n content now? I’m very glad to add Chinese translations but I don’t how to contribute.

**Comment by skade** [comment]
Closing this, we have decided on a method.
