### ISSUE TITLE
Broken link: Command Line Book

### ISSUE THREAD

**Issue by spbogie** [rust-lang/www.rust-lang.org#960]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/learn
https://www.rust-lang.org/what/cli

## What needs to be fixed?
Link to the "Command Line Book" returns 404.
https://rust-lang-nursery.github.io/cli-wg/

**Comment by Manishearth** [comment]
https://twitter.com/CliRust/status/1203320942723813376?s=19
