### ISSUE TITLE
SSL cert expired, cannot install rust

### ISSUE THREAD

**Issue by ackerman76** [rust-lang/www.rust-lang.org#963]
# Technical Bug Report
## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | (Mobile/Tablet/Desktop) |
| Browser Type     | |
| Browser Version  | |

Pi 4, ARM71 Buster

## Is this an issue with Rust, CSS, or HTML (or a combination)?
Cannot install.

curl https://sh.rustup.rs -sSf | sh

curl error 60 SSL cert problem: unable to get local issuer cert. Cannot verify legitimacy of the server..

I tried to disable the cert check on curl, does not work. Tried http but the webserver forces redirect to https.

First time user, cannot figure out how to install. Expected package manager or another simple backup. Thanks

## Expected Behavior
Tell us what should have happened.

## Current Behavior
Tell us what happens instead of the expected behavior. If you are seeing an
error, please include the full error message and stack trace.

## Step to Reproduce
Please provide the steps to reproduce the issue.

## Screenshots
If relevant, please include screenshots of the issue you are seeing.

**Comment by Manishearth** [comment]
This isn't the correct place for this bug report. The certificate doesn't seem expired, have you tried updating your local root certificate store?

**Comment by Manishearth** [comment]
You can download rustup.sh directly using a browser and run it

**Comment by ackerman76** [comment]
Yes I tried all that with no change. This is a common problem for rust and curl does not work at all; several posts in community and no clear answer.

$ sudo update-ca-certificates
$ sudo update-ca-certificates --fresh

**Comment by pietroalbini** [comment]
@ackerman76 what output do you see for this command?

```
openssl s_client -connect rustup.rs:443
```
