### ISSUE TITLE
No way to get to docs for previous versions of std

### ISSUE THREAD

**Issue by plumenator** [rust-lang/www.rust-lang.org#965]
# Content Bug Report

## Page(s) Affected
https://doc.rust-lang.org/std/index.html

## What needs to be fixed?
Missing a drop down to select the version of `std`

## Suggested Improvement
Like at docs.rs, it would be great if we could switch between versions of the documentation.

**Comment by Manishearth** [comment]
Please file this issue on https://github.com/rust-lang/rust, this repository does not deal with the documentation.
