### ISSUE TITLE
Trying to install rust in Solaris 11.4 SPARC

### ISSUE THREAD

**Issue by Michele31415** [rust-lang/www.rust-lang.org#973]
When following the build directions on a Sun T4-1 I run

root@hemlock:~# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: unrecognized OS type: SunOS

It says to report these values:

navigator.platform: SunOS sun4v
navigator.appVersion: 5.0 (X11)

I know *someone* has rust on Solaris 11.4 because Oracle is advertising it in their latest update.  What am I doing wrong?

**Comment by Manishearth** [comment]
We support cross compiling to solaris, there are no official solaris Rust binaries: https://forge.rust-lang.org/release/platform-support.html

**Comment by Michele31415** [comment]
Thanks for the reply.  Forgive me if I'm being naive, but there, under Tier 2 I see
"sparcv9-sun-solaris	✓			SPARC Solaris 10/11, illumos"

Is this available, or do I have to cross-compile on say a Windows 7 machine?

**Comment by Manishearth** [comment]
Look at the checkboxes next to it, we only ship stdlib binaries, which are necessary for cross compilation but are not themselves a compiler.

**Comment by Michele31415** [comment]
OK, well perhaps I was confused by the statement here (https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Solaris_Prerequisites) that:
"OpenSolaris (and therefore also Solaris 11) can build Mozilla with a few extra packages installed:"

$ pfexec pkg install SUNWhea SUNWmercurial SUNWaudh SUNWxwinc SUNWxorg-headers SUNWgm4 SUNWgnome-common-devel SUNWcvs SUNWgmake sunstudio rust

The last package on that command is rust.  So I guess I need to mention that to the Mozilla people.

But thanks for the cross-compilation hint.  All I want is Firefox 68.  I managed to install rust in a Ubuntu VM and will try cross-compiling FF to Solaris there.

**Comment by Manishearth** [comment]
Yes, solaris might package rust, and you may be able to install it through
their package manager. _we_ do not provide solaris binaries in rustup.
