### ISSUE TITLE
Unknown localization at embedded example production page

### ISSUE THREAD

**Issue by senden9** [rust-lang/www.rust-lang.org#983]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/what/embedded

## What needs to be fixed?
On the noted embedded page there is a example production use with the words "Unknown localization embedded-testimonials- Unknown localization embedded-testimonials-".
This can be found next to the logo of @49nord,
![Screenshot_2020-01-15 Embedded devices](https://user-images.githubusercontent.com/905857/72464231-27972500-37d5-11ea-92ac-8e59607a9fe3.png)

**Comment by senden9** [comment]
Just saw that PR #970 addresses this.
Because i only searched open issues and no PRs I will not close this issue now.

**Comment by Manishearth** [comment]
We need to do a deploy
