### ISSUE TITLE
Unknown localization on licenses page

### ISSUE THREAD

**Issue by senden9** [rust-lang/www.rust-lang.org#984]
# Content Bug Report

## Page(s) Affected
https://www.rust-lang.org/policies/licenses

## What needs to be fixed?
The license page has a missing/wrong translation. We see here a "Unknown localization licenses-apache-v- ".
![image](https://user-images.githubusercontent.com/905857/72465381-61692b00-37d7-11ea-8fc8-c7ef34f9738c.png)

### Update:
I see this issue seems be fixed looking at https://github.com/rust-lang/www.rust-lang.org/blob/fab31a427709d67a9c1b6710f8a6c55d049dacf0/templates/policies/licenses.hbs#L17. Maybe the page just got not updated till the last 10 days from this repo?

**Comment by Manishearth** [comment]
We need to do a deploy
