### ISSUE TITLE
Linux Mint Installation

### ISSUE THREAD

**Issue by lozh** [rust-lang/www.rust-lang.org#999]
I'm using a fresh installation of Linux Mint. I tried following the instructions on https://www.rust-lang.org/learn/get-started to get rust installed. Basic programs would fail to compile with linker errors:
` = note: /usr/bin/ld: cannot find Scrt1.o: No such file or directory
          /usr/bin/ld: cannot find crti.o: No such file or directory
          collect2: error: ld returned 1 exit status
`
Installing the build-essentials (apt) package fixed it.

**Comment by XAMPPRocky** [comment]
@lozh Thank you for your issue! This issue tracker is only for issues that about the website itself. For issues about running the compiler, I would recommend re-opening your issue on [`rust-lang/rust`](https://github.com/rust-lang/rust).
